import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerDdpVisualContracts() {
  it('keeps the DDP product page aligned with its requirement document', () => {
    const page = readComponent('pages/products/data-development.vue')
    const pageHero = readComponent('components/common/PageHero.vue')
    const hero = readComponent('components/product/ddp/DdpHero.vue')
    const heroVisual = readComponent('components/product/ddp/DdpHeroVisual.vue')
    const heroSql = readComponent('components/product/ddp/ddpHeroSql.ts')
    const heroAnimation = readComponent('components/product/ddp/useDdpHeroAnimation.ts')
    const flowCanvas = readComponent('components/product/ddp/DdpFlowCanvas.client.vue')
    const flowNode = readComponent('components/product/ddp/DdpFlowNode.vue')
    const architecture = readComponent('components/product/ddp/DdpArchitecture.vue')
    const timeline = readComponent('components/product/ddp/DdpCapabilityTimelineSection.vue')
    const unified = readComponent('components/product/ddp/DdpUnifiedDevelopmentSection.vue')
    const alternatingTimeline = readComponent('components/common/AlternatingTimelineSection.vue')
    const featureGrid = readComponent('components/common/ProductFeatureGridSection.vue')
    const featureCard = readComponent('components/common/card/FeatureCard.vue')
    const cardGrid = readComponent('components/common/card/CardGrid.vue')
    const data = readComponent('data/ddp.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('DdpHero')
    expect(page).toContain('ProductFeatureGridSection')
    expect(page).toContain('DdpArchitecture')
    expect(page).toContain('DdpCapabilityTimelineSection')
    expect(page).toContain('DdpUnifiedDevelopmentSection')
    expect(page).toContain('CtaSection')
    expect(page).toContain('id="ddp-challenge"')
    expect(page).toContain('title="数据开发，正在成为企业增长瓶颈"')
    expect(page).toContain('title="持续释放企业数据生产力"')
    expect(page).toContain('title="赋能企业数据工程实践"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('columns="three"')
    expect(page).toContain('title-id="ddp-cta-title"')
    expect(page).not.toContain('<style')

    expect(hero).toContain('PageHero')
    expect(hero).toContain('import { Network }')
    expect(hero).toContain('badge="数曜·数据开发平台"')
    expect(hero).toContain('title-line="标准、智能、高效"')
    expect(hero).toContain('title-gradient="数据开发平台"')
    expect(hero).toContain('visual-label="SHUYAODDP_HORE_WEBM"')
    expect(hero).toContain('DdpHeroVisual')
    expect(hero).toContain('visual-size="fluid"')
    expect(hero).not.toContain('visual-size="large"')
    expect(pageHero).toContain("visualSize?: 'default' | 'large' | 'fluid'")
    expect(pageHero).toContain('lg:flex-row lg:items-center lg:justify-between')
    expect(pageHero).toContain('max-w-lg xl:max-w-xl 2xl:max-w-2xl')
    expect(heroVisual).not.toContain('图片占位符')
    expect(heroVisual).not.toContain('<style')
    expect(heroVisual).toContain('SQL 开发')
    expect(heroVisual).toContain('可视化编排')
    expect(heroVisual).toContain('h-[368px]')
    expect(heroVisual).toContain('<ClientOnly>')
    expect(heroVisual).toContain('bg-gradient-to-br from-primary/20 via-transparent to-primary/15 blur-2xl')
    expect(heroVisual).toContain('rounded-2xl border border-muted bg-default shadow-2xl')
    expect(heroVisual).toContain('size-3 rounded-full bg-red-500/70')
    expect(heroVisual).toContain('animate-pulse bg-primary')
    expect(heroVisual).toContain('DdpFlowCanvas')
    expect(heroSql).toContain("text: 'INSERT OVERWRITE TABLE '")
    expect(heroSql).toContain("text: 'dws_user_order_summary'")
    expect(heroSql).toContain("text: 'PARTITION '")
    expect(heroSql).toContain('${bizdate}')
    expect(heroSql).toContain("text: 'GROUP BY '")
    expect(heroSql).toContain("text: 'dwd_order_detail '")
    expect(heroSql).toContain("text: 'dim_user_info '")
    expect(heroSql).toContain('text-blue-500 dark:text-blue-400')
    expect(heroSql).toContain('text-emerald-600 dark:text-emerald-400')
    expect(heroSql).toContain('text-amber-600 dark:text-amber-400')
    expect(heroAnimation).toContain('LINE_REVEAL_INTERVAL_MS = 300')
    expect(heroAnimation).toContain('TAB_SWITCH_INTERVAL_MS = 5000')
    expect(flowCanvas).toContain('@vue-flow/core')
    expect(flowCanvas).toContain('DWD Detail')
    expect(flowCanvas).toContain('dwd_order_detail')
    expect(flowCanvas).toContain('Data Transform')
    expect(flowCanvas).toContain('join · aggregate')
    expect(flowCanvas).toContain('DIM Join')
    expect(flowCanvas).toContain('dim_user_info')
    expect(flowCanvas).toContain('DWS Summary')
    expect(flowCanvas).toContain('dws_user_order_summary')
    expect(flowCanvas).toContain('ADS Application')
    expect(flowCanvas).toContain('ads_user_value')
    expect(flowCanvas).toContain('rgba(148, 163, 184, 0.7)')
    expect(flowCanvas).not.toContain('MQTT')
    expect(flowCanvas).not.toContain('Kafka')
    expect(flowCanvas).not.toContain('PostgreSQL')
    expect(flowNode).toContain('min-w-[190px]')
    expect(flowNode).toContain('bg-emerald-500')
    expect(flowNode).toContain('bg-indigo-500')
    expect(flowNode).toContain('bg-purple-500')
    expect(flowNode).not.toContain('<style')

    expect(architecture).toContain('ProductArchitectureSection')
    expect(architecture).toContain('title="构建智能数据开发体系"')
    expect(architecture).toContain('fallback-text="数据开发体系架构图占位符"')
    expect(architecture).not.toContain('EnterpriseFlow')
    expect(architecture).not.toContain('<style')

    expect(timeline).toContain('AlternatingTimelineSection')
    expect(timeline).toContain('ddpTimelineItems')
    expect(timeline).toContain('title="覆盖数据开发全生命周期"')
    expect(timeline).not.toContain('BaseCard')
    expect(timeline).not.toContain('IconBox')
    expect(timeline).not.toContain('<style')
    expect(alternatingTimeline).toContain('SectionHeader')
    expect(alternatingTimeline).toContain('lg:left-1/2')
    expect(alternatingTimeline).toContain('space-y-[4.5rem]')
    expect(alternatingTimeline).toContain('role="img"')
    expect(alternatingTimeline).not.toContain('<style')

    expect(unified).toContain('ProductFeatureGridSection')
    expect(unified).toContain('ProductSystemFlowFrame')
    expect(unified).toContain('title="统一数据开发：从接入到交付"')
    expect(unified).toContain('ddpUnifiedDevelopmentItems')
    expect(unified).toContain('fallback-text="统一数据开发流程图占位符"')
    expect(unified).not.toContain('<style')
    expect(featureGrid).toContain('<slot name="after" />')
    expect(featureGrid).toContain('<slot name="before" />')
    expect(featureGrid).toContain(':icon-label="item.iconLabel"')
    expect(featureCard).toContain('iconLabel?: string')
    expect(featureCard).toContain('dt-icon-box dt-icon-box--gradient text-sm font-bold')
    expect(cardGrid).toContain('md:grid-cols-2 lg:grid-cols-4')
    expect(cardGrid).toContain('md:grid-cols-3')

    for (const text of [
      '数曜·数据开发平台',
      '数据开发，正在成为企业增长瓶颈',
      '构建智能数据开发体系',
      '覆盖数据开发全生命周期',
      '统一数据开发：从接入到交付',
      '赋能企业数据工程实践',
      '开启企业数据治理新征程',
    ]) {
      expect([page, hero, architecture, timeline, unified, data].join('\n')).toContain(text)
    }
  })
}
