import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerDgpVisualContracts() {
  it('keeps the DGP product page aligned with its requirement document', () => {
    const page = readComponent('pages/products/data-governance.vue')
    const pageHero = readComponent('components/common/PageHero.vue')
    const hero = readComponent('components/product/dgp/DgpHero.vue')
    const heroVisual = readComponent('components/product/dgp/DgpHeroVisual.vue')
    const featureGrid = readComponent('components/common/ProductFeatureGridSection.vue')
    const sectionHeader = readComponent('components/common/section/SectionHeader.vue')
    const sectionShell = readComponent('components/common/section/SectionShell.vue')
    const baseCard = readComponent('components/common/card/BaseCard.vue')
    const iconBox = readComponent('components/common/card/IconBox.vue')
    const cardGrid = readComponent('components/common/card/CardGrid.vue')
    const featureCard = readComponent('components/common/card/FeatureCard.vue')
    const baseTabs = readComponent('components/common/tabs/BaseTabs.vue')
    const architecture = readComponent('components/product/dgp/DgpArchitecture.vue')
    const systemCards = readComponent('components/common/SystemCards.vue')
    const evolution = readComponent('components/product/dgp/DgpEvolutionSection.vue')
    const useCases = readComponent('components/product/dgp/DgpUseCasesSection.vue')
    const data = readComponent('data/dgp.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('DgpHero')
    expect(page).toContain('ProductFeatureGridSection')
    expect(page).toContain('DgpArchitecture')
    expect(page).toContain('DgpEvolutionSection')
    expect(page).toContain('DgpUseCasesSection')
    expect(page).toContain('CtaSection')
    expect(page).toContain('为什么选择数曜·治理数据平台')
    expect(page).toContain('开启企业数据治理新征程')
    expect(page).toContain('title-id="dgp-cta-title"')
    expect(page).toContain('nowrap-subtitle')
    expect(page).not.toContain('top-padding')

    expect(hero).toContain('PageHero')
    expect(hero).toContain('import { Database }')
    expect(hero).toContain('badge="数曜·数据治理平台"')
    expect(hero).toContain('title-line="可用、可管、可信"')
    expect(hero).toContain('title-gradient="企业数据底座"')
    expect(hero).toContain('visual-label="SHUYAODGP_HORE_WEBM"')
    expect(hero).toContain('DgpHeroVisual')
    expect(hero).toContain('visual-size="large"')
    expect(pageHero).toContain("visualSize: 'default'")
    expect(pageHero).toContain("'max-w-lg self-center'")
    expect(pageHero).toContain("'max-w-[820px] self-stretch'")

    expect(heroVisual).toContain('HeroVisualShell')
    expect(heroVisual).toContain('数曜·数据治理平台')
    expect(heroVisual).toContain('Intelligent')
    expect(heroVisual).toContain('Governed Data')
    expect(heroVisual).toContain('dgpGovernanceScenes')
    expect(heroVisual).toContain('bg-dt-bg-soft/35')
    expect(heroVisual).toContain('sm:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]')
    expect(heroVisual).toContain('motion-safe:animate-pulse')
    expect(heroVisual).not.toContain('<style')
    expect(heroVisual).not.toContain('esenruizhi.com')

    expect(featureGrid).toContain('SectionShell')
    expect(featureGrid).toContain('SectionHeader')
    expect(featureGrid).toContain('CardGrid')
    expect(featureGrid).toContain('FeatureCard')
    expect(sectionShell).toContain('pb-32 lg:pb-44')
    expect(sectionShell).toContain('bg-dt-bg')
    expect(featureGrid).not.toContain('pt-24')
    expect(cardGrid).toContain('md:grid-cols-2 lg:grid-cols-4')
    expect(featureGrid).toContain(':title-id="titleId"')
    expect(cardGrid).toContain('auto-rows-fr items-stretch')
    expect(featureCard).toContain('BaseCard')
    expect(featureCard).toContain('IconBox')
    expect(featureCard).toContain('CardText')
    expect(baseCard).toContain('dt-card--feature')
    expect(baseCard).toContain('dt-card--adaptive')
    expect(baseCard).toContain('dt-card__accent')
    expect(iconBox).toContain('dt-icon-box')
    expect(iconBox).toContain('dt-icon-box--gradient')
    expect(featureGrid).not.toContain('mb-6')
    expect(featureCard).toContain('iconSize: 20')
    expect(featureCard).toContain("titleSize: 'sm'")
    expect(featureCard).toContain("descriptionSize: 'sm'")
    expect(featureGrid).not.toContain('text-base leading-relaxed')
    expect(featureGrid).not.toContain('min-h-[')
    expect(featureGrid).not.toContain('<style')

    expect(architecture).toContain('ProductArchitectureSection')
    expect(architecture).toContain('产品架构图占位符')
    expect(architecture).not.toContain(':heading-wide="false"')
    expect(architecture).not.toContain(':nowrap-subtitle="false"')
    expect(architecture).toContain('SystemCards')
    expect(architecture).not.toContain('EnterpriseFlow')

    expect(systemCards).toContain('CardGrid')
    expect(systemCards).toContain('FeatureCard')
    expect(systemCards).toContain('columns="three" gap="sm"')
    expect(systemCards).toContain('mt-10 lg:mt-12')
    expect(systemCards).toContain('dt-icon-box dt-icon-box--gradient')
    expect(cardGrid).toContain('md:grid-cols-3')
    expect(iconBox).toContain('dt-icon-box')
    expect(systemCards).not.toContain('rounded-2xl border border-dt-line')
    expect(systemCards).not.toContain('hover:border-dt-primary/40')
    expect(systemCards).not.toContain('min-h-[')
    expect(systemCards).not.toContain('<style')

    expect(evolution).toContain('企业数据治理体系的演进')
    expect(evolution).toContain('class="container pb-32 lg:pb-44"')
    expect(evolution).toContain('SectionHeader')
    expect(evolution).not.toContain('eyebrow-size="sm"')
    expect(evolution).not.toContain('eyebrow-tone="primary"')
    expect(evolution).toContain('nowrap-subtitle')
    expect(sectionHeader).toContain('section-heading--eyebrow-sm')
    expect(sectionHeader).toContain('section-heading--eyebrow-primary')
    expect(sectionHeader).toContain('section-heading--nowrap-subtitle')
    expect(evolution).toContain('class="py-4 lg:py-8"')
    expect(evolution).not.toContain('class="dt-card p-6 backdrop-blur-xl"')
    expect(evolution).toContain('rounded-full border border-primary/20 bg-primary/5 px-2.5 py-1 text-[13px] font-semibold text-primary/80')
    expect(evolution).toContain('lg:grid-cols-2 lg:gap-12')
    expect(evolution).toContain('图片占位符')
    expect(evolution).not.toContain('border border-dt-line bg-dt-bg-soft/40')
    expect(evolution).not.toContain('SectionHeading')
    expect(evolution).not.toContain('<style')

    expect(useCases).toContain('class="pb-32 lg:pb-44"')
    expect(useCases).toContain('text-center text-4xl font-bold leading-[1.2] tracking-tight text-highlighted')
    expect(useCases).toContain('text-center text-base text-default')
    expect(useCases).toContain('lg:whitespace-nowrap')
    expect(useCases).toContain('BaseTabs')
    expect(useCases).toContain('useCaseTabs')
    expect(useCases).toContain('variant="underline"')
    expect(baseTabs).toContain('role="tablist"')
    expect(baseTabs).toContain('role="tab"')
    expect(baseTabs).toContain('data-slot="root"')
    expect(baseTabs).toContain('data-slot="list"')
    expect(baseTabs).toContain('data-slot="trigger"')
    expect(baseTabs).toContain('data-slot="indicator"')
    expect(baseTabs).toContain('data-slot="label"')
    expect(baseTabs).toContain('px-5 py-4 text-base font-medium')
    expect(baseTabs).toContain('border-b border-dt-line')
    expect(useCases).toContain('role="tabpanel"')
    expect(useCases).toContain('BaseButton')
    expect(useCases).toContain('了解更多')
    expect(useCases).not.toContain('class="dt-tab"')
    expect(useCases).not.toContain('SectionHeading')
    expect(useCases).not.toContain('!pb-0')
    expect(useCases).not.toContain('<style')

    for (const text of [
      '让数据快速可用',
      '数据接入',
      '数据集成',
      '政务数据治理',
      '物联数据汇聚与治理',
    ]) {
      expect(data).toContain(text)
    }
  })
}
