import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerDmsVisualContracts() {
  it('keeps the DMS product page aligned with its requirement document', () => {
    const page = readComponent('pages/products/data-element-regulation.vue')
    const hero = readComponent('components/product/dms/DmsHero.vue')
    const heroVisual = readComponent('components/product/dms/DmsHeroVisual.vue')
    const heroAnimation = readComponent('components/product/dms/useDmsHeroAnimation.ts')
    const architecture = readComponent('components/product/dms/DmsArchitecture.vue')
    const intelligentRegulation = readComponent('components/product/dms/DmsIntelligentRegulationSection.vue')
    const businessValue = readComponent('components/product/dms/DmsBusinessValueSection.vue')
    const regulationProcess = readComponent('components/product/dms/DmsRegulationProcessSection.vue')
    const featureGrid = readComponent('components/common/ProductFeatureGridSection.vue')
    const data = readComponent('data/dms.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('DmsHero')
    expect(page).toContain('ProductFeatureGridSection')
    expect(page).toContain('DmsArchitecture')
    expect(page).toContain('DmsIntelligentRegulationSection')
    expect(page).toContain('DmsBusinessValueSection')
    expect(page).toContain('DmsRegulationProcessSection')
    expect(page).toContain('CtaSection')
    expect(page).toContain('id="dms-challenge"')
    expect(page).toContain('title="数据流通不断扩大 监管能力亟需升级"')
    expect(page).toContain('title="要素全流程监管能力"')
    expect(page).toContain('title="赋能多场景数据要素监管"')
    expect(page).toContain('columns="three"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('title-id="dms-cta-title"')
    expect(page).not.toContain('<style')

    expect(hero).toContain('PageHero')
    expect(hero).toContain('background-image-src="/images/products/product-hero-bg.png"')
    expect(hero).toContain('import { HardDrive }')
    expect(hero).toContain('badge="数曜·数据要素监管平台"')
    expect(hero).toContain('title-line="让数据流通安全、可信"')
    expect(hero).toContain('title-gradient="全流程监管平台"')
    expect(hero).toContain('visual-label="SHUYAODMS_HORE_WEBM"')
    expect(hero).toContain('class="min-h-[655px]"')
    expect(hero).toContain('visual-size="large"')
    expect(hero).toContain('DmsHeroVisual')
    expect(heroVisual).toContain('dmsHeroTitle')
    expect(heroVisual).toContain('dmsHeroTabs')
    expect(heroVisual).toContain('dmsHeroIntakeFields')
    expect(heroVisual).toContain('dmsHeroRiskRules')
    expect(heroVisual).toContain('dmsHeroRiskSummary')
    expect(heroVisual).toContain('dmsHeroDisposalFields')
    expect(heroVisual).toContain('dmsHeroDisposalSteps')
    expect(heroVisual).toContain('useDmsHeroAnimation')
    expect(heroVisual).toContain('getProgressWidthClass')
    expect(heroVisual).toContain('relative h-[320px]')
    expect(heroVisual).toContain('flex gap-1.5 border-t border-muted px-5 py-3')
    expect(heroVisual).not.toContain('<style')
    expect(heroVisual).not.toContain('style=')
    expect(heroAnimation).toContain('STAGE_DURATION_MS = 5000')
    expect(heroAnimation).toContain('PROGRESS_WIDTH_CLASSES')
    expect(heroAnimation).toContain('getProgressWidthClass')
    expect(heroAnimation).toContain('INTAKE_STEP_INTERVAL_MS = 800')
    expect(heroAnimation).toContain('RISK_SCAN_START_MS = 700')
    expect(heroAnimation).toContain('RISK_SCAN_INTERVAL_MS = 500')
    expect(heroAnimation).toContain('DISPOSAL_STEP_START_MS = 900')
    expect(heroAnimation).toContain('DISPOSAL_STEP_INTERVAL_MS = 800')
    expect(heroAnimation).toContain('DISPOSAL_DONE_DELAY_MS = 4100')
    expect(data).toContain('dmsHeroTitle')
    expect(data).toContain('dmsHeroTabs')
    expect(data).toContain('TX-20260811-042')
    expect(data).toContain('企业经营分析数据集')
    expect(data).toContain('敏感字段超范围')
    expect(data).toContain('EVT-20260811-017')
    expect(data).toContain('监管工单已创建')

    expect(architecture).toContain('ProductArchitectureSection')
    expect(architecture).toContain('title="构建数据要素流通全过程监管体系"')
    expect(architecture).toContain('RegulationArchitectureFlow')
    expect(architecture).toContain('class="max-lg:hidden"')
    expect(architecture).toContain('w-full overflow-hidden @container')
    expect(architecture).toContain('scale-[min(1,calc(100cqw/1704px))]')
    expect(architecture).toContain('-translate-x-1/2')
    expect(architecture).toContain('-translate-y-1/2')
    expect(architecture).not.toContain('EnterpriseFlow')
    expect(architecture).not.toContain('<style')

    expect(intelligentRegulation).toContain('AlternatingTimelineSection')
    expect(intelligentRegulation).toContain('dmsTimelineItems')
    expect(intelligentRegulation).toContain('title="智能监管，全程守护"')
    expect(intelligentRegulation).toContain('<template #visual="{ index }">')
    expect(intelligentRegulation).toContain('DmsCapabilityVisual')
    expect(intelligentRegulation).toContain('transparent-visual')
    expect(intelligentRegulation).not.toContain('BaseCard')
    expect(intelligentRegulation).not.toContain('IconBox')
    expect(intelligentRegulation).not.toContain('<style')

    const capabilityVisual = readComponent('components/product/dms/capability/DmsCapabilityVisual.vue')
    const ruleCenterVisual = readComponent('components/product/dms/capability/DmsRuleCenterVisual.vue')
    const eventMonitorVisual = readComponent('components/product/dms/capability/DmsEventMonitorVisual.vue')
    const workOrderVisual = readComponent('components/product/dms/capability/DmsWorkOrderVisual.vue')
    const cockpitVisual = readComponent('components/product/dms/capability/DmsCockpitVisual.vue')
    const lifecycleVisual = readComponent('components/product/dms/capability/DmsLifecycleVisual.vue')
    expect(capabilityVisual).toContain('DmsRuleCenterVisual')
    expect(capabilityVisual).toContain('DmsEventMonitorVisual')
    expect(capabilityVisual).toContain('DmsWorkOrderVisual')
    expect(capabilityVisual).toContain('DmsCockpitVisual')
    expect(capabilityVisual).toContain('DmsLifecycleVisual')
    for (const visual of [ruleCenterVisual, eventMonitorVisual, workOrderVisual, cockpitVisual, lifecycleVisual]) {
      expect(visual).toContain('useRuntimeTimeline')
      expect(visual).toContain('flex h-full min-h-[280px] flex-col overflow-hidden rounded-2xl border border-muted bg-white shadow-[0_0_16px_rgba(15,23,42,0.08)] transition-shadow duration-500 hover:shadow-[0_0_28px_rgba(30,68,224,0.22)] lg:min-h-[360px]')
      expect(visual).toContain('flex items-center border-b border-muted px-4 py-3')
      expect(visual).toContain('size-3 rounded-full bg-red-500/70')
      expect(visual).toContain('size-3 rounded-full bg-yellow-500/70')
      expect(visual).toContain('size-3 rounded-full bg-green-500/70')
      expect(visual).not.toContain('<style')
      expect(visual).not.toContain('style=')
    }
    expect(ruleCenterVisual).toContain('监管规则中心')
    expect(ruleCenterVisual).toContain('数据主体准入校验')
    expect(eventMonitorVisual).toContain('实时风险监测')
    expect(eventMonitorVisual).toContain('收敛去重')
    expect(workOrderVisual).toContain('智能工单闭环')
    expect(workOrderVisual).toContain('WO-20260921-017')
    expect(cockpitVisual).toContain('可视化监管驾驶舱')
    expect(cockpitVisual).toContain('getRuntimeBarWidthClass')
    expect(lifecycleVisual).toContain('全流程监管体系')
    expect(lifecycleVisual).toContain('全程追溯')

    expect(businessValue).toContain('ProductSystemSection')
    expect(businessValue).toContain('eyebrow="业务价值"')
    expect(businessValue).toContain('title="可量化的数据要素监管效能"')
    expect(businessValue).toContain('title-id="dms-business-value-title"')
    expect(businessValue).toContain('dmsValueItems')
    expect(businessValue).toContain('grid gap-5 md:grid-cols-2')
    expect(businessValue).toContain('group relative overflow-hidden rounded-2xl border border-default bg-default p-7 shadow-sm transition-shadow duration-500 hover:shadow-md lg:p-9')
    expect(businessValue).toContain('pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/40 to-transparent')
    expect(businessValue).toContain('text-4xl font-bold tracking-tight text-primary lg:text-5xl')
    expect(businessValue).toContain('mt-4 text-sm leading-relaxed text-muted')
    expect(businessValue).toContain('mt-5 text-[13px] italic text-dimmed/60')
    expect(businessValue).toContain('item.detail')
    expect(businessValue).not.toContain('<style')

    expect(regulationProcess).toContain('ProductFeatureGridSection')
    expect(regulationProcess).toContain('ProductSystemFlowFrame')
    expect(regulationProcess).toContain('dmsProcessItems')
    expect(regulationProcess).toContain('columns="three"')
    expect(regulationProcess).toContain('<template #before>')
    expect(regulationProcess).toContain('label="数据要素监管流程图"')
    expect(regulationProcess).toContain('fallback-text="数据要素监管流程图加载中"')
    expect(regulationProcess).toContain('DmsRegulationProcessFlow')
    expect(regulationProcess).toContain('<ClientOnly>')
    expect(regulationProcess).toContain('class="mb-12 max-lg:hidden lg:mb-16"')
    expect(regulationProcess).toContain('h-[560px] w-[1704px]')
    expect(regulationProcess).toContain('w-full overflow-hidden @container')
    expect(regulationProcess).toContain('scale-[min(1,calc(100cqw/1704px))]')
    expect(regulationProcess).toContain('-translate-x-1/2 -translate-y-1/2')
    expect(regulationProcess).not.toContain(':grid="false"')
    expect(regulationProcess).not.toContain('占位')
    expect(regulationProcess).not.toContain('<style')
    const regulationProcessFlow = readComponent('components/demo/dms-regulation-process/DmsRegulationProcessFlow.client.vue')
    expect(regulationProcessFlow).toContain("type: 'dmsRegulationProcessCurve'")
    expect(regulationProcessFlow).toContain("type: 'dmsRegulationProcessReturn'")
    expect(regulationProcessFlow).toContain('viewportY: 60')
    expect(regulationProcessFlow).toContain('事前预防')
    expect(regulationProcessFlow).toContain('事中监控')
    expect(regulationProcessFlow).toContain('事后处置')
    expect(regulationProcessFlow).toContain('监管分析')
    expect(regulationProcessFlow).toContain('规则持续优化')
    expect(regulationProcessFlow).not.toContain('<style')
    expect(featureGrid).toContain('<slot name="before" />')

    for (const text of [
      '数曜·数据要素监管平台',
      '数据流通不断扩大 监管能力亟需升级',
      '构建数据要素流通全过程监管体系',
      '要素全流程监管能力',
      '智能监管，全程守护',
      '可量化的数据要素监管效能',
      '事前预防 → 事中监控 → 事后处置 → 监管分析',
      '赋能多场景数据要素监管',
    ]) {
      expect([page, hero, architecture, intelligentRegulation, businessValue, regulationProcess, data].join('\n')).toContain(text)
    }
  })
}
