import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { whyTrustTabs } from '../data/why'

const root = process.cwd()

function readComponent(relativePath: string) {
  return readFileSync(join(root, relativePath), 'utf8')
}

function listVueFiles(directory: string): string[] {
  return readdirSync(join(root, directory), { withFileTypes: true }).flatMap((entry) => {
    const path = `${directory}/${entry.name}`

    if (entry.isDirectory()) {
      return listVueFiles(path)
    }

    return entry.name.endsWith('.vue') ? [path] : []
  })
}

describe('visual implementation contract', () => {
  it('uses existing visual assets for the first viewport and solution cards', () => {
    const page = readComponent('pages/index.vue')
    const hero = readComponent('components/home/HomeHero.vue')
    expect(hero).not.toContain('HeroTresBackground')
    expect(hero).not.toContain('TresCanvas')
    expect(page).toContain('class="home-hero-deliverables__video"')
    expect(page).toContain('花瓣素材_+暖蓝光泄漏背景可循环')

    for (const asset of [
      'public/images/home/solutions/industrial.K00G2HaS.png',
      'public/images/home/solutions/smart-env.CWc2pooP.png',
      'public/images/home/solutions/smart-energy.DHKY-NE1.png',
      'public/images/home/solutions/smart-Water.DHKY-NE1.png',
      'public/images/home/solutions/data-center-ai.CDu93Miw.png',
      'public/images/home/solutions/data.DHKY-NE1.png',
    ]) {
      expect(existsSync(join(root, asset))).toBe(true)
    }
  })

  it('keeps component styles in SCSS and avoids inline style attributes', () => {
    const vueFiles = listVueFiles('components')

    for (const file of vueFiles) {
      const source = readComponent(file)
      const sourceWithoutRequiredNavWrapper = source.replace(' style="position:relative;"', '')
      expect(source).toContain('lang="scss"')
      expect(sourceWithoutRequiredNavWrapper).not.toMatch(/\sstyle=/)
    }
  })

  it('includes responsive navigation and mobile product fallback', () => {
    expect(readComponent('components/navigation/SiteHeader.vue')).toContain('mobile-navigation')
    expect(readComponent('components/home/HomeProductSystem.vue')).toContain('product-system__mobile-flow')
  })

  it('keeps the Why DeepTrols page on the shared HOME baseline', () => {
    const page = readComponent('pages/why-deeptrols.vue')
    const hero = readComponent('components/why/WhyHero.vue')
    const tabs = readComponent('components/why/WhyTrustTabs.vue')
    const service = readComponent('components/why/WhyServiceReset.vue')
    const engine = readComponent('components/why/WhyEngine.vue')
    const data = readComponent('data/why.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('WhyHero')
    expect(page).toContain('WhyTrustTabs')
    expect(page).toContain('WhyServiceReset')
    expect(page).toContain('WhyEngine')
    expect(hero).toContain('import { Sparkles }')
    expect(hero).toContain('class="why-hero__badge mb-8 inline-flex items-center gap-2 rounded-full px-4 py-2"')
    expect(hero).toContain('<Sparkles class="why-hero__badge-icon"')
    expect(hero).toContain('<span>为什么选择 DeepTrols</span>')
    expect(hero).toContain('id="why-hero-title"')
    expect(hero).toContain('class="why-hero__title-line">数据、知识、智能统一</span>')
    expect(hero).toContain('class="why-hero__title-gradient">企业级AI应用服务商</span>')
    expect(hero).toContain('class="why-hero relative overflow-hidden bg-dt-bg"')
    expect(hero).toContain('container why-hero__body relative pt-24 pb-24 lg:pt-32 lg:pb-32')
    expect(hero).toContain('w-full max-w-2xl text-center lg:text-left')
    expect(hero).toContain('why-hero__actions flex flex-wrap items-center justify-center gap-4 lg:justify-start')
    expect(hero).toContain('why-hero__logos mt-24 border-t border-dt-line pt-12 lg:mt-28')
    expect(hero).not.toContain('padding: 144px')
    expect(hero).not.toContain('padding: 144px 0 96px')
    expect(hero).not.toContain('padding-bottom: 112px')
    expect(hero).toContain('font-size: 36px')
    expect(hero).toContain('font-size: 48px')
    expect(hero).toContain('font-size: 60px')
    expect(hero).toContain('line-height: 1.1')
    expect(hero).toContain('margin: 0 auto 32px')
    expect(hero).toContain('立即咨询')
    expect(hero).toContain('关于我们')
    expect(hero).toContain('BaseButton')
    expect(hero).toContain('HomeCustomerLogos')
    expect(hero).toContain('robot.webm?url')
    expect(hero).toContain('<video')
    expect(hero).toContain('autoplay')
    expect(hero).toContain('loop')
    expect(hero).toContain('muted')
    expect(hero).toContain('playsinline')
    expect(hero).not.toContain('Agentic solution V1.gif')
    expect(hero).not.toContain('new URL(')
    expect(hero).toContain('background-size: 72px 72px')
    expect(hero).toContain('mix-blend-screen')
    expect(hero).toContain('[mask-image:radial-gradient(76%_72%_at_50%_48%')
    expect(hero).toContain('max-w-[820px]')
    expect(hero).toContain('self-stretch')
    expect(hero).toContain('lg:h-full')
    expect(hero).toContain('h-[122%]')
    expect(hero).toContain('w-[122%]')
    expect(hero).toContain('!max-w-none')
    expect(hero).toContain('-translate-x-1/2')
    expect(hero).not.toContain('&::after')
    expect(hero).not.toContain('linear-gradient(180deg, var(--dt-color-bg) 0%')
    expect(hero).not.toContain('linear-gradient(90deg, var(--dt-color-bg) 0%')
    expect(hero).toContain('lg:grid-cols-[minmax(0,0.88fr)_minmax(520px,1fr)]')
    expect(hero).not.toContain('video {')
    expect(hero).not.toContain('box-shadow: 0 24px 60px')
    expect(tabs).toContain('为什么DeepTrols值得信赖')
    expect(tabs).toContain('class="why-trust dt-section relative pb-32 lg:pb-44"')
    expect(tabs).toContain('role="tablist"')
    expect(tabs).toContain('role="tab"')
    expect(tabs).toContain('role="tabpanel"')
    expect(tabs).toContain('class="why-trust__heading mb-12 text-center lg:mb-16"')
    expect(tabs).toContain('class="why-trust__tabs dt-segmented-tabs"')
    expect(tabs).toContain('class="dt-segmented-tab"')
    expect(tabs).toContain('class="why-trust__panel grid gap-5 md:grid-cols-2 lg:gap-6"')
    expect(tabs).toContain('class="why-trust__card dt-product-card min-h-[280px] !p-7 lg:!p-8"')
    expect(tabs).toContain('class="why-trust__icon dt-icon-box !size-12 !rounded-xl"')
    expect(tabs).toContain('font-size: 24px')
    expect(tabs).toContain('font-size: 18px')
    expect(tabs).not.toContain('dt-tab-list')
    expect(tabs).not.toContain('class="dt-tab"')
    expect(tabs).not.toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(service).toContain('class="why-service dt-section relative pb-32 lg:pb-44"')
    expect(engine).toContain('class="why-engine dt-section relative pb-32 lg:pb-44"')
    expect(service).toContain('业务价值可衡量，AI成果可持续')
    expect(service).toContain('fangangaishu@2x.png?url')
    expect(service).not.toContain('new URL(')
    expect(service).toContain('SectionHeading')
    expect(engine).toContain('重塑引擎')
    expect(engine).toContain('whyEngineLinks')
    expect(engine).toContain('SectionHeading')
    expect(data).toContain("label: '面向技术层'")
    expect(data).toContain("label: '面向业务层'")
    expect(data).toContain("label: '面向服务层'")
    expect(data).toContain("label: '面向长期价值'")
    expect(whyTrustTabs).toHaveLength(4)
    expect(whyTrustTabs.every((tab) => tab.features.length === 4)).toBe(true)
    expect(data).toContain('DeepTrolsOPS企业AI引擎')
    expect(data).toContain('FDE企业AI服务指南')
    expect(existsSync(join(root, 'doc/product/PAGE_REQUIREMENTS/WhyDeepTrols/imgs/robot.webm'))).toBe(true)
    expect(existsSync(join(root, 'doc/product/PAGE_REQUIREMENTS/WhyDeepTrols/imgs/fangangaishu@2x.png'))).toBe(true)
  })

  it('keeps EMQX-inspired homepage rhythm contracts', () => {
    const tailwind = readComponent('assets/css/tailwind.css')
    const tokens = readComponent('assets/scss/main.scss')
    const page = readComponent('pages/index.vue')
    const header = readComponent('components/navigation/SiteHeader.vue')
    const baseButton = readComponent('components/common/BaseButton.vue')
    const sectionHeading = readComponent('components/common/SectionHeading.vue')
    const hero = readComponent('components/home/HomeHero.vue')
    const logos = readComponent('components/home/HomeCustomerLogos.vue')
    const deliverables = readComponent('components/home/HomeDeliverables.vue')
    const productSystem = readComponent('components/home/HomeProductSystem.vue')
    const homeSolutions = readComponent('components/home/HomeSolutions.vue')
    const homeEcosystem = readComponent('components/home/HomeEcosystem.vue')
    const ecosystemVisual = readComponent('components/home/HomeEcosystemVisual.vue')
    const homeCases = readComponent('components/home/HomeCases.vue')
    const homeInsights = readComponent('components/home/HomeInsights.vue')
    const homeCta = readComponent('components/home/HomeCta.vue')
    const siteFooter = readComponent('components/layout/SiteFooter.vue')
    const footerMainIndex = siteFooter.indexOf('class="site-footer__main"')
    const footerNavCloseIndex = siteFooter.indexOf('</nav>')
    const footerSocialsIndex = siteFooter.indexOf('class="site-footer__socials"')
    const footerBottomRuleIndex = siteFooter.indexOf('class="site-footer__rule site-footer__rule--bottom"')
    const enterpriseFlow = readComponent('components/flow/EnterpriseFlow.client.vue')

    expect(tailwind).toContain('@import "tailwindcss"')
    expect(tailwind).toContain('@theme inline')
    expect(tailwind).toContain('--color-dt-primary: var(--dt-color-primary)')
    expect(tokens).toContain('--dt-container: 80rem')
    expect(tokens).toContain('--dt-container-2xl: 96rem')
    expect(tokens).toContain('--dt-color-bg: #151515')
    expect(tokens).toContain('--dt-color-text-highlighted: #ffffff')
    expect(tokens).toContain('--dt-color-nav-text: #e5e5e5')
    expect(tokens).toContain('--dt-radius-lg: 16px')
    expect(tokens).toContain('@media (min-width: 1536px)')
    expect(tokens).toContain('--dt-gradient-spotlight')
    expect(tokens).toContain('.dt-button')
    expect(tokens).toContain('.dt-tab-list')
    expect(tokens).toContain('.dt-tab')
    expect(tokens).toContain('.dt-segmented-tabs')
    expect(tokens).toContain('.dt-segmented-tab')
    expect(tokens).toContain('.dt-product-card')
    expect(tokens).toContain('.dt-ecosystem-card')
    expect(tokens).toContain('.dt-card-tag')
    expect(tokens).toContain('.dt-cta-panel')
    expect(tokens).not.toContain('@apply')
    expect(baseButton).toContain('data-slot="base"')
    expect(baseButton).toContain('data-slot="label"')
    expect(baseButton).toContain('data-slot="trailingIcon"')
    expect(baseButton).toContain('dt-button')
    expect(sectionHeading).toContain('titleId')
    expect(sectionHeading).toContain('nowrapSubtitle')
    expect(sectionHeading).toContain('class="section-heading dt-section-heading"')

    expect(header).toContain('height: var(--dt-header-height)')
    expect(header).toContain('margin-bottom: calc(var(--dt-header-height) * -1)')
    expect(header).toContain('data-slot="root"')
    expect(header).toContain('data-slot="container"')
    expect(header).toContain('src="/logo-while.svg"')
    expect(header).toContain('width: 200px')
    expect(header).not.toContain('filter: brightness(0) invert(1)')
    expect(header).toContain('background: rgba(21, 21, 21, 0.95)')
    expect(header).toContain('0 10px 15px -3px rgba(0, 0, 0, 0.1)')
    expect(header).toContain('site-header__left')
    expect(header).toContain('flex: 1 1 0')
    expect(header).toContain('site-header__github-icon')
    expect(header).toContain('site-header__language-icon')
    expect(header).toContain('site-header__github-icon size-5')
    expect(header).toContain('site-header__language-icon size-5')
    expect(header).toContain('site-header__text-link')
    expect(header).toContain('登录OPS')
    expect(header).toContain('font-size: 14px')
    expect(header).not.toContain('GitFork')
    expect(header).not.toContain('联系我们')
    expect(header).not.toContain('免费咨询')
    expect(header).toContain('<div style="position:relative;">')
    expect(header).toContain('function handleNavMouseEnter')
    expect(header).toContain('function handleNavMouseLeave')
    expect(header).toContain('@mouseenter="handleNavMouseEnter(item, index)"')
    expect(header).toContain('@mouseleave="handleNavMouseLeave(item)"')
    expect(header).toContain(":class=\"{ 'direct-link': !hasMega(item) }\"")
    expect(header).toContain('color: var(--dt-color-nav-text)')
    expect(header).toContain('color: var(--dt-color-text-highlighted)')
    expect(header).toContain('&.direct-link:hover')
    expect(header).toContain('color: var(--dt-color-primary)')
    expect(header).toContain('rgba(39, 30, 53, 0.5)')
    expect(header).toContain('color-mix(in oklab, var(--dt-color-bg-elevated) 50%, transparent)')
    expect(header).toContain('border-radius: var(--dt-ui-radius)')
    expect(header).not.toContain('max-width: var(--dt-container)')
    expect(header).not.toContain('@media (max-width: 1279px)')
    expect(page).toContain('class="home-hero-deliverables"')
    expect(page).toContain('class="home-hero-deliverables__video"')
    expect(page).toContain('class="home-hero-deliverables__mask"')
    expect(page).toContain('rgba(21, 21, 21, 0.4)')
    expect(page).toContain('rgba(21, 21, 21, 0.95) 0%')
    expect(page).toContain('var(--dt-color-bg) 100%')
    expect(page).toContain('      </div>\n      <HomeProductSystem />')
    expect(hero).toContain('padding-top: 128px')
    expect(hero).toContain('font-size: 60px')
    expect(hero).toContain('background: transparent')
    expect(hero).not.toContain('home-hero__wash')
    expect(hero).not.toContain('ClientOnly')
    expect(logos).toContain('padding-top: 5.5rem')
    expect(logos).toContain('gap: 4rem')
    expect(deliverables).toContain('padding: clamp(3.5rem, 7vw, 6rem) 0 8rem')
    expect(deliverables).toContain('flex: 0 0 40%')
    expect(deliverables).toContain('min-height: 280px')
    expect(deliverables).toContain('padding: 48px')
    expect(deliverables).toContain('padding-right: 112px')
    expect(deliverables).toContain('linear-gradient(to right, #181524, #271e35)')
    expect(deliverables).toContain('aria-roledescription="轮播"')
    expect(deliverables).toContain('showPreviousDeliverable')
    expect(deliverables).toContain('showNextDeliverable')
    expect(deliverables).toContain('data-active-slide')
    expect(deliverables).toContain('flex: 0 0 100%')
    expect(deliverables).toContain('transform: translate3d(-100%, 0, 0)')
    expect(deliverables).toContain('transform: translate3d(-200%, 0, 0)')
    expect(deliverables).not.toContain('animation:')
    expect(deliverables).not.toContain('deliverablesCarousel')
    expect(deliverables).not.toContain('deliverablesMarquee')
    expect(deliverables).toContain('font-size: 20px')
    expect(deliverables).toContain('font-size: 24px')
    expect(deliverables).toContain('font-size: 14px')
    expect(deliverables).toContain('display: none')
    expect(deliverables).not.toContain('What We Deliver')

    expect(productSystem).toContain('eyebrow="DeepTrols OPS"')
    expect(productSystem).toContain('title="连接真实业务与人工智能"')
    expect(productSystem).toContain('以数据与知识底座桥接企业业务与人工智能。赋能 AI Agent，实现对真实业务的支撑。')
    expect(productSystem).toContain('nowrap-subtitle')
    expect(productSystem).toContain('.product-system :deep(.section-heading)')
    expect(productSystem).toContain('.product-system :deep(.section-heading__subtitle)')
    expect(productSystem).toContain('font-size: 20px')
    expect(productSystem).toContain('white-space: nowrap')
    expect(productSystem).toContain('role="img"')
    expect(productSystem).toContain('aria-label="DeepTrols OPS platform architecture"')
    expect(productSystem).toContain('height: 560px')
    expect(productSystem).toContain('rgba(148, 163, 184, 0.12) 1px')
    expect(productSystem).toContain('background-size: 48px 48px')
    expect(productSystem).toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(productSystem).toContain('class="product-system__card dt-product-card"')
    expect(productSystem).toContain('class="product-system__card-accent dt-product-card__accent"')
    expect(productSystem).toContain('class="product-system__card-icon dt-icon-box"')
    expect(productSystem).toContain('product-system__card-accent')
    expect(productSystem).toContain('<h3>{{ card.name }}</h3>')
    expect(productSystem).not.toContain('{{ card.title }}')

    expect(homeSolutions).toContain('eyebrow="Use Cases"')
    expect(homeSolutions).toContain('title="驱动各行业智能提升"')
    expect(homeSolutions).toContain('覆盖智能制造、企业运营、AI基础设施等核心领域，帮助企业快速构建可持续演进的智能化能力')
    expect(homeSolutions).toContain('nowrap-subtitle')
    expect(homeSolutions).toContain('.solutions :deep(.section-heading__subtitle)')
    expect(homeSolutions).toContain('font-size: 20px')
    expect(homeSolutions).toContain('white-space: nowrap')
    expect(homeSolutions).toContain('role="tablist"')
    expect(homeSolutions).toContain('class="solutions__tabs dt-tab-list"')
    expect(homeSolutions).toContain('class="dt-tab"')
    expect(homeSolutions).toContain('role="region"')
    expect(homeSolutions).toContain('aria-roledescription="carousel"')
    expect(homeSolutions).toContain('data-orientation="horizontal"')
    expect(homeSolutions).toContain('data-slot="root"')
    expect(homeSolutions).toContain('data-slot="viewport"')
    expect(homeSolutions).toContain('data-slot="container"')
    expect(homeSolutions).toContain('role="group"')
    expect(homeSolutions).toContain('data-slot="item"')
    expect(homeSolutions).toContain('flex: 0 0 100%')
    expect(homeSolutions).toContain('transform: translate3d(-500%, 0, 0)')
    expect(homeSolutions).toContain('min-height: 420px')
    expect(homeSolutions).toContain('min-height: 520px')
    expect(homeSolutions).toContain('background: linear-gradient(to top, rgba(0, 0, 0, 0.95)')
    expect(homeSolutions).toContain('padding: 96px 24px 24px')
    expect(homeSolutions).toContain('font-size: 24px')
    expect(homeSolutions).toContain('class="group solutions__panel"')
    expect(homeSolutions).toContain('阅读案例')
    expect(homeSolutions).toContain('class="iconify iconify--lucide size-4 transition group-hover:translate-x-1"')
    expect(homeSolutions).toContain('line-height: 1.5')
    expect(homeSolutions).not.toContain('了解更多')
    expect(homeSolutions).toContain('查看所有应用场景')
    expect(homeSolutions).toContain('href="/solutions#use-cases"')
    expect(homeSolutions).toContain('BaseButton')
    expect(homeSolutions).not.toContain('查看所有解决方案')

    expect(homeEcosystem).toContain('eyebrow="ecosystem"')
    expect(homeEcosystem).toContain('title="连接企业 AI 全链路的开放生态"')
    expect(homeEcosystem).toContain('subtitle="连接算力、模型、社区与行业知识，构建开放 AI 生态"')
    expect(homeEcosystem).toContain('nowrap-subtitle')
    expect(homeEcosystem).toContain('.ecosystem :deep(.section-heading__subtitle)')
    expect(homeEcosystem).toContain('font-size: 20px')
    expect(homeEcosystem).toContain('white-space: nowrap')
    expect(homeEcosystem).toContain('HomeEcosystemVisual')
    expect(homeEcosystem).toContain('class="group ecosystem-card dt-ecosystem-card"')
    expect(homeEcosystem).toContain('class="ecosystem-card__tag dt-card-tag"')
    expect(homeEcosystem).toContain(':to="card.href"')
    expect(homeEcosystem).toContain('grid-template-columns: 1fr')
    expect(homeEcosystem).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(homeEcosystem).toContain('gap: 24px')
    expect(homeEcosystem).toContain('margin-top: 48px')
    expect(homeEcosystem).toContain('width: 48px')
    expect(homeEcosystem).toContain('height: 48px')
    expect(homeEcosystem).toContain('font-size: 20px')
    expect(homeEcosystem).toContain('max-width: 75%')
    expect(homeEcosystem).toContain('font-size: 16px')
    expect(homeEcosystem).toContain('width: 32px')
    expect(homeEcosystem).toContain('height: 32px')
    expect(homeEcosystem).toContain('bottom: 32px')
    expect(homeEcosystem).toContain('opacity: 0')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__cloud-grid)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__base-line)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__flow)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__led)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__device-label)')
    expect(homeEcosystem).not.toContain('title="Ecosystem"')
    expect(ecosystemVisual).toContain("variant: 'token' | 'agent' | 'infra' | 'report'")
    expect(ecosystemVisual).toContain('ecosystem-visual--${variant}')
    expect(ecosystemVisual).toContain("variant === 'token'")
    expect(ecosystemVisual).toContain("variant === 'agent'")
    expect(ecosystemVisual).toContain("variant === 'infra'")
    expect(ecosystemVisual).toContain('cloudDots')
    expect(ecosystemVisual).toContain('r="0.35"')
    expect(ecosystemVisual).toContain('filter id="glow-map"')
    expect(ecosystemVisual).toContain('filter id="edgeGlow"')
    expect(ecosystemVisual).toContain('filter id="serverGlow"')
    expect(ecosystemVisual).toContain('filter id="bridgeGlow"')
    expect(ecosystemVisual).toContain('x1: 105')
    expect(ecosystemVisual).toContain('x2: 125')
    expect(ecosystemVisual).toContain('x1: 120')
    expect(ecosystemVisual).toContain('x2: 140')
    expect(ecosystemVisual).toContain('x1: 80')
    expect(ecosystemVisual).toContain('x2: 115')
    expect(ecosystemVisual).toContain('transform: \'translate(115, 21)\'')
    expect(ecosystemVisual).toContain('transform: \'translate(135, 45)\'')
    expect(ecosystemVisual).toContain('transform: \'translate(105, 58)\'')
    expect(ecosystemVisual).toContain('论文')
    expect(ecosystemVisual).toContain('领域')
    expect(ecosystemVisual).toContain('top: -5px')
    expect(ecosystemVisual).toContain('right: -5%')
    expect(ecosystemVisual).toContain('top: -5%')
    expect(ecosystemVisual).toContain('height: 110%')
    expect(ecosystemVisual).toContain('width: 80%')
    expect(ecosystemVisual).toContain('width: 65%')
    expect(ecosystemVisual).toContain('stroke-dasharray="1 2"')
    expect(ecosystemVisual).toContain('stroke-dasharray="1 15"')
    expect(ecosystemVisual).toContain('animation-play-state: paused')
    expect(ecosystemVisual).toContain('stroke-dashoffset: 16')
    expect(ecosystemVisual).toContain('@keyframes ecosystemVisualFlow')
    expect(ecosystemVisual).toContain('@keyframes ecosystemVisualPulse')

    expect(homeCases).toContain('CUSTOMER STORIES')
    expect(homeCases).toContain('携手 DeepTrols 加速创新')
    expect(homeCases).toContain('助力客户加速创新、实现业务突破，同时显著降低成本。')
    expect(homeCases).toContain('SectionHeading')
    expect(homeCases).toContain('title-id="cases-title"')
    expect(homeCases).toContain('nowrap-subtitle')
    expect(homeCases).toContain('max-width: 96rem')
    expect(homeCases).toContain('padding: 0 16px 128px')
    expect(homeCases).toContain('padding-bottom: 176px')
    expect(homeCases).toContain('font-size: 20px')
    expect(homeCases).toContain('white-space: nowrap')
    expect(homeCases).toContain('padding: 40px 0 0')
    expect(homeCases).toContain('cases__shell')
    expect(homeCases).toContain('overflow: hidden')
    expect(homeCases).toContain('border-radius: 24px')
    expect(homeCases).toContain('background: rgba(38, 38, 38, 0.4)')
    expect(homeCases).toContain('0 1px 2px rgba(0, 0, 0, 0.05)')
    expect(homeCases).toContain('cases__controls')
    expect(homeCases).toContain('aria-label="Previous story"')
    expect(homeCases).toContain('aria-label="Next story"')
    expect(homeCases).toContain('dt-icon-button')
    expect(homeCases).toContain('role="tablist"')
    expect(homeCases).toContain('cases__logo-tabs')
    expect(homeCases).toContain('gap: 40px')
    expect(homeCases).toContain('gap: 56px')
    expect(homeCases).toContain('role="region"')
    expect(homeCases).toContain('aria-roledescription="carousel"')
    expect(homeCases).toContain('data-orientation="horizontal"')
    expect(homeCases).toContain('data-slot="root"')
    expect(homeCases).toContain('padding: 0')
    expect(homeCases).toContain('data-slot="viewport"')
    expect(homeCases).toContain('data-slot="container"')
    expect(homeCases).toContain('data-active-slide')
    expect(homeCases).toContain('transform: translate3d(-100%, 0, 0)')
    expect(homeCases).toContain('transform: translate3d(-200%, 0, 0)')
    expect(homeCases).toContain('min-height: 520px')
    expect(homeCases).toContain('<div class="cases__visual-overlay"></div>')
    expect(homeCases).not.toContain('<span></span>')
    expect(homeCases).not.toContain('span:nth-child')
    expect(homeCases).toContain('class="cases__button"')
    expect(homeCases).toContain(':href="story.href"')
    expect(homeCases).toContain('margin-top: auto')
    expect(homeCases).toContain('padding-top: 32px')
    expect(homeCases).toContain('BaseButton')
    expect(homeCases).toContain('variant="secondary"')
    expect(homeCases).toContain('阅读案例')
    expect(homeCases).toContain('class="cases__all-action"')
    expect(homeCases).toContain('href="/cases"')
    expect(homeCases).toContain('查看所有案例')
    expect(homeCases).toContain('margin-top: 32px')
    expect(homeCases).not.toContain('type="button"\n                          data-slot="base"')
    expect(homeCases).not.toContain('class="cases__read-link"')
    expect(homeCases).not.toContain('function readStory')
    expect(homeCases).not.toContain('navigateTo')
    expect(homeCases).not.toContain('阅读案例研究')
    expect(homeCases).not.toContain('class="cases__link"')
    expect(homeCases).toMatch(/h3 \{[\s\S]*font-size: 20px;[\s\S]*font-weight: 600;[\s\S]*line-height: 1\.25;/)
    expect(homeCases).toMatch(/\.cases__content p \{[\s\S]*font-size: 18px;[\s\S]*line-height: 1\.625;/)
    expect(homeCases).toContain('h3 {\n    font-size: 24px;\n  }')
    expect(homeCases).toContain('.cases__content p {\n    font-size: 20px;\n  }')
    expect(homeCases).not.toContain('title="CUSTOMER STORIES"')

    expect(homeInsights).toContain('SectionHeading')
    expect(homeInsights).toContain('eyebrow="Resources"')
    expect(homeInsights).toContain('title="创新、洞察与新闻"')
    expect(homeInsights).toContain('title-id="insights-title"')
    expect(homeInsights).toContain('class="insights__layout"')
    expect(homeInsights).toContain('grid-template-columns: 1fr')
    expect(homeInsights).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(homeInsights).toContain('gap: 24px')
    expect(homeInsights).toContain('margin-bottom: 48px')
    expect(homeInsights).toContain('font-size: 16px')
    expect(homeInsights).toContain('class="group insights__featured"')
    expect(homeInsights).toContain('class="group insights__item"')
    expect(homeInsights).toContain('aspect-ratio: 2 / 1')
    expect(homeInsights).toContain('aspect-ratio: 400 / 180')
    expect(homeInsights).toContain('aspect-ratio: auto')
    expect(homeInsights).toContain('border-radius: var(--dt-ui-radius)')
    expect(homeInsights).toContain('border-color: var(--dt-color-line-strong)')
    expect(homeInsights).toContain('transform: scale(1.05)')
    expect(homeInsights).toContain('transition: transform 500ms ease')
    expect(homeInsights).toContain('position: absolute')
    expect(homeInsights).toContain('inset: 0')
    expect(homeInsights).toContain('object-fit: cover')
    expect(homeInsights).toContain('-webkit-line-clamp: 3')
    expect(homeInsights).toContain('-webkit-line-clamp: 2')
    expect(homeInsights).toContain('-webkit-line-clamp: 1')
    expect(homeInsights).toContain('class="insights__all-link insights__all-link--desktop"')
    expect(homeInsights).toContain('class="insights__mobile-action"')
    expect(homeInsights).toContain('BaseButton')
    expect(homeInsights).toContain('查看全部资源')
    expect(homeInsights).not.toContain('insights__topline')
    expect(homeInsights).not.toContain('transform: translateY')

    expect(homeCta).toContain('class="home-cta"')
    expect(homeCta).toContain('class="container"')
    expect(homeCta).toContain('class="home-cta__panel dt-cta-panel"')
    expect(homeCta).toContain('构建企业自身的AI能力')
    expect(homeCta).toContain('让数据成为资产，让知识驱动决策，让AI创造价值')
    expect(homeCta).toContain('padding-bottom: 128px')
    expect(homeCta).toContain('padding-bottom: 176px')
    expect(homeCta).toContain('font-size: 36px')
    expect(homeCta).toContain('font-size: 48px')
    expect(homeCta).toContain('font-size: 20px')
    expect(homeCta).toContain('class="home-cta__actions"')
    expect(homeCta).toContain('gap: 24px')
    expect(homeCta).toContain('BaseButton')
    expect(homeCta).toContain('href="/contact"')
    expect(homeCta).toContain('href="/try"')
    expect(homeCta).toContain('咨询合作')
    expect(homeCta).toContain('申请试用')
    expect(homeCta).not.toContain('Start With DeepTrols')
    expect(homeCta).not.toContain('构建属于企业自己的 AI 能力')

    expect(siteFooter).toContain('class="site-footer"')
    expect(siteFooter).toContain('padding-top: 48px')
    expect(siteFooter).toContain('background: var(--dt-color-bg-soft)')
    expect(siteFooter).toContain('订阅 DeepTrols 最新资讯')
    expect(siteFooter).toContain('data-slot="base"')
    expect(siteFooter).toContain('dt-button dt-button--primary dt-button--lg')
    expect(siteFooter).toContain('class="site-footer__main"')
    expect(siteFooter).toContain('class="site-footer__identity"')
    expect(siteFooter).toContain('src="/logo-while.svg"')
    expect(siteFooter).toContain('width: 240px')
    expect(footerMainIndex).toBeGreaterThan(-1)
    expect(footerNavCloseIndex).toBeGreaterThan(footerMainIndex)
    expect(footerSocialsIndex).toBeGreaterThan(footerNavCloseIndex)
    expect(footerSocialsIndex).toBeLessThan(footerBottomRuleIndex)
    expect(siteFooter).toContain('</div>\n\n      <div class="site-footer__socials"')
    expect(siteFooter).toContain('class="site-footer__socials"')
    expect(siteFooter).toContain('aria-label="社交媒体"')
    expect(siteFooter).toContain('class="site-footer__social-link"')
    expect(siteFooter).toContain('aria-label="GitHub"')
    expect(siteFooter).toContain('aria-label="X"')
    expect(siteFooter).toContain('aria-label="哔哩哔哩"')
    expect(siteFooter).toContain('aria-label="LinkedIn"')
    expect(siteFooter).toContain('aria-label="微信公众号"')
    expect(siteFooter).toContain('margin-top: 40px')
    expect(siteFooter).toContain('gap: 24px')
    expect(siteFooter).toContain('iconify iconify--simple-icons w-full h-6')
    expect(siteFooter).toContain('class="site-footer__columns"')
    expect(siteFooter).toContain('grid-template-columns: repeat(5, minmax(0, 1fr))')
    expect(siteFooter).toContain('gap: 32px')
    expect(siteFooter).toContain('font-size: 14px')
    expect(siteFooter).toContain('line-height: 20px')
    expect(siteFooter).toContain('gap: 10px')
    expect(siteFooter).toContain('margin: 16px 0')
    expect(siteFooter).toContain('class="site-footer__group-rule"')
    expect(siteFooter).toContain('产品')
    expect(siteFooter).toContain('数曜·数据治理平台')
    expect(siteFooter).toContain('数曜·数据标签平台')
    expect(siteFooter).toContain('数曜·数据开发平台')
    expect(siteFooter).toContain('数曜·数据资产管理平台')
    expect(siteFooter).toContain('博曜·企业级知识管理平台')
    expect(siteFooter).toContain('探曜·AI物联感知平台')
    expect(siteFooter).toContain('Device Agent')
    expect(siteFooter).toContain('API安全管控平台')
    expect(siteFooter).toContain('API安全审计系统')
    expect(siteFooter).toContain('业务威胁感知系统')
    expect(siteFooter).toContain('使用场景')
    expect(siteFooter).toContain('智能制造')
    expect(siteFooter).toContain('智能环保')
    expect(siteFooter).toContain('智能水利')
    expect(siteFooter).toContain('智慧能源')
    expect(siteFooter).toContain('数据治理')
    expect(siteFooter).toContain('企业AI应用')
    expect(siteFooter).toContain('智慧城市')
    expect(siteFooter).toContain('智慧医疗')
    expect(siteFooter).toContain('行业')
    expect(siteFooter).toContain('制造业')
    expect(siteFooter).toContain('能源')
    expect(siteFooter).toContain('交通运输与物流')
    expect(siteFooter).toContain('政府/公共事业')
    expect(siteFooter).toContain('教育')
    expect(siteFooter).toContain('水利/水务')
    expect(siteFooter).toContain('金融服务')
    expect(siteFooter).toContain('城市治理')
    expect(siteFooter).toContain('零售')
    expect(siteFooter).toContain('服务')
    expect(siteFooter).toContain('Token Hub')
    expect(siteFooter).toContain('白皮书&报告')
    expect(siteFooter).toContain('产品文档')
    expect(siteFooter).toContain('算力与基础设施')
    expect(siteFooter).toContain('智能体社区')
    expect(siteFooter).toContain('translate-inline-px translate-y-[-2px] scale-inline-100 transform')
    expect(siteFooter).toContain('stroke-width="1.3"')
    expect(siteFooter).toContain('公司')
    expect(siteFooter).toContain('关于我们')
    expect(siteFooter).toContain('新闻动态')
    expect(siteFooter).toContain('合作伙伴')
    expect(siteFooter).toContain('加入我们')
    expect(siteFooter).toContain('联系我们')
    expect(siteFooter).toContain('品牌资源')
    expect(siteFooter).toContain('服务案例')
    expect(siteFooter).toContain('投资计划')
    expect(siteFooter).toContain('class="site-footer__filings"')
    expect(siteFooter).toContain('京公网安备100861001010000号')
    expect(siteFooter).toContain('京ICP备20018888号-4')
    expect(siteFooter).toContain('https://beian.miit.gov.cn/')
    expect(siteFooter).toContain('class="site-footer__copyright"')
    expect(siteFooter).toContain('@ 武汉深度数智科技有限公司 2026 版权所有')
    expect(siteFooter).toContain('justify-content: space-between')
    expect(siteFooter).not.toContain('© 2026 DeepTrols. All rights reserved')
    expect(siteFooter).not.toContain('legalLinks')
    expect(siteFooter).not.toContain('class="site-footer__locale"')
    expect(siteFooter).not.toContain('site-footer__locale-leading')
    expect(siteFooter).not.toContain('site-footer__locale-trailing')
    expect(siteFooter).not.toContain('aria-label="切换语言"')
    expect(siteFooter).not.toContain('primaryNavigation')
    expect(siteFooter).not.toContain('flattenColumnLinks')
    expect(siteFooter).not.toContain('Mail')
    expect(siteFooter).not.toContain('MapPin')
    expect(siteFooter).not.toContain('Phone')
    expect(enterpriseFlow).toContain('height: 100%')
    expect(enterpriseFlow).toContain('background: transparent')
    expect(enterpriseFlow).not.toContain('border: 1px solid var(--dt-color-line)')
  })
})
