import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { whyTrustTabs } from '../data/why'

const root = process.cwd()

function readComponent(relativePath: string) {
  return readFileSync(join(root, relativePath), 'utf8')
}

function listVueFiles(directory: string): string[] {
  return readdirSync(join(root, directory), { withFileTypes: true }).flatMap((entry) => {
    const path = `${directory}/${entry.name}`

    if (entry.isDirectory()) {
      return listVueFiles(path)
    }

    return entry.name.endsWith('.vue') ? [path] : []
  })
}

describe('visual implementation contract', () => {
  it('uses existing visual assets for the first viewport and solution cards', () => {
    const page = readComponent('pages/index.vue')
    const hero = readComponent('components/home/HomeHero.vue')
    expect(hero).not.toContain('HeroTresBackground')
    expect(hero).not.toContain('TresCanvas')
    expect(page).toContain('class="home-hero-deliverables__video"')
    expect(page).toContain('花瓣素材_+暖蓝光泄漏背景可循环')

    for (const asset of [
      'public/images/home/solutions/industrial.K00G2HaS.png',
      'public/images/home/solutions/smart-env.CWc2pooP.png',
      'public/images/home/solutions/smart-energy.DHKY-NE1.png',
      'public/images/home/solutions/smart-Water.DHKY-NE1.png',
      'public/images/home/solutions/data-center-ai.CDu93Miw.png',
      'public/images/home/solutions/data.DHKY-NE1.png',
    ]) {
      expect(existsSync(join(root, asset))).toBe(true)
    }
  })

  it('keeps component styles in SCSS, avoids inline style attributes, and caps component size', () => {
    const vueFiles = [...listVueFiles('components'), ...listVueFiles('pages')]

    for (const file of vueFiles) {
      const source = readComponent(file)
      const sourceWithoutRequiredNavWrapper = source.replace(' style="position:relative;"', '')
      const lineCount = source.split(/\r?\n/).length

      if (file.startsWith('components/') && source.includes('<style')) {
        expect(source).toContain('<style scoped lang="scss">')
      }

      expect(lineCount, `${file} exceeds 300 lines`).toBeLessThanOrEqual(300)
      expect(sourceWithoutRequiredNavWrapper).not.toMatch(/\sstyle=/)
    }
  })

  it('includes responsive navigation and mobile product fallback', () => {
    expect(readComponent('components/navigation/SiteHeaderMobileNav.vue')).toContain('mobile-navigation')
    expect(readComponent('components/home/HomeProductSystemMobileFlow.vue')).toContain('product-system__mobile-flow')
  })

  it('keeps the DGP product page aligned with its requirement document', () => {
    const page = readComponent('pages/products/data-governance.vue')
    const pageHero = readComponent('components/common/PageHero.vue')
    const hero = readComponent('components/product/dgp/DgpHero.vue')
    const heroVisual = readComponent('components/product/dgp/DgpHeroVisual.vue')
    const featureGrid = readComponent('components/common/ProductFeatureGridSection.vue')
    const architecture = readComponent('components/product/dgp/DgpArchitecture.vue')
    const systemCards = readComponent('components/common/SystemCards.vue')
    const evolution = readComponent('components/product/dgp/DgpEvolutionSection.vue')
    const useCases = readComponent('components/product/dgp/DgpUseCasesSection.vue')
    const data = readComponent('data/dgp.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('DgpHero')
    expect(page).toContain('ProductFeatureGridSection')
    expect(page).toContain('DgpArchitecture')
    expect(page).toContain('DgpEvolutionSection')
    expect(page).toContain('DgpUseCasesSection')
    expect(page).toContain('CtaSection')
    expect(page).toContain('为什么选择数曜·治理数据平台')
    expect(page).toContain('开启企业数据治理新征程')
    expect(page).toContain('title-id="dgp-cta-title"')
    expect(page).toContain('nowrap-subtitle')
    expect(page).not.toContain('top-padding')

    expect(hero).toContain('PageHero')
    expect(hero).toContain('import { Database }')
    expect(hero).toContain('badge="数曜·数据治理平台"')
    expect(hero).toContain('title-line="可用、可管、可信"')
    expect(hero).toContain('title-gradient="企业数据底座"')
    expect(hero).toContain('visual-label="SHUYAODGP_HORE_WEBM"')
    expect(hero).toContain('DgpHeroVisual')
    expect(hero).not.toContain('visual-size="large"')
    expect(pageHero).toContain("visualSize: 'default'")
    expect(pageHero).toContain("'max-w-lg self-center'")
    expect(pageHero).toContain("'max-w-[820px] self-stretch'")

    expect(heroVisual).toContain('ban-shape1.png?url')
    expect(heroVisual).toContain('ban-shape2.png?url')
    expect(heroVisual).toContain('ban-shape3.png?url')
    expect(heroVisual).toContain('ruizhi1.png?url')
    expect(heroVisual).toContain('<animateMotion')
    expect(heroVisual).toContain('motion-safe:animate-pulse')
    expect(heroVisual).not.toContain('esenruizhi.com')

    expect(featureGrid).toContain('SectionHeading')
    expect(featureGrid).toContain('class="relative bg-dt-bg pb-32 lg:pb-44"')
    expect(featureGrid).not.toContain('pt-24')
    expect(featureGrid).toContain('md:grid-cols-2 lg:grid-cols-4')
    expect(featureGrid).toContain(':title-id="titleId"')
    expect(featureGrid).toContain('auto-rows-fr items-stretch')
    expect(featureGrid).toContain('rounded-xl bg-gradient-to-br from-primary/20 to-primary/5')
    expect(featureGrid).not.toContain('mb-6')
    expect(featureGrid).toContain('class="size-5"')
    expect(featureGrid).toContain('class="relative mt-4 text-[15px] font-semibold leading-snug text-highlighted"')
    expect(featureGrid).toContain('class="relative mt-2 flex-1 text-sm leading-relaxed text-muted"')
    expect(featureGrid).not.toContain('text-base leading-relaxed')
    expect(featureGrid).not.toContain('min-h-[')
    expect(featureGrid).not.toContain('<style')

    expect(architecture).toContain('ProductSystemSection')
    expect(architecture).toContain('ProductSystemFlowFrame')
    expect(architecture).toContain('产品架构图占位符')
    expect(architecture).toContain('content-flush')
    expect(architecture).not.toContain(':heading-wide="false"')
    expect(architecture).not.toContain(':nowrap-subtitle="false"')
    expect(architecture).toContain('SystemCards')
    expect(architecture).not.toContain('EnterpriseFlow')

    expect(systemCards).toContain('mt-10 grid auto-rows-fr items-stretch gap-4 md:grid-cols-3 lg:mt-12')
    expect(systemCards).toContain('rounded-2xl border border-dt-line')
    expect(systemCards).toContain('hover:border-dt-primary/40')
    expect(systemCards).not.toContain('min-h-[')
    expect(systemCards).not.toContain('<style')

    expect(evolution).toContain('企业数据治理体系的演进')
    expect(evolution).toContain('class="container pb-32 lg:pb-44"')
    expect(evolution).toContain('mb-12 flex flex-col items-center gap-2 text-center lg:mb-16')
    expect(evolution).toContain('text-sm font-semibold uppercase tracking-wide text-primary')
    expect(evolution).toContain('text-4xl font-bold leading-[1.2] tracking-tight text-highlighted')
    expect(evolution).toContain('lg:whitespace-nowrap')
    expect(evolution).toContain('rounded-full border border-primary/20 bg-primary/5 px-2.5 py-1 text-[13px] font-semibold text-primary/80')
    expect(evolution).toContain('lg:grid-cols-2 lg:gap-12')
    expect(evolution).toContain('图片占位符')
    expect(evolution).not.toContain('border border-dt-line bg-dt-bg-soft/40')
    expect(evolution).not.toContain('SectionHeading')
    expect(evolution).not.toContain('<style')

    expect(useCases).toContain('class="pb-32 lg:pb-44"')
    expect(useCases).toContain('text-center text-4xl font-bold leading-[1.2] tracking-tight text-highlighted')
    expect(useCases).toContain('text-center text-base text-default')
    expect(useCases).toContain('lg:whitespace-nowrap')
    expect(useCases).toContain('role="tablist"')
    expect(useCases).toContain('data-slot="root"')
    expect(useCases).toContain('data-slot="list"')
    expect(useCases).toContain('data-slot="trigger"')
    expect(useCases).toContain('data-slot="indicator"')
    expect(useCases).toContain('data-slot="label"')
    expect(useCases).toContain('px-5 py-4 text-base font-medium')
    expect(useCases).toContain('border-b border-dt-line')
    expect(useCases).toContain('role="tabpanel"')
    expect(useCases).toContain('BaseButton')
    expect(useCases).toContain('了解更多')
    expect(useCases).not.toContain('class="dt-tab"')
    expect(useCases).not.toContain('SectionHeading')
    expect(useCases).not.toContain('!pb-0')
    expect(useCases).not.toContain('<style')

    for (const text of [
      '让数据快速可用',
      '数据接入',
      '数据集成',
      '政务数据治理',
      '物联数据汇聚与治理',
    ]) {
      expect(data).toContain(text)
    }
  })

  it('keeps the Why DeepTrols page on the shared HOME baseline', () => {
    const page = readComponent('pages/why-deeptrols.vue')
    const pageHero = readComponent('components/common/PageHero.vue')
    const heroLogoStrip = readComponent('components/common/HeroLogoStrip.vue')
    const trustTabsSection = readComponent('components/common/TrustTabsSection.vue')
    const serviceShowcaseSection = readComponent('components/common/ServiceShowcaseSection.vue')
    const engineLinksSection = readComponent('components/common/EngineLinksSection.vue')
    const hero = readComponent('components/why/WhyHero.vue')
    const heroLogos = readComponent('components/why/WhyHeroLogos.vue')
    const tabs = readComponent('components/why/WhyTrustTabs.vue')
    const service = readComponent('components/why/WhyServiceReset.vue')
    const engine = readComponent('components/why/WhyEngine.vue')
    const data = readComponent('data/why.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('WhyHero')
    expect(page).toContain('WhyHeroLogos')
    expect(page).toContain('WhyTrustTabs')
    expect(page).toContain('WhyServiceReset')
    expect(page).toContain('WhyEngine')
    expect(page).toContain('CtaSection')
    expect(page).toContain('whyCtaActions')
    expect(hero).toContain('PageHero')
    expect(hero).toContain('import { Sparkles }')
    expect(hero).toContain('badge="为什么选择 DeepTrols"')
    expect(hero).toContain('title-id="why-hero-title"')
    expect(hero).toContain('title-line="数据、知识、智能统一"')
    expect(hero).toContain('title-gradient="企业级AI应用服务商"')
    expect(hero).toContain('visual-size="large"')
    expect(hero).not.toContain('HomeCustomerLogos')
    expect(hero).not.toContain('why-hero__logos')
    expect(heroLogos).toContain('HeroLogoStrip')
    expect(heroLogos).toContain('HomeCustomerLogos')
    expect(hero).toContain('flush-bottom')
    expect(heroLogoStrip).toContain('class="container"')
    expect(heroLogoStrip).toContain('class="hero-logo-strip__inner mt-24 border-t border-dt-line pt-12 lg:mt-28"')
    expect(heroLogoStrip).toContain('padding-bottom: 96px')
    expect(heroLogoStrip).toContain('padding-bottom: 128px')
    expect(pageHero).toContain('class="page-hero relative overflow-hidden bg-dt-bg"')
    expect(pageHero).toContain('container page-hero__body relative pt-24 lg:pt-32')
    expect(pageHero).toContain("flushBottom ? 'pb-0 lg:pb-0' : 'pb-24 lg:pb-32'")
    expect(pageHero).toContain('w-full max-w-2xl text-center lg:text-left')
    expect(pageHero).toContain('page-hero__actions flex flex-wrap items-center justify-center gap-4 lg:justify-start')
    expect(pageHero).not.toContain('padding: 144px')
    expect(pageHero).not.toContain('padding: 144px 0 96px')
    expect(pageHero).not.toContain('padding-bottom: 112px')
    expect(pageHero).toContain('font-size: 36px')
    expect(pageHero).toContain('font-size: 48px')
    expect(pageHero).toContain('font-size: 60px')
    expect(pageHero).toContain('line-height: 1.1')
    expect(pageHero).toContain('margin: 0 auto 32px')
    expect(hero).toContain('立即咨询')
    expect(hero).toContain('关于我们')
    expect(pageHero).toContain('BaseButton')
    expect(hero).toContain('robot.webm?url')
    expect(hero).toContain('<video')
    expect(hero).toContain('autoplay')
    expect(hero).toContain('loop')
    expect(hero).toContain('muted')
    expect(hero).toContain('playsinline')
    expect(hero).not.toContain('Agentic solution V1.gif')
    expect(hero).not.toContain('new URL(')
    expect(pageHero).toContain('background-size: 72px 72px')
    expect(hero).toContain('mix-blend-screen')
    expect(hero).toContain('[mask-image:radial-gradient(76%_72%_at_50%_48%')
    expect(pageHero).toContain('max-w-[820px]')
    expect(pageHero).toContain('self-stretch')
    expect(hero).toContain('lg:h-full')
    expect(hero).toContain('h-[132%]')
    expect(hero).toContain('w-[132%]')
    expect(hero).toContain('!max-w-none')
    expect(hero).toContain('top-[46%]')
    expect(hero).toContain('-translate-x-1/2')
    expect(hero).not.toContain('&::after')
    expect(hero).not.toContain('linear-gradient(180deg, var(--dt-color-bg) 0%')
    expect(hero).not.toContain('linear-gradient(90deg, var(--dt-color-bg) 0%')
    expect(pageHero).toContain('lg:grid-cols-[minmax(0,0.88fr)_minmax(520px,1fr)]')
    expect(hero).not.toContain('video {')
    expect(hero).not.toContain('box-shadow: 0 24px 60px')
    expect(tabs).toContain('TrustTabsSection')
    expect(tabs).toContain('为什么DeepTrols值得信赖')
    expect(trustTabsSection).toContain('dt-section relative pb-32 lg:pb-44')
    expect(trustTabsSection).toContain('role="tablist"')
    expect(trustTabsSection).toContain('role="tab"')
    expect(trustTabsSection).toContain('role="tabpanel"')
    expect(trustTabsSection).toContain('mb-12 text-center lg:mb-16')
    expect(trustTabsSection).toContain('dt-segmented-tabs')
    expect(trustTabsSection).toContain('class="dt-segmented-tab"')
    expect(trustTabsSection).toContain('grid gap-5 md:grid-cols-2 lg:gap-6')
    expect(trustTabsSection).toContain('dt-product-card !p-7 lg:!p-8')
    expect(trustTabsSection).not.toContain('min-h-[280px]')
    expect(trustTabsSection).toContain('dt-icon-box !size-12 !rounded-xl')
    expect(trustTabsSection).toContain('font-size: 24px')
    expect(trustTabsSection).toContain('font-size: 18px')
    expect(trustTabsSection).not.toContain('dt-tab-list')
    expect(trustTabsSection).not.toContain('class="dt-tab"')
    expect(trustTabsSection).not.toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(serviceShowcaseSection).toContain('dt-section relative pb-32 lg:pb-44')
    expect(engineLinksSection).toContain('dt-section relative pb-32 lg:pb-44')
    expect(service).toContain('业务价值可衡量，AI成果可持续')
    expect(service).toContain('ServiceShowcaseSection')
    expect(service).toContain('fangangaishu@2x.png?url')
    expect(service).not.toContain('new URL(')
    expect(serviceShowcaseSection).toContain('SectionHeading')
    expect(serviceShowcaseSection).toContain('border-radius: var(--dt-radius-lg)')
    expect(serviceShowcaseSection).not.toContain('border-radius: 24px')
    expect(engine).toContain('重塑引擎')
    expect(engine).toContain('whyEngineLinks')
    expect(engine).toContain('EngineLinksSection')
    expect(engineLinksSection).toContain('SectionHeading')
    expect(engineLinksSection).toContain('border-radius: var(--dt-radius-lg)')
    expect(engineLinksSection).toContain('border-radius: var(--dt-radius-md)')
    expect(engineLinksSection).not.toContain('border-radius: 24px')
    expect(data).toContain("label: '面向技术层'")
    expect(data).toContain("label: '面向业务层'")
    expect(data).toContain("label: '面向服务层'")
    expect(data).toContain("label: '面向长期价值'")
    expect(whyTrustTabs).toHaveLength(4)
    expect(whyTrustTabs.every((tab) => tab.features.length === 4)).toBe(true)
    expect(data).toContain('DeepTrolsOPS企业AI引擎')
    expect(data).toContain('FDE企业AI服务指南')
    expect(existsSync(join(root, 'doc/product/PAGE_REQUIREMENTS/WhyDeepTrols/imgs/robot.webm'))).toBe(true)
    expect(existsSync(join(root, 'doc/product/PAGE_REQUIREMENTS/WhyDeepTrols/imgs/fangangaishu@2x.png'))).toBe(true)
  })

  it('keeps EMQX-inspired homepage rhythm contracts', () => {
    const tailwind = readComponent('assets/css/tailwind.css')
    const tokens = readComponent('assets/scss/main.scss')
    const page = readComponent('pages/index.vue')
    const header = readComponent('components/navigation/SiteHeader.vue')
    const headerDesktopNav = readComponent('components/navigation/SiteHeaderDesktopNav.vue')
    const headerActions = readComponent('components/navigation/SiteHeaderActions.vue')
    const headerMobileNav = readComponent('components/navigation/SiteHeaderMobileNav.vue')
    const headerMenuButton = readComponent('components/navigation/SiteHeaderMenuButton.vue')
    const baseButton = readComponent('components/common/BaseButton.vue')
    const sectionHeading = readComponent('components/common/SectionHeading.vue')
    const productSystemSection = readComponent('components/common/ProductSystemSection.vue')
    const productSystemFlowFrame = readComponent('components/common/ProductSystemFlowFrame.vue')
    const productSystemCards = readComponent('components/common/ProductSystemCards.vue')
    const ctaSection = readComponent('components/common/CtaSection.vue')
    const hero = readComponent('components/home/HomeHero.vue')
    const logos = readComponent('components/home/HomeCustomerLogos.vue')
    const deliverables = readComponent('components/home/HomeDeliverables.vue')
    const productSystem = readComponent('components/home/HomeProductSystem.vue')
    const homeProductSystemFlow = readComponent('components/home/HomeProductSystemFlow.vue')
    const homeProductSystemMobileFlow = readComponent('components/home/HomeProductSystemMobileFlow.vue')
    const homeSolutions = readComponent('components/home/HomeSolutions.vue')
    const homeEcosystem = readComponent('components/home/HomeEcosystem.vue')
    const ecosystemVisual = readComponent('components/home/HomeEcosystemVisual.vue')
    const ecosystemTokenVisual = readComponent('components/home/ecosystem-visuals/EcosystemTokenVisual.vue')
    const ecosystemAgentVisual = readComponent('components/home/ecosystem-visuals/EcosystemAgentVisual.vue')
    const ecosystemInfraVisual = readComponent('components/home/ecosystem-visuals/EcosystemInfraVisual.vue')
    const ecosystemReportVisual = readComponent('components/home/ecosystem-visuals/EcosystemReportVisual.vue')
    const ecosystemVisualData = readComponent('data/ecosystemVisual.ts')
    const homeCases = readComponent('components/home/HomeCases.vue')
    const homeCaseSlide = readComponent('components/home/HomeCaseSlide.vue')
    const homeCasesControls = readComponent('components/home/HomeCasesControls.vue')
    const homeInsights = readComponent('components/home/HomeInsights.vue')
    const homeCta = readComponent('components/home/HomeCta.vue')
    const siteFooter = readComponent('components/layout/SiteFooter.vue')
    const footerSubscribe = readComponent('components/layout/FooterSubscribe.vue')
    const footerMain = readComponent('components/layout/FooterMain.vue')
    const footerSocials = readComponent('components/layout/FooterSocials.vue')
    const footerBottom = readComponent('components/layout/FooterBottom.vue')
    const footerData = readComponent('data/footer.ts')
    const footerMainIndex = siteFooter.indexOf('<FooterMain')
    const footerSocialsIndex = siteFooter.indexOf('<FooterSocials')
    const footerBottomRuleIndex = siteFooter.indexOf('class="site-footer__rule site-footer__rule--bottom"')
    const footerSources = [siteFooter, footerSubscribe, footerMain, footerSocials, footerBottom, footerData].join('\n')
    const enterpriseFlow = readComponent('components/flow/EnterpriseFlow.client.vue')

    expect(sectionHeading).toContain('section-heading--nowrap-subtitle')
    expect(sectionHeading).toContain('max-width: none')
    expect(tailwind).toContain('@import "tailwindcss"')
    expect(tailwind).toContain('@theme inline')
    expect(tailwind).toContain('--color-dt-primary: var(--dt-color-primary)')
    expect(tokens).toContain('--dt-container: 80rem')
    expect(tokens).toContain('--dt-container-2xl: 96rem')
    expect(tokens).toContain('--dt-color-bg: #151515')
    expect(tokens).toContain('--dt-color-text-highlighted: #ffffff')
    expect(tokens).toContain('--dt-color-nav-text: #e5e5e5')
    expect(tokens).toContain('--dt-radius-lg: 16px')
    expect(tokens).toContain('@media (min-width: 1536px)')
    expect(tokens).toContain('--dt-gradient-spotlight')
    expect(tokens).toContain('.dt-button')
    expect(tokens).toContain('.dt-tab-list')
    expect(tokens).toContain('.dt-tab')
    expect(tokens).toContain('.dt-segmented-tabs')
    expect(tokens).toContain('.dt-segmented-tab')
    expect(tokens).toContain('.dt-product-card')
    expect(tokens).toContain('.dt-ecosystem-card')
    expect(tokens).toContain('.dt-icon-box')
    expect(tokens).toContain('border-radius: var(--dt-radius-md)')
    expect(tokens).toContain('border-radius: var(--dt-radius-lg)')
    expect(tokens).not.toContain('min-height: 280px')
    expect(tokens).toContain('.dt-card-tag')
    expect(tokens).toContain('.dt-cta-panel')
    expect(tokens).not.toContain('@apply')
    expect(baseButton).toContain('data-slot="base"')
    expect(baseButton).toContain('data-slot="label"')
    expect(baseButton).toContain('data-slot="trailingIcon"')
    expect(baseButton).toContain('dt-button')
    expect(sectionHeading).toContain('titleId')
    expect(sectionHeading).toContain('nowrapSubtitle')
    expect(sectionHeading).toContain('class="section-heading dt-section-heading"')

    expect(header).toContain('height: var(--dt-header-height)')
    expect(header).toContain('margin-bottom: calc(var(--dt-header-height) * -1)')
    expect(header).toContain('data-slot="root"')
    expect(header).toContain('data-slot="container"')
    expect(header).toContain('src="/logo-while.svg"')
    expect(header).toContain('width: 200px')
    expect(header).not.toContain('filter: brightness(0) invert(1)')
    expect(header).toContain('background: rgba(21, 21, 21, 0.95)')
    expect(header).toContain('0 10px 15px -3px rgba(0, 0, 0, 0.1)')
    expect(header).toContain('site-header__left')
    expect(header).toContain('flex: 1 1 0')
    expect(header).toContain('SiteHeaderDesktopNav')
    expect(header).toContain('SiteHeaderActions')
    expect(header).toContain('SiteHeaderMobileNav')
    expect(header).toContain('SiteHeaderMenuButton')
    expect(header).toContain('function handleNavMouseEnter')
    expect(header).toContain('function handleNavMouseLeave')
    expect(header).not.toContain('max-width: var(--dt-container)')
    expect(header).not.toContain('@media (max-width: 1279px)')
    expect(headerActions).toContain('site-header__github-icon')
    expect(headerActions).toContain('site-header__language-icon')
    expect(headerActions).toContain('site-header__github-icon size-5')
    expect(headerActions).toContain('site-header__language-icon size-5')
    expect(headerActions).toContain('site-header__text-link')
    expect(headerActions).toContain('登录OPS')
    expect(headerActions).toContain('font-size: 14px')
    expect(headerActions).not.toContain('GitFork')
    expect(headerActions).not.toContain('联系我们')
    expect(headerActions).not.toContain('免费咨询')
    expect(headerDesktopNav).toContain('<div style="position:relative;">')
    expect(headerDesktopNav).toContain('@mouseenter="$emit(\'enter\', item, index)"')
    expect(headerDesktopNav).toContain('@mouseleave="$emit(\'leave\', item)"')
    expect(headerDesktopNav).toContain(":class=\"{ 'direct-link': !hasMega(item) }\"")
    expect(headerDesktopNav).toContain('color: var(--dt-color-nav-text)')
    expect(headerDesktopNav).toContain('color: var(--dt-color-text-highlighted)')
    expect(headerDesktopNav).toContain('&.direct-link:hover')
    expect(headerDesktopNav).toContain('color: var(--dt-color-primary)')
    expect(headerDesktopNav).toContain('rgba(39, 30, 53, 0.5)')
    expect(headerDesktopNav).toContain('color-mix(in oklab, var(--dt-color-bg-elevated) 50%, transparent)')
    expect(headerDesktopNav).toContain('border-radius: var(--dt-ui-radius)')
    expect(headerMobileNav).toContain('mobile-navigation')
    expect(headerMenuButton).toContain('Menu')
    expect(headerMenuButton).toContain('X')
    expect(page).toContain('class="home-hero-deliverables"')
    expect(page).toContain('class="home-hero-deliverables__video"')
    expect(page).toContain('class="home-hero-deliverables__mask"')
    expect(page).toContain('rgba(21, 21, 21, 0.4)')
    expect(page).toContain('rgba(21, 21, 21, 0.95) 0%')
    expect(page).toContain('var(--dt-color-bg) 100%')
    expect(page).toContain('      </div>\n      <HomeProductSystem />')
    expect(hero).toContain('padding-top: 128px')
    expect(hero).toContain('font-size: 60px')
    expect(hero).toContain('background: transparent')
    expect(hero).not.toContain('home-hero__wash')
    expect(hero).not.toContain('ClientOnly')
    expect(logos).toContain('padding-top: 5.5rem')
    expect(logos).toContain('gap: 4rem')
    expect(deliverables).toContain('padding: clamp(3.5rem, 7vw, 6rem) 0 8rem')
    expect(deliverables).toContain('flex: 0 0 40%')
    expect(deliverables).toContain('min-height: 280px')
    expect(deliverables).toContain('padding: 48px')
    expect(deliverables).toContain('padding-right: 112px')
    expect(deliverables).toContain('linear-gradient(to right, #181524, #271e35)')
    expect(deliverables).toContain('aria-roledescription="轮播"')
    expect(deliverables).toContain('showPreviousDeliverable')
    expect(deliverables).toContain('showNextDeliverable')
    expect(deliverables).toContain('data-active-slide')
    expect(deliverables).toContain('flex: 0 0 100%')
    expect(deliverables).toContain('transform: translate3d(-100%, 0, 0)')
    expect(deliverables).toContain('transform: translate3d(-200%, 0, 0)')
    expect(deliverables).not.toContain('animation:')
    expect(deliverables).not.toContain('deliverablesCarousel')
    expect(deliverables).not.toContain('deliverablesMarquee')
    expect(deliverables).toContain('font-size: 20px')
    expect(deliverables).toContain('font-size: 24px')
    expect(deliverables).toContain('font-size: 14px')
    expect(deliverables).toContain('display: none')
    expect(deliverables).not.toContain('What We Deliver')

    expect(productSystem).toContain('eyebrow="DeepTrols OPS"')
    expect(productSystem).toContain('title="连接真实业务与人工智能"')
    expect(productSystem).toContain('以数据与知识底座桥接企业业务与人工智能。赋能 AI Agent，实现对真实业务的支撑。')
    expect(productSystem).toContain('ProductSystemSection')
    expect(productSystem).toContain('HomeProductSystemFlow')
    expect(productSystem).toContain('HomeProductSystemMobileFlow')
    expect(productSystem).toContain('ProductSystemCards')
    expect(homeProductSystemFlow).toContain('ProductSystemFlowFrame')
    expect(homeProductSystemFlow).toContain('shouldRenderFlow')
    expect(homeProductSystemFlow).toContain('<EnterpriseFlow v-if="shouldRenderFlow" />')
    expect(productSystemSection).toContain('nowrap-subtitle')
    expect(productSystemSection).toContain('.product-system--heading-wide :deep(.section-heading)')
    expect(productSystemSection).toContain('.product-system :deep(.section-heading__subtitle)')
    expect(productSystemSection).toContain('font-size: 20px')
    expect(productSystemSection).toContain('.product-system--heading-wide :deep(.section-heading__subtitle)')
    expect(productSystemSection).toContain('white-space: nowrap')
    expect(productSystemSection).toContain('product-system__content')
    expect(productSystemSection).not.toContain('role="img"')
    expect(productSystemSection).not.toContain('product-system__mobile-flow')
    expect(productSystemSection).not.toContain('v-for="card in cards"')
    expect(productSystemSection).not.toContain('flowFallbackText')
    expect(productSystemSection).not.toContain('EnterpriseFlow')
    expect(productSystem).toContain('label="DeepTrols OPS platform architecture"')
    expect(productSystemFlowFrame).toContain('role="img"')
    expect(productSystemFlowFrame).toContain('height: 560px')
    expect(productSystemFlowFrame).toContain('rgba(148, 163, 184, 0.12) 1px')
    expect(productSystemFlowFrame).toContain('background-size: 48px 48px')
    expect(homeProductSystemMobileFlow).toContain('product-system__mobile-flow')
    expect(homeProductSystemMobileFlow).toContain('inputs')
    expect(homeProductSystemMobileFlow).toContain('outputs')
    expect(productSystemCards).toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(productSystemCards).toContain('class="product-system__card dt-product-card"')
    expect(productSystemCards).toContain('class="product-system__card-accent dt-product-card__accent"')
    expect(productSystemCards).toContain('class="product-system__card-icon dt-icon-box"')
    expect(productSystemCards).toContain('product-system__card-accent')
    expect(productSystemCards).not.toContain('min-height')
    expect(productSystemCards).toContain('<h3>{{ card.name }}</h3>')
    expect(productSystemCards).not.toContain('{{ card.title }}')

    expect(homeSolutions).toContain('eyebrow="Use Cases"')
    expect(homeSolutions).toContain('title="驱动各行业智能提升"')
    expect(homeSolutions).toContain('覆盖智能制造、企业运营、AI基础设施等核心领域，帮助企业快速构建可持续演进的智能化能力')
    expect(homeSolutions).toContain('nowrap-subtitle')
    expect(homeSolutions).toContain('.solutions :deep(.section-heading__subtitle)')
    expect(homeSolutions).toContain('font-size: 20px')
    expect(homeSolutions).toContain('white-space: nowrap')
    expect(homeSolutions).toContain('role="tablist"')
    expect(homeSolutions).toContain('class="solutions__tabs dt-tab-list"')
    expect(homeSolutions).toContain('class="dt-tab"')
    expect(homeSolutions).toContain('role="region"')
    expect(homeSolutions).toContain('aria-roledescription="carousel"')
    expect(homeSolutions).toContain('data-orientation="horizontal"')
    expect(homeSolutions).toContain('data-slot="root"')
    expect(homeSolutions).toContain('data-slot="viewport"')
    expect(homeSolutions).toContain('data-slot="container"')
    expect(homeSolutions).toContain('role="group"')
    expect(homeSolutions).toContain('data-slot="item"')
    expect(homeSolutions).toContain('flex: 0 0 100%')
    expect(homeSolutions).toContain('transform: translate3d(-500%, 0, 0)')
    expect(homeSolutions).toContain('min-height: 420px')
    expect(homeSolutions).toContain('min-height: 520px')
    expect(homeSolutions).toContain('background: linear-gradient(to top, rgba(0, 0, 0, 0.95)')
    expect(homeSolutions).toContain('padding: 96px 24px 24px')
    expect(homeSolutions).toContain('font-size: 24px')
    expect(homeSolutions).toContain('class="group solutions__panel"')
    expect(homeSolutions).toContain('阅读案例')
    expect(homeSolutions).toContain('class="iconify iconify--lucide size-4 transition group-hover:translate-x-1"')
    expect(homeSolutions).toContain('line-height: 1.5')
    expect(homeSolutions).not.toContain('了解更多')
    expect(homeSolutions).toContain('查看所有应用场景')
    expect(homeSolutions).toContain('href="/solutions#use-cases"')
    expect(homeSolutions).toContain('BaseButton')
    expect(homeSolutions).not.toContain('查看所有解决方案')

    expect(homeEcosystem).toContain('eyebrow="ecosystem"')
    expect(homeEcosystem).toContain('title="连接企业 AI 全链路的开放生态"')
    expect(homeEcosystem).toContain('subtitle="连接算力、模型、社区与行业知识，构建开放 AI 生态"')
    expect(homeEcosystem).toContain('nowrap-subtitle')
    expect(homeEcosystem).toContain('.ecosystem :deep(.section-heading__subtitle)')
    expect(homeEcosystem).toContain('font-size: 20px')
    expect(homeEcosystem).toContain('white-space: nowrap')
    expect(homeEcosystem).toContain('HomeEcosystemVisual')
    expect(homeEcosystem).toContain('class="group ecosystem-card dt-ecosystem-card"')
    expect(homeEcosystem).toContain('class="ecosystem-card__tag dt-card-tag"')
    expect(homeEcosystem).toContain('border-radius: var(--dt-radius-md)')
    expect(homeEcosystem).toContain(':to="card.href"')
    expect(homeEcosystem).toContain('grid-template-columns: 1fr')
    expect(homeEcosystem).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(homeEcosystem).toContain('gap: 24px')
    expect(homeEcosystem).toContain('margin-top: 48px')
    expect(homeEcosystem).toContain('width: 48px')
    expect(homeEcosystem).toContain('height: 48px')
    expect(homeEcosystem).toContain('font-size: 20px')
    expect(homeEcosystem).toContain('max-width: 75%')
    expect(homeEcosystem).toContain('font-size: 16px')
    expect(homeEcosystem).toContain('width: 32px')
    expect(homeEcosystem).toContain('height: 32px')
    expect(homeEcosystem).toContain('bottom: 32px')
    expect(homeEcosystem).toContain('opacity: 0')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__cloud-grid)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__base-line)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__flow)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__led)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__device-label)')
    expect(homeEcosystem).not.toContain('title="Ecosystem"')
    expect(ecosystemVisual).toContain("type EcosystemVisualVariant = 'token' | 'agent' | 'infra' | 'report'")
    expect(ecosystemVisual).toContain('ecosystem-visual--${variant}')
    expect(ecosystemVisual).toContain('visualComponents[variant]')
    expect(ecosystemVisual).toContain('EcosystemTokenVisual')
    expect(ecosystemVisual).toContain('EcosystemAgentVisual')
    expect(ecosystemVisual).toContain('EcosystemInfraVisual')
    expect(ecosystemVisual).toContain('EcosystemReportVisual')
    expect(ecosystemTokenVisual).toContain('cloudDots')
    expect(ecosystemTokenVisual).toContain('r="0.35"')
    expect(ecosystemTokenVisual).toContain('filter id="glow-map"')
    expect(ecosystemAgentVisual).toContain('filter id="edgeGlow"')
    expect(ecosystemInfraVisual).toContain('filter id="serverGlow"')
    expect(ecosystemReportVisual).toContain('filter id="bridgeGlow"')
    expect(ecosystemVisualData).toContain('x1: 105')
    expect(ecosystemVisualData).toContain('x2: 125')
    expect(ecosystemVisualData).toContain('x1: 120')
    expect(ecosystemVisualData).toContain('x2: 140')
    expect(ecosystemVisualData).toContain('x1: 80')
    expect(ecosystemVisualData).toContain('x2: 115')
    expect(ecosystemVisualData).toContain('transform: \'translate(115, 21)\'')
    expect(ecosystemVisualData).toContain('transform: \'translate(135, 45)\'')
    expect(ecosystemVisualData).toContain('transform: \'translate(105, 58)\'')
    expect(ecosystemReportVisual).toContain('论文')
    expect(ecosystemReportVisual).toContain('领域')
    expect(ecosystemVisual).toContain('top: -5px')
    expect(ecosystemVisual).toContain('right: -5%')
    expect(ecosystemVisual).toContain('top: -5%')
    expect(ecosystemVisual).toContain('height: 110%')
    expect(ecosystemVisual).toContain('width: 80%')
    expect(ecosystemVisual).toContain('width: 65%')
    expect(ecosystemAgentVisual).toContain('stroke-dasharray="1 2"')
    expect(ecosystemAgentVisual).toContain('stroke-dasharray="1 15"')
    expect(ecosystemVisual).toContain('animation-play-state: paused')
    expect(ecosystemVisual).toContain('stroke-dashoffset: 16')
    expect(ecosystemVisual).toContain('@keyframes ecosystemVisualFlow')
    expect(ecosystemVisual).toContain('@keyframes ecosystemVisualPulse')

    expect(homeCases).toContain('CUSTOMER STORIES')
    expect(homeCases).toContain('携手 DeepTrols 加速创新')
    expect(homeCases).toContain('助力客户加速创新、实现业务突破，同时显著降低成本。')
    expect(homeCases).toContain('SectionHeading')
    expect(homeCases).toContain('HomeCaseSlide')
    expect(homeCases).toContain('HomeCasesControls')
    expect(homeCases).toContain('title-id="cases-title"')
    expect(homeCases).toContain('nowrap-subtitle')
    expect(homeCases).toContain('max-width: 96rem')
    expect(homeCases).toContain('padding: 0 16px 128px')
    expect(homeCases).toContain('padding-bottom: 176px')
    expect(homeCases).toContain('font-size: 20px')
    expect(homeCases).toContain('white-space: nowrap')
    expect(homeCases).toContain('padding: 40px 0 0')
    expect(homeCases).toContain('cases__shell')
    expect(homeCases).toContain('overflow: hidden')
    expect(homeCases).toContain('border-radius: 24px')
    expect(homeCases).toContain('background: rgba(38, 38, 38, 0.4)')
    expect(homeCases).toContain('0 1px 2px rgba(0, 0, 0, 0.05)')
    expect(homeCases).toContain('cases__controls')
    expect(homeCasesControls).toContain('aria-label="Previous story"')
    expect(homeCasesControls).toContain('aria-label="Next story"')
    expect(homeCasesControls).toContain('dt-icon-button')
    expect(homeCases).toContain('role="tablist"')
    expect(homeCases).toContain('cases__logo-tabs')
    expect(homeCases).toContain('gap: 40px')
    expect(homeCases).toContain('gap: 56px')
    expect(homeCases).toContain('role="region"')
    expect(homeCases).toContain('aria-roledescription="carousel"')
    expect(homeCases).toContain('data-orientation="horizontal"')
    expect(homeCases).toContain('data-slot="root"')
    expect(homeCases).toContain('padding: 0')
    expect(homeCases).toContain('data-slot="viewport"')
    expect(homeCases).toContain('data-slot="container"')
    expect(homeCases).toContain('data-active-slide')
    expect(homeCases).toContain('transform: translate3d(-100%, 0, 0)')
    expect(homeCases).toContain('transform: translate3d(-200%, 0, 0)')
    expect(homeCaseSlide).toContain('min-height: 520px')
    expect(homeCaseSlide).toContain('<div class="cases__visual-overlay"></div>')
    expect(homeCaseSlide).not.toContain('<span></span>')
    expect(homeCaseSlide).not.toContain('span:nth-child')
    expect(homeCaseSlide).toContain('class="cases__button"')
    expect(homeCaseSlide).toContain(':href="story.href"')
    expect(homeCaseSlide).toContain('margin-top: auto')
    expect(homeCaseSlide).toContain('padding-top: 32px')
    expect(homeCaseSlide).toContain('BaseButton')
    expect(homeCaseSlide).toContain('variant="secondary"')
    expect(homeCaseSlide).toContain('阅读案例')
    expect(homeCases).toContain('class="cases__all-action"')
    expect(homeCases).toContain('href="/cases"')
    expect(homeCases).toContain('查看所有案例')
    expect(homeCases).toContain('margin-top: 32px')
    expect(homeCaseSlide).not.toContain('type="button"\n                          data-slot="base"')
    expect(homeCaseSlide).not.toContain('class="cases__read-link"')
    expect(homeCases).not.toContain('function readStory')
    expect(homeCases).not.toContain('navigateTo')
    expect(homeCaseSlide).not.toContain('阅读案例研究')
    expect(homeCaseSlide).not.toContain('class="cases__link"')
    expect(homeCaseSlide).toMatch(/h3 \{[\s\S]*font-size: 20px;[\s\S]*font-weight: 600;[\s\S]*line-height: 1\.25;/)
    expect(homeCaseSlide).toMatch(/\.cases__content p \{[\s\S]*font-size: 18px;[\s\S]*line-height: 1\.625;/)
    expect(homeCaseSlide).toContain('h3 {\n    font-size: 24px;\n  }')
    expect(homeCaseSlide).toContain('.cases__content p {\n    font-size: 20px;\n  }')
    expect(homeCases).not.toContain('title="CUSTOMER STORIES"')

    expect(homeInsights).toContain('SectionHeading')
    expect(homeInsights).toContain('eyebrow="Resources"')
    expect(homeInsights).toContain('title="创新、洞察与新闻"')
    expect(homeInsights).toContain('title-id="insights-title"')
    expect(homeInsights).toContain('class="insights__layout"')
    expect(homeInsights).toContain('grid-template-columns: 1fr')
    expect(homeInsights).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(homeInsights).toContain('gap: 24px')
    expect(homeInsights).toContain('margin-bottom: 48px')
    expect(homeInsights).toContain('font-size: 16px')
    expect(homeInsights).toContain('class="group insights__featured"')
    expect(homeInsights).toContain('class="group insights__item"')
    expect(homeInsights).toContain('aspect-ratio: 2 / 1')
    expect(homeInsights).toContain('aspect-ratio: 400 / 180')
    expect(homeInsights).toContain('aspect-ratio: auto')
    expect(homeInsights).toContain('border-radius: var(--dt-ui-radius)')
    expect(homeInsights).toContain('border-color: var(--dt-color-line-strong)')
    expect(homeInsights).toContain('transform: scale(1.05)')
    expect(homeInsights).toContain('transition: transform 500ms ease')
    expect(homeInsights).toContain('position: absolute')
    expect(homeInsights).toContain('inset: 0')
    expect(homeInsights).toContain('object-fit: cover')
    expect(homeInsights).toContain('-webkit-line-clamp: 3')
    expect(homeInsights).toContain('-webkit-line-clamp: 2')
    expect(homeInsights).toContain('-webkit-line-clamp: 1')
    expect(homeInsights).toContain('class="insights__all-link insights__all-link--desktop"')
    expect(homeInsights).toContain('class="insights__mobile-action"')
    expect(homeInsights).toContain('BaseButton')
    expect(homeInsights).toContain('查看全部资源')
    expect(homeInsights).not.toContain('insights__topline')
    expect(homeInsights).not.toContain('transform: translateY')

    expect(homeCta).toContain('CtaSection')
    expect(ctaSection).toContain('class="cta-section"')
    expect(ctaSection).toContain('class="container"')
    expect(ctaSection).toContain('class="cta-section__panel dt-cta-panel"')
    expect(homeCta).toContain('构建企业自身的AI能力')
    expect(homeCta).toContain('让数据成为资产，让知识驱动决策，让AI创造价值')
    expect(ctaSection).toContain('padding-bottom: 128px')
    expect(ctaSection).toContain('padding-bottom: 176px')
    expect(ctaSection).toContain('font-size: 36px')
    expect(ctaSection).toContain('font-size: 48px')
    expect(ctaSection).toContain('font-size: 20px')
    expect(ctaSection).toContain('class="cta-section__actions"')
    expect(ctaSection).toContain('gap: 24px')
    expect(ctaSection).toContain('BaseButton')
    expect(homeCta).toContain("href: '/contact'")
    expect(homeCta).toContain("href: '/try'")
    expect(homeCta).toContain('咨询合作')
    expect(homeCta).toContain('申请试用')
    expect(homeCta).not.toContain('Start With DeepTrols')
    expect(homeCta).not.toContain('构建属于企业自己的 AI 能力')

    expect(siteFooter).toContain('class="site-footer"')
    expect(siteFooter).toContain('padding-top: 48px')
    expect(siteFooter).toContain('background: var(--dt-color-bg-soft)')
    expect(siteFooter).toContain('FooterSubscribe')
    expect(siteFooter).toContain('FooterMain')
    expect(siteFooter).toContain('FooterSocials')
    expect(siteFooter).toContain('FooterBottom')
    expect(footerSubscribe).toContain('订阅 DeepTrols 最新资讯')
    expect(footerSubscribe).toContain('data-slot="base"')
    expect(footerSubscribe).toContain('dt-button dt-button--primary dt-button--lg')
    expect(footerMain).toContain('class="site-footer__main"')
    expect(footerMain).toContain('class="site-footer__identity"')
    expect(footerMain).toContain('src="/logo-while.svg"')
    expect(footerMain).toContain('width: 240px')
    expect(footerMainIndex).toBeGreaterThan(-1)
    expect(footerSocialsIndex).toBeGreaterThan(footerMainIndex)
    expect(footerSocialsIndex).toBeLessThan(footerBottomRuleIndex)
    expect(footerSocials).toContain('class="site-footer__socials"')
    expect(footerSocials).toContain('aria-label="社交媒体"')
    expect(footerSocials).toContain('class="site-footer__social-link"')
    expect(footerData).toContain("label: 'GitHub'")
    expect(footerData).toContain("label: 'X'")
    expect(footerData).toContain("label: '哔哩哔哩'")
    expect(footerData).toContain("label: 'LinkedIn'")
    expect(footerData).toContain("label: '微信公众号'")
    expect(footerSocials).toContain('margin-top: 40px')
    expect(footerSocials).toContain('gap: 24px')
    expect(footerSocials).toContain('iconify iconify--simple-icons w-full h-6')
    expect(footerMain).toContain('class="site-footer__columns"')
    expect(footerMain).toContain('grid-template-columns: repeat(5, minmax(0, 1fr))')
    expect(footerMain).toContain('gap: 32px')
    expect(footerMain).toContain('font-size: 14px')
    expect(footerMain).toContain('line-height: 20px')
    expect(footerMain).toContain('gap: 10px')
    expect(footerMain).toContain('margin: 16px 0')
    expect(footerMain).toContain('class="site-footer__group-rule"')
    expect(footerData).toContain('产品')
    expect(footerData).toContain('数曜·数据治理平台')
    expect(footerData).toContain('数曜·数据标签平台')
    expect(footerData).toContain('数曜·数据开发平台')
    expect(footerData).toContain('数曜·数据资产管理平台')
    expect(footerData).toContain('博曜·企业级知识管理平台')
    expect(footerData).toContain('探曜·AI物联感知平台')
    expect(footerData).toContain('Device Agent')
    expect(footerData).toContain('API安全管控平台')
    expect(footerData).toContain('API安全审计系统')
    expect(footerData).toContain('业务威胁感知系统')
    expect(footerData).toContain('使用场景')
    expect(footerData).toContain('智能制造')
    expect(footerData).toContain('智能环保')
    expect(footerData).toContain('智能水利')
    expect(footerData).toContain('智慧能源')
    expect(footerData).toContain('数据治理')
    expect(footerData).toContain('企业AI应用')
    expect(footerData).toContain('智慧城市')
    expect(footerData).toContain('智慧医疗')
    expect(footerData).toContain('行业')
    expect(footerData).toContain('制造业')
    expect(footerData).toContain('能源')
    expect(footerData).toContain('交通运输与物流')
    expect(footerData).toContain('政府/公共事业')
    expect(footerData).toContain('教育')
    expect(footerData).toContain('水利/水务')
    expect(footerData).toContain('金融服务')
    expect(footerData).toContain('城市治理')
    expect(footerData).toContain('零售')
    expect(footerData).toContain('服务')
    expect(footerData).toContain('Token Hub')
    expect(footerData).toContain('白皮书&报告')
    expect(footerData).toContain('产品文档')
    expect(footerData).toContain('算力与基础设施')
    expect(footerData).toContain('智能体社区')
    expect(footerMain).toContain('translate-inline-px translate-y-[-2px] scale-inline-100 transform')
    expect(footerMain).toContain('stroke-width="1.3"')
    expect(footerData).toContain('公司')
    expect(footerData).toContain('关于我们')
    expect(footerData).toContain('新闻动态')
    expect(footerData).toContain('合作伙伴')
    expect(footerData).toContain('加入我们')
    expect(footerData).toContain('联系我们')
    expect(footerData).toContain('品牌资源')
    expect(footerData).toContain('服务案例')
    expect(footerData).toContain('投资计划')
    expect(footerBottom).toContain('class="site-footer__filings"')
    expect(footerBottom).toContain('京公网安备100861001010000号')
    expect(footerBottom).toContain('京ICP备20018888号-4')
    expect(footerBottom).toContain('https://beian.miit.gov.cn/')
    expect(footerBottom).toContain('class="site-footer__copyright"')
    expect(footerBottom).toContain('@ 武汉深度数智科技有限公司 2026 版权所有')
    expect(footerBottom).toContain('justify-content: space-between')
    expect(footerSources).not.toContain('© 2026 DeepTrols. All rights reserved')
    expect(footerSources).not.toContain('legalLinks')
    expect(footerSources).not.toContain('class="site-footer__locale"')
    expect(footerSources).not.toContain('site-footer__locale-leading')
    expect(footerSources).not.toContain('site-footer__locale-trailing')
    expect(footerSources).not.toContain('aria-label="切换语言"')
    expect(footerSources).not.toContain('primaryNavigation')
    expect(footerSources).not.toContain('flattenColumnLinks')
    expect(footerSources).not.toContain('Mail')
    expect(footerSources).not.toContain('MapPin')
    expect(footerSources).not.toContain('Phone')
    expect(enterpriseFlow).toContain('height: 100%')
    expect(enterpriseFlow).toContain('background: transparent')
    expect(enterpriseFlow).not.toContain('border: 1px solid var(--dt-color-line)')
  })
})
