import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerDatacenterVisualContracts() {
  it('builds the datacenter solution page from the product requirement layout', () => {
    const page = readComponent('pages/solutions/compute.vue')
    const hero = readComponent('components/solution/datacenter/DatacenterHero.vue')
    const scenarios = readComponent('components/solution/datacenter/DatacenterScenariosSection.vue')
    const data = readComponent('data/solutions/datacenter.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('<DatacenterHero />')
    expect(page).toContain('class="pt-32"')
    expect(page).toContain('eyebrow="行业痛点"')
    expect(page).toContain('title="算力规模持续增长，传统分系统运营难以实现全局最优"')
    expect(page).toContain('title-id="datacenter-pain-title"')
    expect(page).toContain(':items="datacenterPains"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('header-width="wide"')
    expect(page).toContain('<SectionShell title-id="datacenter-solution-title" spacing="compact">')
    expect(page).toContain('eyebrow="解决方案"')
    expect(page).toContain('title="构建算力与能源协同优化的统一运营体系"')
    expect(page).toContain('<ProductSystemFlowFrame :label="datacenterSolutionLabel" />')
    expect(page).toContain('eyebrow="核心能力"')
    expect(page).toContain('title="从分系统优化走向算电协同全局优化"')
    expect(page).toContain('title-id="datacenter-capability-title"')
    expect(page).toContain('subtitle=""')
    expect(page).toContain(':items="datacenterCapabilities"')
    expect(page).toContain('columns="four"')
    expect(page).toContain('<SectionShell title-id="datacenter-loop-title" spacing="compact">')
    expect(page).toContain('eyebrow="运营闭环"')
    expect(page).toContain('title="预测、优化、执行、反馈持续闭环"')
    expect(page).toContain('<ProductSystemFlowFrame :label="datacenterLoopLabel" />')
    expect(page).toContain('DatacenterScenariosSection')
    expect(page).toContain('<CtaSection title-id="datacenter-cta-title" />')
    expect(page).not.toContain('<style')
    expect(page).not.toContain('style=')

    expect(hero).toContain('h-[586px]')
    expect(hero).toContain(':src="datacenterHero.image"')
    expect(hero).toContain(':alt="datacenterHero.imageAlt"')
    expect(hero).toContain('bg-[linear-gradient(90deg,rgba(0,0,0,0.55)_0,rgba(0,0,0,0.26)_38%,rgba(0,0,0,0)_62%)]')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)]')
    expect(hero).toContain('max-md:whitespace-normal')
    expect(hero).toContain('max-md:top-[290px]')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('免费获取专属方案')
    expect(hero).toContain('to="/contact"')
    expect(hero).not.toContain('<style')
    expect(hero).not.toContain('style=')

    expect(scenarios).toContain('title="典型场景"')
    expect(scenarios).toContain('align="center"')
    expect(scenarios).toContain('grid gap-6 md:grid-cols-2 xl:grid-cols-4')
    expect(scenarios).toContain('grid-rows-[auto_auto_1fr]')
    expect(scenarios).toContain('content-start gap-4 rounded-lg border border-default bg-muted p-8')
    expect(scenarios).toContain('text-lg font-semibold text-highlighted')
    expect(scenarios).toContain('text-base font-normal text-default')
    expect(scenarios).not.toContain('NuxtLink')
    expect(scenarios).not.toContain('ArrowUpRight')
    expect(scenarios).not.toContain('before:')
    expect(scenarios).not.toContain('<style')
    expect(scenarios).not.toContain('style=')

    expect(data).toContain("image: '/images/solutions/datacenter-hero.webp'")
    expect(data).toContain("title: '统筹算力、电力、冷却与储能，降低综合成本'")
    expect(data).toContain("title: 'AI 数据中心'")
    expect(data).toContain('算电协同运营能力图')
    expect(data).toContain('算电协同运营闭环能力图')
    expect(existsSync(join(root, 'public/images/solutions/datacenter-hero.webp'))).toBe(true)
  })
}
