import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerEducationVisualContracts() {
  it('builds the education solution page from the product requirement layout', () => {
    const page = readComponent('pages/services/smart-education.vue')
    const hero = readComponent('components/solution/education/EducationHero.vue')
    const cards = readComponent('components/solution/education/EducationCapabilityCardsSection.vue')
    const values = readComponent('components/solution/education/EducationValueSection.vue')
    const agentFlow = readComponent('components/solution/education/EducationAgentFlowSection.vue')
    const cases = readComponent('components/solution/education/EducationCustomerCasesSection.vue')
    const data = readComponent('data/solutions/education.ts')
    const gridSection = readComponent('components/common/ProductFeatureGridSection.vue')
    const featureCard = readComponent('components/common/card/FeatureCard.vue')
    const cardText = readComponent('components/common/card/CardText.vue')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('EducationHero')
    expect(page).toContain('eyebrow="行业痛点"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('header-width="wide"')
    expect(page).toContain('class="pt-32"')
    expect(page).toContain('spacing="compact"')
    expect(page).toContain('eyebrow="解决方案"')
    expect(page).toContain('<ProductSystemFlowFrame label="教育智能体运行底座能力图" />')
    expect(page).toContain('EducationCapabilityCardsSection')
    expect(page).toContain('EducationValueSection')
    expect(page).toContain('EducationAgentFlowSection')
    expect(page).toContain('eyebrow="教育智能体"')
    expect(page).toContain('columns="three"')
    expect(page).toContain('EducationCustomerCasesSection')
    expect(page).toContain('CtaSection')

    expect(hero).toContain('class="relative h-[586px] overflow-hidden bg-[#1f49e5]"')
    expect(hero).toContain('education-hero-title')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)] bg-clip-text')
    expect(hero).toContain('border border-white bg-transparent')
    expect(hero).not.toContain('<style')

    expect(cards).toContain('bg-[#f6f8fb] pb-16 lg:pb-32')
    expect(cards).toContain('class="container mt-16"')
    expect(cards).toContain('eyebrow="核心功能体系"')
    expect(cards).toContain('从模型调用到任务执行，构建教育 AI 原生能力体系')
    expect(cards).toContain('xl:grid-cols-4')
    expect(cards).toContain('class="group relative h-[367px] cursor-default bg-white outline-none"')
    expect(cards).toContain('group-hover:top-[93px]')
    expect(cards).not.toContain('<style')

    expect(values).toContain('spacing="tight"')
    expect(values).toContain('container-spacing="top"')
    expect(values).toContain('eyebrow="核心价值"')
    expect(values).toContain('让 AI 从辅助工具，走向教育业务智能执行者')
    expect(values).toContain('columns="two"')
    expect(values).toContain('variant="product"')
    expect(values).toContain('class="!p-7 lg:!p-8"')
    expect(values).toContain('<IconBox :icon="item.icon" :size="40" :icon-size="20" />')
    expect(values).toContain('rounded-full bg-dt-bg-soft px-3 py-1')
    expect(values).not.toContain('<style')

    // section5a：EMQX Edge 立体方块排版 1:1 复刻
    expect(agentFlow).toContain('eyebrow="AI 原生教育"')
    expect(agentFlow).toContain('从 Copilot 到 Agent，让 AI 真正完成教育任务')
    expect(agentFlow).toContain('mt-14 grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]')
    expect(agentFlow).toContain('rounded-3xl border border-default bg-dt-bg-soft/30 p-8 shadow-sm backdrop-blur-xl lg:p-10')
    expect(agentFlow).toContain('class="space-y-10"')
    expect(agentFlow).toContain('relative flex flex-col items-start gap-6 text-left lg:flex-row lg:items-start')
    expect(agentFlow).toContain('class="relative h-[120px] w-[120px]"')
    expect(agentFlow).toContain('[perspective:800px]')
    expect(agentFlow).toContain('[transform:rotateX(55deg)_rotateZ(-45deg)] [transform-style:preserve-3d]')
    expect(agentFlow).toContain('h-[104px] w-[104px] border bg-default [transform:translateZ(-12px)]')
    expect(agentFlow).toContain('h-[104px] w-[104px] overflow-hidden border bg-default [transform:translateZ(12px)]')
    expect(agentFlow).toContain('h-[104px] w-[24px] origin-left border bg-muted [transform:rotateY(-90deg)_translateX(-12px)]')
    expect(agentFlow).toContain('h-[24px] w-[104px] origin-bottom border-x bg-default [transform:rotateX(90deg)_translateY(12px)]')
    expect(agentFlow).not.toMatch(/\sstyle=/)
    expect(agentFlow).toContain('absolute -right-2 -top-2 rounded-full border border-default bg-default px-2.5 py-1 text-[10px] font-semibold text-muted shadow-sm')
    expect(agentFlow).toContain('class="size-9"')
    expect(agentFlow).toContain('mt-3 max-w-xl text-sm leading-relaxed text-muted')
    // 右侧架构图：EMQX Edge 760×500 绝对定位画布 1:1 复刻（容器查询等比缩放）
    expect(agentFlow).toContain('@container aspect-[760/500] w-full')
    expect(agentFlow).toContain('relative h-[500px] w-[760px] origin-top-left [transform:scale(calc(100cqw/760px))]')
    expect(agentFlow).toContain('viewBox="0 0 760 500"')
    expect(agentFlow).toContain('<animate attributeName="stroke-dashoffset" values="0;-20" dur="2s" repeatCount="indefinite" />')
    expect(agentFlow).toContain('from-primary/8 via-fuchsia-500/6 to-blue-500/8 blur-3xl')
    expect(agentFlow).toContain('absolute left-1/2 top-[12px] flex -translate-x-1/2 items-center gap-4')
    expect(agentFlow).toContain('h-[56px] w-[210px]')
    expect(agentFlow).toContain('absolute left-0 top-[120px]')
    expect(agentFlow).toContain('absolute left-0 top-[300px]')
    expect(agentFlow).toContain('absolute right-0 top-[120px]')
    expect(agentFlow).toContain('absolute right-0 top-[300px]')
    expect(agentFlow).toContain('absolute left-1/2 top-[170px] -translate-x-1/2')
    expect(agentFlow).toContain('animate-value-flow')
    expect(agentFlow).toContain('[perspective:900px]')
    expect(agentFlow).toContain('h-[150px] w-[150px] overflow-hidden border border-primary/50 bg-muted [transform:translateZ(14px)]')
    expect(agentFlow).toContain('[background-size:26px_26px]')
    expect(agentFlow).toContain('absolute left-1/2 top-[242px] w-[460px] -translate-x-1/2')
    expect(agentFlow).toContain('bg-white/95 px-8 py-5 shadow-sm backdrop-blur-xl')
    expect(agentFlow).toContain('zhiyao-logo.svg?url')
    expect(agentFlow).not.toContain('<style')

    expect(cases).toContain('class="container pb-32 lg:pb-44"')
    expect(cases).toContain('class="flex flex-col gap-11"')
    expect(cases).toContain('lg:flex-row-reverse')
    expect(cases).toContain('lg:w-[320px]')
    expect(cases).toContain('查看案例详情')
    expect(cases).not.toContain('<style')

    // 共享组件 subtitle/tags 扩展（向后兼容）
    expect(gridSection).toContain('subtitle?: string')
    expect(gridSection).toContain('tags?: string[]')
    expect(gridSection).toContain(':subtitle="item.subtitle"')
    expect(gridSection).toContain(':tags="item.tags"')
    expect(featureCard).toContain('subtitle?: string')
    expect(featureCard).toContain('tags?: string[]')
    expect(featureCard).toContain(':subtitle="subtitle"')
    expect(featureCard).toContain('v-if="tags?.length"')
    expect(cardText).toContain('subtitle?: string')
    expect(cardText).toContain('v-if="subtitle"')
    expect(cardText).not.toContain('.card-text__subtitle')

    expect(data).toContain("image: '/images/solutions/education-hero.png'")
    expect(data).toContain("title: '智慧教育解决方案'")
    expect(data).toContain("title: '教育大模型网关'")
    expect(data).toContain("badge: '01'")
    expect(data).toContain("'border-violet-500/45'")
    expect(data).toContain("'bg-fuchsia-500/12'")
    expect(data).toContain("'text-blue-500'")
    expect(data).toContain("name: '智曜·AgentOS'")
    expect(data).toContain("title: 'AI 教师助手'")
    expect(data).toContain("title: '某高校教育智能体平台'")
    expect(data).toContain("value: '10,000+'")
    expect(existsSync(join(root, 'public/images/solutions/education-hero.png'))).toBe(true)
    expect(existsSync(join(root, 'public/images/solutions/education/image-placeholder.svg'))).toBe(true)
  })
}
