import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerEnergySavingVisualContracts() {
  it('builds the energy-saving solution page from the product requirement layout', () => {
    const page = readComponent('pages/solutions/energy.vue')
    const hero = readComponent('components/solution/energy-saving/EnergySavingHero.vue')
    const cards = readComponent('components/solution/energy-saving/EnergySavingCapabilityCardsSection.vue')
    const values = readComponent('components/solution/energy-saving/EnergySavingValueSection.vue')
    const cases = readComponent('components/solution/energy-saving/EnergySavingCustomerCasesSection.vue')
    const data = readComponent('data/solutions/energy-saving.ts')
    const hubFlow = readComponent('components/demo/energy-storage-hub/EnergyStorageHubFlow.client.vue')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('EnergySavingHero')
    expect(page).toContain('eyebrow="行业痛点"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('header-width="wide"')
    expect(page).toContain('class="pt-32"')
    expect(page).toContain('spacing="compact"')
    expect(page).toContain('EnergySavingCapabilityCardsSection')
    expect(page).toContain('EnergySavingValueSection')
    expect(page).toContain('EnergySavingCustomerCasesSection')
    expect(page).toContain('CtaSection')

    expect(page).toContain('<SectionShell title-id="energy-saving-system-title" spacing="compact" class="max-lg:hidden">')
    expect(page).toContain('eyebrow="解决方案"')
    expect(page).toContain('<ProductSystemFlowFrame label="储能智能运营能力图" fallback-text="储能智能运营能力图加载中">')
    expect(page).toContain('EnergyStorageHubFlow')
    expect(page).toContain('<ClientOnly>')
    expect(page).toContain('h-[560px] w-[1704px]')
    expect(page).toContain('w-full overflow-hidden @container')
    expect(page).toContain('scale-[min(1,calc(100cqw/1704px))]')
    expect(page).toContain('-translate-x-1/2 -translate-y-1/2')
    expect(page).not.toContain(':grid="false"')
    expect(page).not.toContain('<style')
    expect(page).not.toContain('style=')

    expect(hubFlow).toContain("type: 'energyStorageHubCurve'")
    expect(hubFlow).toContain('viewportY: 21')
    expect(hubFlow).toContain('PCS 储能变流器')
    expect(hubFlow).toContain('BMS 电池管理')
    expect(hubFlow).toContain('EMS 能源管理')
    expect(hubFlow).toContain('探曜·AI 物联感知')
    expect(hubFlow).toContain('数曜·数据治理')
    expect(hubFlow).toContain('储能数据资产')
    expect(hubFlow).toContain('运行监测与预警')
    expect(hubFlow).toContain('电池健康评估')
    expect(hubFlow).toContain('充放电策略优化')
    expect(hubFlow).not.toContain('<style')

    expect(hero).toContain('class="relative h-[586px] overflow-hidden bg-[#1f49e5]"')
    expect(hero).toContain('energy-saving-hero-title')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('w-[min(760px,100%)]')
    expect(hero).toContain('top-[clamp(132px,16.67vw,320px)]')
    expect(hero).toContain('top-[clamp(246px,24.375vw,468px)]')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)] bg-clip-text')
    expect(hero).toContain('border border-white bg-transparent')
    expect(hero).toContain('!text-white')
    expect(hero).toContain('class="size-6 shrink-0 !text-white"')
    expect(hero).toContain('stroke="currentColor"')
    expect(hero).not.toContain('<style')

    expect(cards).toContain('bg-[#f6f8fb] pb-16 lg:pb-32')
    expect(cards).toContain('class="container mt-16"')
    expect(cards).toContain('eyebrow="解决方案"')
    expect(cards).toContain('贯通感知、数据、分析与优化的储能智能能力体系')
    expect(cards).toContain('xl:grid-cols-4')
    expect(cards).toContain('<BaseCard')
    expect(cards).toContain('class="group relative h-[367px] cursor-default bg-white outline-none"')
    expect(cards).toContain('left-4 right-4 top-[279.22px]')
    expect(cards).toContain('inset-x-0 top-0 h-[181px] w-full')
    expect(cards).toContain('h-full w-full min-w-full object-cover')
    expect(cards).toContain('group-hover:top-[93px]')
    expect(cards).toContain('group-hover:-translate-y-[74px]')
    expect(cards).toContain('top-[255.22px]')
    expect(cards).toContain('group-hover:opacity-100')
    expect(cards).not.toContain('<style')

    expect(values).toContain('spacing="tight"')
    expect(values).toContain('container-spacing="top"')
    expect(values).toContain('align="left"')
    expect(values).toContain('columns="three"')
    expect(values).toContain('<BaseCard')
    expect(values).not.toContain('eyebrow=')
    expect(values).not.toContain('subtitle=')
    expect(values).not.toContain('<style')

    expect(cases).toContain('SolutionCasePicksSection')
    expect(cases).toContain('page-key="energy"')
    expect(cases).not.toContain('<style')

    expect(data).toContain("image: '/images/solutions/energy-saving-hero.webp'")
    expect(data).toContain("title: '智慧储能解决方案'")
    expect(data).toContain("title: '储能设备接入管理'")
    expect(existsSync(join(root, 'public/images/solutions/energy-saving-hero.webp'))).toBe(true)
    expect(existsSync(join(root, 'public/images/solutions/energy-saving/image-placeholder.svg'))).toBe(true)
  })
}
