import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerEnergySavingVisualContracts() {
  it('builds the energy-saving solution page from the product requirement layout', () => {
    const page = readComponent('pages/solutions/energy.vue')
    const hero = readComponent('components/solution/energy-saving/EnergySavingHero.vue')
    const cards = readComponent('components/solution/energy-saving/EnergySavingCapabilityCardsSection.vue')
    const values = readComponent('components/solution/energy-saving/EnergySavingValueSection.vue')
    const cases = readComponent('components/solution/energy-saving/EnergySavingCustomerCasesSection.vue')
    const data = readComponent('data/solutions/energy-saving.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('EnergySavingHero')
    expect(page).toContain('eyebrow="行业痛点"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('header-width="wide"')
    expect(page).toContain('class="pt-32"')
    expect(page).toContain('spacing="compact"')
    expect(page).toContain('<ProductSystemFlowFrame label="储能智能运营能力图" />')
    expect(page).toContain('EnergySavingCapabilityCardsSection')
    expect(page).toContain('EnergySavingValueSection')
    expect(page).toContain('EnergySavingCustomerCasesSection')
    expect(page).toContain('CtaSection')

    expect(hero).toContain('class="relative h-[586px] overflow-hidden bg-[#1f49e5]"')
    expect(hero).toContain('energy-saving-hero-title')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('w-[min(760px,100%)]')
    expect(hero).toContain('top-[clamp(132px,16.67vw,320px)]')
    expect(hero).toContain('top-[clamp(246px,24.375vw,468px)]')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)] bg-clip-text')
    expect(hero).toContain('border border-white bg-transparent')
    expect(hero).toContain('!text-white')
    expect(hero).toContain('class="size-6 shrink-0 !text-white"')
    expect(hero).toContain('stroke="currentColor"')
    expect(hero).not.toContain('<style')

    expect(cards).toContain('bg-[#f6f8fb] pb-16 lg:pb-32')
    expect(cards).toContain('class="container mt-16"')
    expect(cards).toContain('eyebrow="解决方案"')
    expect(cards).toContain('贯通感知、数据、分析与优化的储能智能能力体系')
    expect(cards).toContain('xl:grid-cols-4')
    expect(cards).toContain('<BaseCard')
    expect(cards).toContain('class="group relative h-[367px] cursor-default bg-white outline-none"')
    expect(cards).toContain('left-4 right-4 top-[279.22px]')
    expect(cards).toContain('inset-x-0 top-0 h-[181px] w-full')
    expect(cards).toContain('h-full w-full min-w-full object-cover')
    expect(cards).toContain('group-hover:top-[93px]')
    expect(cards).toContain('group-hover:-translate-y-[74px]')
    expect(cards).toContain('top-[255.22px]')
    expect(cards).toContain('group-hover:opacity-100')
    expect(cards).not.toContain('<style')

    expect(values).toContain('spacing="tight"')
    expect(values).toContain('container-spacing="top"')
    expect(values).toContain('align="left"')
    expect(values).toContain('columns="three"')
    expect(values).toContain('<BaseCard')
    expect(values).not.toContain('eyebrow=')
    expect(values).not.toContain('subtitle=')
    expect(values).not.toContain('<style')

    expect(cases).toContain('class="container pb-32 lg:pb-44"')
    expect(cases).toContain('class="flex flex-col gap-11"')
    expect(cases).toContain('lg:flex-row-reverse')
    expect(cases).toContain('lg:w-[320px]')
    expect(cases).toContain('查看案例详情')
    expect(cases).not.toContain('<style')

    expect(data).toContain("image: '/images/solutions/energy-saving-hero.png'")
    expect(data).toContain("title: '智慧储能解决方案'")
    expect(data).toContain("title: '储能设备接入管理'")
    expect(data).toContain("title: '某大型工业园区储能项目'")
    expect(data).toContain("value: '99.9%'")
    expect(existsSync(join(root, 'public/images/solutions/energy-saving-hero.png'))).toBe(true)
    expect(existsSync(join(root, 'public/images/solutions/energy-saving/image-placeholder.svg'))).toBe(true)
  })
}
