import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerFdeVisualContracts() {
  it('builds the FDE solution page from the product requirement layout', () => {
    const page = readComponent('pages/services/enterprise-ai-delivery.vue')
    const aliasPage = readComponent('pages/solutions/fde.vue')
    const content = readComponent('components/solution/fde/FdePageContent.vue')
    const hero = readComponent('components/solution/fde/FdeHero.vue')
    const evolution = readComponent('components/solution/fde/FdeEvolutionSection.vue')
    const evolutionVisual = readComponent('components/solution/fde/FdeEvolutionVisual.vue')
    const evolutionCube = readComponent('components/solution/fde/FdeEvolutionCube.vue')
    const prototypeVisual = readComponent('components/solution/fde/FdeEvolutionPrototypeVisual.vue')
    const productionVisual = readComponent('components/solution/fde/FdeEvolutionProductionVisual.vue')
    const scaleVisual = readComponent('components/solution/fde/FdeEvolutionScaleVisual.vue')
    const capabilityCards = readComponent('components/solution/fde/FdeCapabilityCardsSection.vue')
    const valueSection = readComponent('components/solution/fde/FdeValueSection.vue')
    const useCases = readComponent('components/solution/fde/FdeUseCasesSection.vue')
    const cases = readComponent('components/solution/fde/FdeCustomerCasesSection.vue')
    const data = readComponent('data/solutions/fde.ts')
    const solutionFlow = readComponent('components/demo/fde-solution/FdeSolutionFlow.client.vue')
    const workModeFlow = readComponent('components/demo/fde-work-mode/FdeWorkModeFlow.client.vue')
    const deliveryFlow = readComponent('components/demo/fde-delivery/FdeDeliveryFlow.client.vue')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('FdePageContent')
    expect(aliasPage).toContain('FdePageContent')
    expect(content).toContain('<FdeHero />')
    expect(content).toContain('eyebrow="行业痛点"')
    expect(content).toContain('FdeEvolutionSection')
    expect(content).toContain('eyebrow="解决方案"')
    expect(content).toContain(':items="fdeSolutionItems"')
    expect(content).toContain('columns="four"')
    expect(content).toContain('<ProductSystemFlowFrame')
    expect(content).toContain(':label="fdeSolutionLabel"')
    expect(content).toContain(':fallback-text="`${fdeSolutionLabel}加载中`"')
    expect(content).toContain('class="mb-10"')
    expect(content).toContain('FdeSolutionFlow')
    expect(content).toContain(':label="fdeWorkModeLabel"')
    expect(content).toContain(':fallback-text="`${fdeWorkModeLabel}加载中`"')
    expect(content).toContain('FdeWorkModeFlow')
    expect(content).toContain(':label="fdeDeliveryLabel"')
    expect(content).toContain(':fallback-text="`${fdeDeliveryLabel}加载中`"')
    expect(content).toContain('FdeDeliveryFlow')
    expect(content).toContain('<ClientOnly>')
    expect(content).toContain('relative z-[1] mx-auto h-full w-[min(1704px,100%)] overflow-hidden')
    expect(content).toContain('h-[560px] w-[1704px]')
    expect(content).toContain('-translate-x-1/2 -translate-y-1/2')
    expect(content).toContain(':viewport-y="-17"')
    expect(content).toContain(':viewport-y="10"')
    expect(content).toContain(':viewport-y="46"')
    expect(content).not.toContain(':grid="false"')
    expect(solutionFlow).toContain('viewportY: -7')
    expect(solutionFlow).toContain("type: 'fdeSolutionCurve'")
    expect(solutionFlow).toContain('DeepTrols 基础能力')
    expect(solutionFlow).toContain('数曜 ｜ 数智基建')
    expect(solutionFlow).toContain('博曜 ｜ 知识中枢')
    expect(solutionFlow).toContain('智曜 ｜ 智能引擎')
    expect(solutionFlow).toContain('场景识别')
    expect(solutionFlow).toContain('系统集成与生产上线')
    expect(solutionFlow).not.toContain('<style')
    expect(workModeFlow).toContain('viewportY: 20')
    expect(workModeFlow).toContain("type: 'fdeWorkModeCurve'")
    expect(workModeFlow).toContain('业务问题识别')
    expect(workModeFlow).toContain('生产运行迭代')
    expect(workModeFlow).not.toContain('fdeWorkModeReturn')
    expect(workModeFlow).not.toContain('<style')
    expect(deliveryFlow).toContain('viewportY: 56')
    expect(deliveryFlow).toContain("type: 'fdeDeliveryCurve'")
    expect(deliveryFlow).toContain('需求诊断')
    expect(deliveryFlow).toContain('场景清单确认')
    expect(deliveryFlow).not.toContain('<style')
    expect(content).toContain('eyebrow="FDE工作模式"')
    expect(content).toContain('FdeCapabilityCardsSection')
    expect(content).toContain('<FdeValueSection />')
    expect(content).toContain('FdeUseCasesSection')
    expect(content).toContain('eyebrow="交付流程"')
    expect(content).toContain('FdeCustomerCasesSection')
    expect(content).toContain('CtaSection')
    expect(content).not.toContain('<style')
    expect(content).not.toContain('style=')

    expect(hero).toContain('min-h-screen')
    expect(hero).toContain(':src="fdeHero.video"')
    expect(hero).toContain('autoplay')
    expect(hero).toContain('muted')
    expect(hero).toContain('loop')
    expect(hero).toContain('playsinline')
    expect(hero).toContain('items-center justify-center')
    expect(hero).toContain('<h2')
    expect(hero).not.toContain('pt-[var(--dt-header-height)]')
    expect(hero).not.toContain('whitespace-nowrap')
    expect(hero).not.toContain('<style')
    expect(hero).not.toContain('style=')

    expect(evolution).toContain('eyebrow="FDE 的价值演进"')
    expect(evolution).toContain('title="从 AI 原型，到真正进入生产"')
    expect(evolution).toContain('align="left"')
    expect(evolution).toContain('width="wide"')
    expect(evolution).toContain('grid gap-0')
    expect(evolution).toContain('lg:grid-cols-2')
    expect(evolution).toContain("item.visualSide === 'left' ? 'lg:col-start-2' : 'lg:col-start-1'")
    expect(evolution).toContain("item.visualSide === 'left' ? 'lg:col-start-1 lg:row-start-1' : 'lg:col-start-2'")
    expect(evolution).toContain('text-sm font-semibold uppercase tracking-wide text-muted')
    expect(evolution).toContain('mt-3 text-2xl font-semibold leading-tight text-highlighted')
    expect(evolution).toContain('mt-5 space-y-2 text-base text-default')
    expect(evolution).toContain('mt-2 size-1.5 shrink-0 rounded-full bg-primary/70')
    expect(evolution).toContain('class="w-full bg-default"')
    expect(evolution).toContain('flex items-start gap-2')
    expect(evolution).toContain('[&_.rounded-lg]:rounded-none [&_.rounded-2xl]:rounded-none [&_.rounded-md]:rounded-none')
    expect(evolution).not.toContain('style=')
    expect(evolution).not.toContain('<style')

    expect(evolutionVisual).toContain('FdeEvolutionPrototypeVisual')
    expect(evolutionVisual).toContain('FdeEvolutionProductionVisual')
    expect(evolutionVisual).toContain('FdeEvolutionScaleVisual')
    expect(evolutionVisual).not.toContain('<style')
    expect(evolutionVisual).not.toContain('style=')

    expect(evolutionCube).toContain('inline-flex [perspective:800px]')
    expect(evolutionCube).toContain('[transform:rotateX(55deg)_rotate(-45deg)]')
    expect(evolutionCube).toContain('[transform-style:preserve-3d]')
    expect(evolutionCube).toContain('h-[90px] w-[90px] [transform:translateZ(10px)]')
    expect(evolutionCube).toContain('h-[70px] w-[70px] [transform:translateZ(8px)]')
    expect(evolutionCube).toContain('border-violet-500/20')
    expect(evolutionCube).toContain('border-blue-500/20')
    expect(evolutionCube).toContain('border-violet-500/40')
    expect(evolutionCube).toContain('bg-dt-bg-elevated/50')
    expect(evolutionCube).not.toContain('<style')
    expect(evolutionCube).not.toContain('style=')

    expect(prototypeVisual).toContain('业务问题')
    expect(prototypeVisual).toContain('场景·数据')
    expect(prototypeVisual).toContain('AI原型')
    expect(prototypeVisual).toContain('模型·应用')
    expect(prototypeVisual).toContain('M 160 155 Q 260 125 360 155')
    expect(prototypeVisual).toContain('animateMotion')
    expect(prototypeVisual).toContain('id="fdeUnifiedGrad"')
    expect(prototypeVisual).toContain('size-[260px]')
    expect(prototypeVisual).toContain('from-primary/8 via-violet-500/5 to-blue-500/8')
    expect(prototypeVisual).toContain('mt-10 flex items-center gap-3 rounded-full border border-primary/40 bg-default px-5 py-2.5 backdrop-blur-sm')
    expect(prototypeVisual).toContain('h-4 w-px bg-default')
    expect(prototypeVisual).not.toContain('<style')
    expect(prototypeVisual).not.toContain('style=')

    expect(productionVisual).toContain('生产业务请求')
    expect(productionVisual).not.toContain('Production Workload')
    expect(productionVisual).toContain('AI 应用')
    expect(productionVisual).toContain('企业系统')
    expect(productionVisual).toContain('运行治理')
    expect(productionVisual).toContain('animate-pulse-dot')
    expect(productionVisual).toContain('M 200 165 L 270 165')
    expect(productionVisual).toContain('M 310 165 L 370 165')
    expect(productionVisual).toContain('id="fdeStorageFlow"')
    expect(productionVisual).toContain('size-[280px]')
    expect(productionVisual).toContain('flex items-end gap-8')
    expect(productionVisual).toContain('animate-value-hub')
    expect(productionVisual).toContain('text-lg font-bold text-primary')
    expect(productionVisual).not.toContain('<style')
    expect(productionVisual).not.toContain('style=')

    expect(scaleVisual).toContain('业务上下文')
    expect(scaleVisual).toContain('FDE')
    expect(scaleVisual).toContain('知识智能体')
    expect(scaleVisual).toContain('数据智能体')
    expect(scaleVisual).toContain('业务智能体')
    expect(scaleVisual).toContain('viewBox="0 0 400 400"')
    expect(scaleVisual).toContain('id="fdeAIInputClip"')
    expect(scaleVisual).toContain('M 200 72 L 200 148')
    expect(scaleVisual).toContain('M 200 155 Q 140 185 100 235')
    expect(scaleVisual).toContain('M 200 155 Q 260 185 300 235')
    expect(scaleVisual).toContain('animate-value-hub')
    expect(scaleVisual).toContain('mt-14 flex items-start gap-10')
    expect(scaleVisual).toContain('flex size-16 items-center justify-center rounded-2xl border border-default bg-default shadow-lg')
    expect(scaleVisual).not.toContain('<style')
    expect(scaleVisual).not.toContain('style=')

    expect(capabilityCards).toContain('bg-[#f6f8fb] pb-16 lg:pb-32')
    expect(capabilityCards).toContain('class="container mt-16"')
    expect(capabilityCards).toContain('eyebrow="核心能力"')
    expect(capabilityCards).toContain('xl:grid-cols-4')
    expect(capabilityCards).toContain('class="group relative h-[367px] cursor-default bg-white outline-none"')
    expect(capabilityCards).toContain('src="/images/solutions/fde/image-placeholder.svg"')
    expect(capabilityCards).toContain('group-hover:top-[93px]')
    expect(capabilityCards).toContain('group-hover:-translate-y-[74px]')
    expect(capabilityCards).not.toContain('<style')

    expect(useCases).toContain('CarouselControls')
    expect(useCases).toContain('relative flow-root bg-dt-bg pb-16 lg:pb-32')
    expect(useCases).toContain('eyebrow="应用场景"')
    expect(useCases).toContain('title="从一个高价值问题开始，让 AI 深入核心业务"')
    expect(useCases).toContain('updateControls')
    expect(useCases).toContain('getUseCaseStep')
    expect(useCases).toContain('scrollBy')
    expect(useCases).toContain('snap-x snap-mandatory gap-6')
    expect(useCases).toContain('basis-full shrink-0 snap-start')
    expect(useCases).toContain('layout="split"')
    expect(useCases).toContain(':previous-disabled="!canGoPrevious"')
    expect(useCases).toContain(':next-disabled="!canGoNext"')
    expect(useCases).toContain('previous-label="上一条应用场景"')
    expect(useCases).toContain('next-label="下一条应用场景"')
    expect(useCases).toContain('grid-rows-[auto_auto_1fr]')
    expect(useCases).toContain('content-start gap-4 rounded-lg border border-default bg-muted p-8')
    expect(useCases).toContain('before:inset-0 before:rounded-lg before:bg-[image:var(--dt-gradient-hero)] before:opacity-0')
    expect(useCases).toContain('hover:border-primary hover:before:opacity-100')
    expect(useCases).toContain('absolute top-4 right-4 z-10 size-5 text-dimmed opacity-0 transition-opacity duration-300 group-hover:opacity-100')
    expect(useCases).toContain('text-lg font-semibold text-highlighted')
    expect(useCases).toContain('text-base font-normal text-default')
    expect(useCases).not.toContain('<style')

    expect(valueSection).toContain('eyebrow="核心价值"')
    expect(valueSection).toContain('title="缩短 AI 从想法到价值的距离"')
    expect(valueSection).toContain('SectionShell title-id="fde-value-title" spacing="compact" container-spacing="top"')
    expect(valueSection).toContain('<CardGrid columns="two">')
    expect(valueSection).toContain('variant="product"')
    expect(valueSection).toContain('padding="none"')
    expect(valueSection).toContain('accent')
    expect(valueSection).toContain('equal-height')
    expect(valueSection).toContain('class="!p-7 lg:!p-8"')
    expect(valueSection).toContain('<IconBox :icon="item.icon" :size="40" :icon-size="20" />')
    expect(valueSection).toContain('m-0 text-2xl font-bold leading-[1.25] text-highlighted')
    expect(valueSection).toContain('m-0 mt-5 text-lg font-semibold leading-normal text-primary')
    expect(valueSection).toContain('rounded-full bg-dt-bg-soft px-3 py-1 text-xs leading-relaxed text-muted')
    expect(valueSection).not.toContain('<style')
    expect(valueSection).not.toContain('style=')

    expect(cases).toContain('class="container pb-32 lg:pb-44"')
    expect(cases).toContain('class="flex flex-col gap-11"')
    expect(cases).toContain('flex flex-col rounded-lg border border-default lg:flex-row')
    expect(cases).toContain('lg:flex-row-reverse')
    expect(cases).toContain('bg-[image:var(--dt-gradient-text)] bg-clip-text text-transparent')
    expect(cases).toContain('lg:w-[320px]')
    expect(cases).toContain('<BaseButton href="/cases">查看案例详情</BaseButton>')
    expect(cases).toContain('src="/images/solutions/fde/image-placeholder.svg"')
    expect(cases).not.toContain('<style')

    expect(data).toContain("video: '/images/solutions/fde/hero-bg.mp4'")
    expect(data).toContain("title: 'DeepTrols FDE解决方案'")
    expect(data).toContain("title: '企业知识智能化'")
    expect(data).toContain("metric: '50%'")
    expect(data).toContain("metric: '70%'")
    expect(data).toContain("metric: '5%'")
    expect(existsSync(join(root, 'public/images/solutions/fde/hero-bg.mp4'))).toBe(true)
    expect(existsSync(join(root, 'public/images/solutions/fde/image-placeholder.svg'))).toBe(true)
  })
}
