import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerHydraulicVisualContracts() {
  it('builds the hydraulic solution page from the product requirement layout', () => {
    const page = readComponent('pages/solutions/water.vue')
    const hero = readComponent('components/solution/hydraulic/HydraulicHero.vue')
    const cards = readComponent('components/solution/hydraulic/HydraulicCapabilityCardsSection.vue')
    const values = readComponent('components/solution/hydraulic/HydraulicValueSection.vue')
    const cases = readComponent('components/solution/hydraulic/HydraulicCustomerCasesSection.vue')
    const data = readComponent('data/solutions/hydraulic.ts')
    const gridSection = readComponent('components/common/ProductFeatureGridSection.vue')
    const featureCard = readComponent('components/common/card/FeatureCard.vue')
    const cardText = readComponent('components/common/card/CardText.vue')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('HydraulicHero')
    expect(page).toContain('eyebrow="行业痛点"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('header-width="wide"')
    expect(page).toContain('class="pt-32"')
    expect(page).toContain('spacing="compact"')
    expect(page).toContain('eyebrow="解决方案"')
    expect(page).toContain('<ProductSystemFlowFrame label="智慧水利知识中枢能力图" />')
    expect(page).toContain('HydraulicCapabilityCardsSection')
    expect(page).toContain('HydraulicValueSection')
    expect(page).toContain('HydraulicCustomerCasesSection')
    expect(page).toContain('CtaSection')

    expect(hero).toContain('class="relative h-[586px] overflow-hidden bg-[#1f49e5]"')
    expect(hero).toContain('hydraulic-hero-title')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('w-[min(760px,100%)]')
    expect(hero).toContain('top-[clamp(132px,16.67vw,320px)]')
    expect(hero).toContain('top-[clamp(246px,24.375vw,468px)]')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)] bg-clip-text')
    expect(hero).toContain('border border-white bg-transparent')
    expect(hero).toContain('!text-white')
    expect(hero).toContain('class="size-6 shrink-0 !text-white"')
    expect(hero).toContain('stroke="currentColor"')
    expect(hero).not.toContain('<style')

    expect(cards).toContain('bg-[#f6f8fb] pb-16 lg:pb-32')
    expect(cards).toContain('class="container mt-16"')
    expect(cards).toContain('eyebrow="核心功能体系"')
    expect(cards).toContain('从数据治理到知识决策，构建智慧水利核心能力')
    expect(cards).toContain('xl:grid-cols-4')
    expect(cards).toContain('<BaseCard')
    expect(cards).toContain('class="group relative h-[367px] cursor-default bg-white outline-none"')
    expect(cards).toContain('left-4 right-4 top-[279.22px]')
    expect(cards).toContain('inset-x-0 top-0 h-[181px] w-full')
    expect(cards).toContain('h-full w-full min-w-full object-cover')
    expect(cards).toContain('group-hover:top-[93px]')
    expect(cards).toContain('group-hover:-translate-y-[74px]')
    expect(cards).toContain('top-[255.22px]')
    expect(cards).toContain('group-hover:opacity-100')
    expect(cards).not.toContain('<style')

    expect(values).toContain('spacing="tight"')
    expect(values).toContain('container-spacing="top"')
    expect(values).toContain('eyebrow="核心价值"')
    expect(values).toContain('让水利知识可沉淀、可理解、可调用、可决策')
    expect(values).toContain('columns="two"')
    expect(values).toContain('variant="product"')
    expect(values).toContain('class="!p-7 lg:!p-8"')
    expect(values).toContain('<IconBox :icon="item.icon" :size="40" :icon-size="20" />')
    expect(values).toContain('rounded-full bg-dt-bg-soft px-3 py-1')
    expect(values).not.toContain('<style')

    expect(cases).toContain('class="container pb-32 lg:pb-44"')
    expect(cases).toContain('class="flex flex-col gap-11"')
    expect(cases).toContain('lg:flex-row-reverse')
    expect(cases).toContain('lg:w-[320px]')
    expect(cases).toContain('查看案例详情')
    expect(cases).not.toContain('<style')

    expect(gridSection).toContain('points?: string[]')
    expect(gridSection).toContain(':points="item.points"')
    expect(featureCard).toContain('points?: string[]')
    expect(featureCard).toContain(':points="points"')
    expect(cardText).toContain('points?: string[]')
    expect(cardText).toContain('v-if="points?.length"')
    expect(cardText).toContain('card-text__title')
    expect(cardText).toContain('card-text__description')

    expect(data).toContain("image: '/images/solutions/hydraulic-hero.png'")
    expect(data).toContain("title: '智慧水利解决方案'")
    expect(data).toContain("title: '水利知识库管理'")
    expect(data).toContain("title: '某省级水利知识平台'")
    expect(data).toContain("value: '185类'")
    expect(existsSync(join(root, 'public/images/solutions/hydraulic-hero.png'))).toBe(true)
    expect(existsSync(join(root, 'public/images/solutions/hydraulic/image-placeholder.svg'))).toBe(true)
  })
}
