import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../../utils'

export function registerManufacturingVisualContracts() {
  it('builds the manufacturing solution page from the product requirement layout', () => {
    const page = readComponent('pages/solutions/manufacturing.vue')
    const hero = readComponent('components/solution/manufacturing/ManufacturingHero.vue')
    const cards = readComponent('components/solution/manufacturing/ManufacturingCapabilityCardsSection.vue')
    const cases = readComponent('components/solution/manufacturing/ManufacturingCustomerCasesSection.vue')
    const data = readComponent('data/solutions/manufacturing.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('ManufacturingHero')
    expect(page).toContain('eyebrow="行业痛点"')
    expect(page).toContain('columns="two"')
    expect(page).toContain('header-width="wide"')
    expect(page).not.toContain(':icon-box-size="56"')
    expect(page).not.toContain(':icon-size="48"')
    expect(page).toContain('<ProductSystemFlowFrame label="制造智能闭环能力图" class="mb-10" />')
    expect(page).toContain('ManufacturingCapabilityCardsSection')
    expect(page).toContain('title="为什么选择深度数智"')
    expect(page).toContain('columns="three"')
    expect(page).toContain('ManufacturingCustomerCasesSection')
    expect(page).toContain('CtaSection')
    expect(page).toContain('class="pt-32"')
    expect(page).toContain('spacing="compact"')
    expect(page).toContain('spacing="tight"')
    expect(page).toContain('container-spacing="top"')

    expect(hero).toContain('class="relative h-[586px] overflow-hidden bg-[#1f49e5]"')
    expect(hero).toContain('manufacturing-hero-title')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('w-[min(760px,100%)]')
    expect(hero).toContain('top-[clamp(132px,16.67vw,320px)]')
    expect(hero).toContain('top-[clamp(246px,24.375vw,468px)]')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)] bg-clip-text')
    expect(hero).toContain('border border-white bg-transparent')
    expect(hero).toContain('!text-white')
    expect(hero).toContain('class="size-6 shrink-0 !text-white"')
    expect(hero).toContain('stroke="currentColor"')
    expect(hero).not.toContain('<style')

    expect(cards).toContain('bg-[#f6f8fb] pb-16 lg:pb-32')
    expect(cards).toContain('class="container mt-16"')
    expect(cards).toContain('核心功能体系')
    expect(cards).toContain('xl:grid-cols-4')
    expect(cards).toContain('<BaseCard')
    expect(cards).toContain('class="group relative h-[367px] cursor-default bg-white outline-none"')
    expect(cards).toContain('left-4 right-4 top-[279.22px]')
    expect(cards).not.toContain('w-[263px]')
    expect(cards).not.toContain('rounded-none')
    expect(cards).not.toContain('hover:translate-y-0')
    expect(cards).not.toContain('hover:shadow-none')
    expect(cards).toContain('h-[367px]')
    expect(cards).toContain('inset-x-0 top-0 h-[181px] w-full')
    expect(cards).toContain('h-full w-full min-w-full object-cover')
    expect(cards).toContain('group-hover:top-[93px]')
    expect(cards).toContain('group-hover:-translate-y-[74px]')
    expect(cards).toContain('top-[255.22px]')
    expect(cards).toContain('group-hover:opacity-100')
    expect(cards).not.toContain('<style')

    expect(cases).toContain('class="container pb-32 lg:pb-44"')
    expect(cases).toContain('class="flex flex-col gap-11"')
    expect(cases).toContain('lg:flex-row-reverse')
    expect(cases).toContain('lg:w-[320px]')
    expect(cases).toContain('查看案例详情')
    expect(cases).not.toContain('<style')

    expect(data).toContain("image: '/images/solutions/manufacturing-hero.png'")
    expect(data).toContain("title: '智能制造解决方案'")
    expect(data).toContain("title: 'APS智能生产排程'")
    expect(data).toContain("title: '某大型装备制造企业'")
    expect(data).toContain("value: '2,000+'")
    expect(existsSync(join(root, 'public/images/solutions/manufacturing-hero.png'))).toBe(true)
  })
}
