import { describe, expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerDeviceAgentPanelVisualContracts() {
describe('device agent runtime panel contract', () => {
  it('keeps the ESS-01 closed loop across the six runtime panels', () => {
    const eventPanel = readComponent('components/product/device-agent/runtime/RuntimeEventPanel.vue')
    const contextPanel = readComponent('components/product/device-agent/runtime/RuntimeContextPanel.vue')
    const toolsPanel = readComponent('components/product/device-agent/runtime/RuntimeToolsPanel.vue')
    const skillsPanel = readComponent('components/product/device-agent/runtime/RuntimeSkillsPanel.vue')
    const guardrailsPanel = readComponent('components/product/device-agent/runtime/RuntimeGuardrailsPanel.vue')
    const guardrailsSequence = readComponent('components/product/device-agent/runtime/RuntimeGuardrailsSequence.vue')
    const tracePanel = readComponent('components/product/device-agent/runtime/RuntimeTracePanel.vue')

    expect(eventPanel).toContain('badge="监听中"')
    expect(eventPanel).toContain('DEVICE AGENT')
    expect(eventPanel).toContain('等待事件')
    expect(eventPanel).toContain('事件已触发')
    expect(eventPanel).toContain('61.8°C')
    expect(eventPanel).toContain('rounded-xl border border-primary/20 bg-primary/5 p-3')
    expect(eventPanel).toContain('animate-ping')
    expect(eventPanel).toContain("triggered ? '事件已触发' : '等待事件'")
    expect(eventPanel).toContain('h-1.5 flex-1 rounded-full transition-colors duration-200')
    expect(eventPanel).toContain("index < activeBars ? 'bg-primary' : 'bg-dt-bg-soft'")
    expect(eventPanel).toContain('<template #footer>')
    expect(eventPanel).toContain('max-w-xl text-sm text-muted lg:line-clamp-2')
    expect(eventPanel).toContain('验证来源与事件结构')
    expect(eventPanel).toContain('关联设备与历史上下文')
    expect(eventPanel).toContain('ArrowRight')
    expect(eventPanel).toContain('animate-pulse')
    expect(eventPanel).toContain("import IconBox from '~/components/common/card/IconBox.vue'")
    expect(eventPanel).toContain("stepState(index) === 'pending' ? 'soft' : 'primary'")
    expect(eventPanel).toContain('truncate text-sm font-semibold text-highlighted')
    expect(eventPanel).toContain('mt-1 hidden truncate text-xs leading-5 text-muted xl:block')
    expect(eventPanel).toContain('mt-5 rounded-xl border border-dt-line-strong/60 bg-dt-bg p-2.5')
    expect(eventPanel).toContain('flex items-baseline justify-between gap-2 text-xs leading-4 transition-opacity duration-500')
    expect(eventPanel).toContain('mb-3 flex items-center gap-2')
    expect(eventPanel).toContain('grid gap-2')
    expect(eventPanel).toContain('mt-5 flex items-stretch gap-1')

    expect(contextPanel).toContain('title="设备上下文引擎"')
    expect(contextPanel).toContain('badge="实时构建"')
    expect(contextPanel).toContain('ESS-01 设备上下文')
    expect(contextPanel).toContain('<RuntimeContextSnapshot :group="activeSnapshotGroup" />')

    const snapshot = readComponent('components/product/device-agent/runtime/RuntimeContextSnapshot.vue')
    expect(snapshot).not.toContain('持续更新')
    expect(snapshot).not.toContain('animate-sync-pulse')
    expect(snapshot).toContain('flex gap-1.5 overflow-x-auto xl:grid xl:grid-cols-7')
    expect(snapshot).toContain('最高电芯温度')
    expect(snapshot).toContain('偏离幅度')
    expect(snapshot).toContain('知识匹配')
    expect(contextPanel).toContain('上下文构建序列')
    expect(contextPanel).toContain('context.build({ device: "ESS-01", sources: 4 })')
    expect(contextPanel).toContain('Context Ready · 1.2s')
    expect(contextPanel).toContain("import IconBox from '~/components/common/card/IconBox.vue'")
    expect(contextPanel).toContain('shrink-0 rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary')
    expect(contextPanel).toContain('mt-2 grid min-h-0 flex-1 grid-cols-2 gap-2 sm:gap-3 xl:flex-none xl:grid-cols-4')
    expect(contextPanel).toContain('mt-3 flex items-center gap-2')
    expect(contextPanel).toContain('h-1.5 flex-1 rounded-full transition-colors duration-200')
    expect(contextPanel).toContain("sourceState(card) === 'idle' ? 'bg-dt-bg-soft' : 'bg-primary'")
    expect(contextPanel).toContain('flex h-full items-center gap-2 rounded-lg border p-2.5 transition-all duration-300')
    expect(contextPanel).toContain('truncate text-sm font-semibold leading-5 text-highlighted')
    expect(contextPanel).toContain('mt-0.5 hidden truncate text-xs leading-4 text-muted xl:block')
    expect(contextPanel).toContain('mt-1 truncate font-mono text-xs leading-4')
    expect(contextPanel).toContain('设备实时运行指标')
    expect(contextPanel).toContain('历史趋势与运行基线')
    expect(contextPanel).toContain('设备及子系统状态')
    expect(contextPanel).toContain('运维知识与处置规范')
    expect(contextPanel).toContain('mt-3 rounded-xl border border-dt-line-strong/60 bg-dt-bg p-2.5 xl:mt-5')
    expect(contextPanel).toContain('truncate text-sm text-muted')
    expect(contextPanel).not.toContain('知识参考')
    expect(contextPanel).not.toContain('mt-auto')

    const toolsGraph = readComponent('components/product/device-agent/runtime/RuntimeToolsGraph.vue')
    const toolsHex = readComponent('components/product/device-agent/runtime/RuntimeToolsHex.vue')

    expect(toolsPanel).toContain('title="MCP 工具连接"')
    expect(toolsPanel).toContain('badge="已连接"')
    expect(toolsPanel).toContain('badge-dot')
    expect(toolsPanel).toContain('<RuntimeToolsGraph :call="activeCall" :dot="dot" />')
    expect(toolsPanel).toContain('当前工具')
    expect(toolsPanel).toContain('调用示例')
    expect(toolsPanel).toContain('CALL_MS = 3000')
    expect(toolsPanel).toContain('DOT_A_MS = 300')
    expect(toolsPanel).toContain('DOT_B_MS = 900')
    expect(toolsPanel).toContain('EXEC_MS = 1500')
    expect(toolsPanel).toContain('DONE_MS = 2200')
    expect(toolsPanel).toContain('useRuntimeTimeline(CALL_MS * calls.length)')
    expect(toolsPanel).toContain("name: 'tables.query'")
    expect(toolsPanel).toContain("name: 'device.command'")
    expect(toolsPanel).toContain("name: 'humans.approve'")
    expect(toolsPanel).toContain('查询储能柜历史时序数据')
    expect(toolsPanel).toContain('向储能柜下发运行控制指令')
    expect(toolsPanel).toContain('高风险动作请求人工确认')
    expect(toolsPanel).toContain('数据指标')
    expect(toolsPanel).toContain('温度 / SOC / 功率')
    expect(toolsPanel).toContain('采样粒度')
    expect(toolsPanel).toContain('5 min')
    expect(toolsPanel).toContain('控制动作')
    expect(toolsPanel).toContain('调整充电功率')
    expect(toolsPanel).toContain('目标功率')
    expect(toolsPanel).toContain('420 kW')
    expect(toolsPanel).toContain('执行模式')
    expect(toolsPanel).toContain('单次执行')
    expect(toolsPanel).toContain('审批事项')
    expect(toolsPanel).toContain('审批策略')
    expect(toolsPanel).toContain('人工确认')
    expect(toolsPanel).toContain('truncate font-mono text-sm font-bold text-primary')
    expect(toolsPanel).toContain('mt-3 hidden gap-2 xl:grid')
    expect(toolsPanel).toContain('flex justify-between gap-2 text-xs leading-4')
    expect(toolsPanel).toContain('完成状态')
    expect(toolsPanel).toContain('✓ {{ currentCall.done }}')
    expect(toolsPanel).toContain('tools.tables.query({ device: "ESS-01", window: "7d" })')
    expect(toolsPanel).toContain('tools.device.command({ device: "ESS-01", action: "set_power" })')
    expect(toolsPanel).toContain('tools.humans.approve({ device: "ESS-01", action: "set_power" })')
    expect(toolsPanel).toContain("running: '调用中'")
    expect(toolsPanel).toContain("running: '执行中'")
    expect(toolsPanel).toContain("running: '等待审批'")
    expect(toolsPanel).toContain("done: '已完成'")
    expect(toolsPanel).toContain("done: '已批准'")
    expect(toolsPanel).toContain('近 7 天')
    expect(toolsPanel).toContain('等待调用')
    expect(toolsPanel).toContain('执行中 ···')
    expect(toolsPanel).toContain('✓ 调用成功 · 284 ms')
    expect(toolsPanel).toContain('<template #footer>')
    expect(toolsPanel).toContain('Agent 通过 MCP 协议连接设备、数据与业务工具，在消息流中完成读取、查询、检索与执行。')

    expect(toolsGraph).toContain('grid h-full grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] gap-4 xl:gap-6')
    expect(toolsGraph).toContain('grid h-full grid-rows-3 grid-cols-[minmax(0,1fr)]')
    expect(toolsGraph).toContain('truncate text-sm font-semibold text-highlighted')
    expect(toolsGraph).toContain('truncate text-xs leading-4 text-muted')
    expect(toolsGraph).toContain('truncate font-mono text-xs leading-4 text-muted')
    expect(toolsGraph).toContain('数据平台')
    expect(toolsGraph).toContain('设备管理')
    expect(toolsGraph).toContain('企业系统')
    expect(toolsGraph).toContain('tables.query')
    expect(toolsGraph).toContain('device.command')
    expect(toolsGraph).toContain('humans.approve')
    expect(toolsGraph).toContain('relative w-24 xl:w-[150px]')
    expect(toolsGraph).toContain('viewBox="0 0 128 198"')
    expect(toolsGraph).toContain('viewBox="0 0 198 241"')
    expect(toolsGraph).toContain('-left-4 -right-4 overflow-visible xl:hidden')
    expect(toolsGraph).toContain('-left-6 -right-6 hidden overflow-visible xl:block')
    expect(toolsGraph).toContain('preserveAspectRatio="none"')
    expect(toolsGraph).toContain('vector-effect="non-scaling-stroke"')
    expect(toolsGraph).toContain('stroke-width="1"')
    expect(toolsGraph).toContain('stroke-dasharray="4 5"')
    expect(toolsGraph).toContain('stroke-linecap="round"')
    expect(toolsGraph).toContain('stroke-primary/30')
    expect(toolsGraph).toContain('stroke-primary/70')
    expect(toolsGraph).toContain('<RuntimeToolsHex :active="call !== null" />')
    expect(toolsGraph).toContain('bezierPoint')
    expect(toolsGraph).toContain(' C ')
    expect(toolsGraph).toContain('rows: [33, 99, 165]')
    expect(toolsGraph).toContain('rows: [40.2, 120.5, 200.8]')
    expect(toolsGraph).toContain('ports: [86.75, 99, 111.25]')
    expect(toolsGraph).toContain('ports: [101.5, 120.5, 139.5]')
    expect(toolsGraph).toContain('r="3"')
    expect(toolsGraph).toContain('drop-shadow-[0_0_3px_rgba(139,92,246,0.5)]')
    expect(toolsGraph).not.toContain(' H ')
    expect(toolsGraph).not.toContain(' Q ')
    expect(toolsGraph).not.toContain('<style')

    expect(toolsHex).toContain('clip-hex')
    expect(toolsHex).toContain('MCP 工具层')
    expect(toolsHex).toContain('Tools Ready')
    expect(toolsHex).toContain('<polygon')
    expect(toolsHex).toContain('viewBox="0 0 146 170"')
    expect(toolsHex).toContain('h-[143px] w-[123px]')
    expect(toolsHex).toContain('xl:h-[224px] xl:w-[193px]')
    expect(toolsHex).toContain('clip-hex relative h-[97px] w-[84px] transition-colors duration-300 xl:h-[152px] xl:w-[132px]')
    expect(toolsHex).toContain('clip-hex-inner absolute inset-px bg-dt-bg')
    expect(toolsHex).toContain('stroke-linejoin="round"')
    expect(toolsHex).toContain('font-mono text-xs leading-4 text-muted')
    expect(toolsHex).toContain('shadow-[inset_0_0_18px_rgba(139,92,246,0.15)]')
    expect(toolsHex).toContain('points="73,18.3 122.5,51.7 122.5,118.4 73,151.7 23.6,118.4 23.6,51.7"')
    expect(toolsHex).toContain('stroke-primary/16')
    expect(toolsHex).toContain('stroke-primary/12')
    expect(toolsHex).toContain('stroke-primary/8')
    expect(toolsHex).toContain("active ? 'bg-primary/45' : 'bg-primary/30'")
    expect(toolsHex).toContain("active ? 'bg-primary/15' : 'bg-primary/10'")
    expect(toolsHex).not.toContain('animate-')
    expect(toolsHex).not.toContain('<style')

    expect(skillsPanel).toContain('badge="按需加载"')
    expect(skillsPanel).toContain('ESS-01 · 电芯温度告警')
    expect(skillsPanel).toContain('收到事件')
    expect(skillsPanel).toContain('animate-ping')
    expect(skillsPanel).toContain('正在匹配 Skills...')
    expect(skillsPanel).toContain('正在挂载 Skills...')
    expect(skillsPanel).not.toContain('参数优化')
    expect(skillsPanel).toContain('Skill 挂载序列')
    expect(skillsPanel).toContain('skills.mount(')
    expect(skillsPanel).toContain('挂载中')
    expect(skillsPanel).toContain('3 Skills mounted')
    expect(skillsPanel).toContain('Agent 通过 Skills 按需挂载能力')
    expect(skillsPanel).not.toContain('热异常分析')
    expect(skillsPanel).not.toContain('处置决策')
    expect(skillsPanel).not.toContain('opacity-0')

    expect(guardrailsPanel).toContain('badge="护栏已启用"')
    expect(guardrailsPanel).toContain('待执行动作')
    expect(guardrailsPanel).toContain('420 kW')
    expect(guardrailsPanel).toContain('身份与权限')
    expect(guardrailsPanel).toContain('运行安全策略')
    expect(guardrailsPanel).toContain('ALLOW_WITH_APPROVAL')
    expect(guardrailsPanel).toContain('需人工审批')
    expect(guardrailsPanel).toContain('等待审批')
    expect(guardrailsPanel).not.toContain('opacity-0')

    expect(guardrailsSequence).toContain('安全校验')
    expect(guardrailsSequence).toContain('权限·参数·策略校验')
    expect(guardrailsSequence).toContain('人工审批确认')
    expect(guardrailsSequence).toContain('指令下发执行')
    expect(guardrailsSequence).toContain('结果验证')
    expect(guardrailsSequence).toContain('执行结果验证')
    expect(guardrailsSequence).toContain("import IconBox from '~/components/common/card/IconBox.vue'")
    expect(guardrailsSequence).toContain('<IconBox')
    expect(guardrailsSequence).not.toContain('opacity-0')

    expect(tracePanel).toContain('badge="采集中"')
    expect(tracePanel).toContain('deviceAgentTraceSteps')
    expect(tracePanel).toContain('重放本次运行')
    expect(tracePanel).toContain('@click="restart()"')

    for (const panel of [eventPanel, contextPanel, toolsPanel, skillsPanel, guardrailsPanel, tracePanel]) {
      expect(panel).not.toContain('<style')
      expect(panel).toContain('RuntimePanelShell')
      expect(panel).toContain('useRuntimeTimeline')
    }
  })

  it('assembles the device agent page sections in the required order', () => {
    const page = readComponent('pages/products/device-agent.vue')

    expect(page).toContain('<DeviceAgentArchitectureSection />')
    expect(page).toContain('<DeviceAgentValueSection />')
    expect(page).toContain('<DeviceAgentRuntimeSection />')
    expect(page.indexOf('device-agent-ecosystem-title')).toBeLessThan(page.indexOf('<DeviceAgentArchitectureSection'))
    expect(page.indexOf('<DeviceAgentArchitectureSection')).toBeLessThan(page.indexOf('<DeviceAgentValueSection'))
    expect(page.indexOf('<DeviceAgentValueSection')).toBeLessThan(page.indexOf('<DeviceAgentRuntimeSection'))
  })
  })
}
