import { expect, it } from 'vitest'
import { loadHomeVisualSources } from './context'

export function registerHomeCasesVisualContracts() {
  it('keeps HOME customer stories carousel contracts', () => {
    const {
      homeCases,
      homeCaseSlide,
      carouselRoot,
      carouselControls,
    } = loadHomeVisualSources()

    expect(homeCases).toContain('CUSTOMER STORIES')
    expect(homeCases).toContain('携手 DeepTrols 加速创新')
    expect(homeCases).toContain('助力客户加速创新、实现业务突破，同时显著降低成本。')
    expect(homeCases).toContain('SectionHeading')
    expect(homeCases).toContain('HomeCaseSlide')
    expect(homeCases).toContain('CarouselRoot')
    expect(homeCases).toContain('CarouselControls')
    expect(homeCases).toContain('title-id="cases-title"')
    expect(homeCases).toContain('nowrap-subtitle')
    expect(homeCases).toContain('max-width: 96rem')
    expect(homeCases).toContain('padding: 0 16px 128px')
    expect(homeCases).toContain('padding-bottom: 176px')
    expect(homeCases).toContain('font-size: 20px')
    expect(homeCases).toContain('white-space: nowrap')
    expect(homeCases).toContain('padding: 40px 0 0')
    expect(homeCases).toContain('cases__shell')
    expect(homeCases).toContain('overflow: hidden')
    expect(homeCases).toContain('border-radius: 24px')
    expect(homeCases).toContain('background: rgba(38, 38, 38, 0.4)')
    expect(homeCases).toContain('0 1px 2px rgba(0, 0, 0, 0.05)')
    expect(homeCases).toContain('cases__controls')
    expect(homeCases).toContain('previous-label="Previous story"')
    expect(homeCases).toContain('next-label="Next story"')
    expect(carouselControls).toContain('previousLabel')
    expect(carouselControls).toContain('nextLabel')
    expect(carouselControls).toContain('dt-icon-button')
    expect(homeCases).toContain('role="tablist"')
    expect(homeCases).toContain('cases__logo-tabs')
    expect(homeCases).toContain('gap: 40px')
    expect(homeCases).toContain('gap: 56px')
    expect(homeCases).toContain(':active-index="activeStoryIndex"')
    expect(homeCases).toContain(':item-count="storyCount"')
    expect(homeCases).toContain(':label="activeStory?.title"')
    expect(homeCases).not.toContain('cases__track')
    expect(carouselRoot).toContain('data-active-slide')
    expect(carouselRoot).toContain('transform: translate3d(-100%, 0, 0)')
    expect(carouselRoot).toContain('transform: translate3d(-200%, 0, 0)')
    expect(homeCaseSlide).toContain('min-height: 520px')
    expect(homeCaseSlide).toContain('<div class="cases__visual-overlay"></div>')
    expect(homeCaseSlide).not.toContain('<span></span>')
    expect(homeCaseSlide).not.toContain('span:nth-child')
    expect(homeCaseSlide).toContain('class="cases__button"')
    expect(homeCaseSlide).toContain(':href="story.href"')
    expect(homeCaseSlide).toContain('margin-top: auto')
    expect(homeCaseSlide).toContain('padding-top: 32px')
    expect(homeCaseSlide).toContain('BaseButton')
    expect(homeCaseSlide).toContain('variant="secondary"')
    expect(homeCaseSlide).toContain('阅读案例')
    expect(homeCases).toContain('class="cases__all-action"')
    expect(homeCases).toContain('href="/cases"')
    expect(homeCases).toContain('查看所有案例')
    expect(homeCases).toContain('margin-top: 32px')
    expect(homeCaseSlide).not.toContain('type="button"\n                          data-slot="base"')
    expect(homeCaseSlide).not.toContain('class="cases__read-link"')
    expect(homeCases).not.toContain('function readStory')
    expect(homeCases).not.toContain('navigateTo')
    expect(homeCaseSlide).not.toContain('阅读案例研究')
    expect(homeCaseSlide).not.toContain('class="cases__link"')
    expect(homeCaseSlide).toMatch(/h3 \{[\s\S]*font-size: 20px;[\s\S]*font-weight: 600;[\s\S]*line-height: 1\.25;/)
    expect(homeCaseSlide).toMatch(/\.cases__content p \{[\s\S]*font-size: 18px;[\s\S]*line-height: 1\.625;/)
    expect(homeCaseSlide).toContain('h3 {\n    font-size: 24px;\n  }')
    expect(homeCaseSlide).toContain('.cases__content p {\n    font-size: 20px;\n  }')
    expect(homeCases).not.toContain('title="CUSTOMER STORIES"')
  })
}
