import { expect, it } from 'vitest'
import { loadHomeVisualSources } from './context'

export function registerHomeEcosystemVisualContracts() {
  it('keeps HOME ecosystem visual contracts', () => {
    const {
      homeEcosystem,
      ecosystemVisual,
      ecosystemTokenVisual,
      ecosystemAgentVisual,
      ecosystemInfraVisual,
      ecosystemReportVisual,
      ecosystemVisualData,
    } = loadHomeVisualSources()

    expect(homeEcosystem).toContain('eyebrow="ecosystem"')
    expect(homeEcosystem).toContain('title="连接企业 AI 全链路的开放生态"')
    expect(homeEcosystem).toContain('subtitle="连接算力、模型、社区与行业知识，构建开放 AI 生态"')
    expect(homeEcosystem).toContain('nowrap-subtitle')
    expect(homeEcosystem).toContain('.ecosystem :deep(.section-heading__subtitle)')
    expect(homeEcosystem).toContain('font-size: 20px')
    expect(homeEcosystem).toContain('white-space: nowrap')
    expect(homeEcosystem).toContain('HomeEcosystemVisual')
    expect(homeEcosystem).toContain('class="group ecosystem-card dt-ecosystem-card"')
    expect(homeEcosystem).toContain('class="ecosystem-card__icon-box dt-icon-box"')
    expect(homeEcosystem).toContain('class="ecosystem-card__tag dt-card-tag"')
    expect(homeEcosystem).not.toContain('border-radius: var(--dt-radius-md)')
    expect(homeEcosystem).toContain(':to="card.href"')
    expect(homeEcosystem).toContain('grid-template-columns: 1fr')
    expect(homeEcosystem).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(homeEcosystem).toContain('gap: 24px')
    expect(homeEcosystem).toContain('margin-top: 48px')
    expect(homeEcosystem).toContain('width: 48px')
    expect(homeEcosystem).toContain('height: 48px')
    expect(homeEcosystem).toContain('font-size: 20px')
    expect(homeEcosystem).toContain('max-width: 75%')
    expect(homeEcosystem).toContain('font-size: 16px')
    expect(homeEcosystem).toContain('width: 32px')
    expect(homeEcosystem).toContain('height: 32px')
    expect(homeEcosystem).toContain('bottom: 32px')
    expect(homeEcosystem).toContain('opacity: 0')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__cloud-grid)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__base-line)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__flow)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__led)')
    expect(homeEcosystem).toContain(':deep(.ecosystem-visual__device-label)')
    expect(homeEcosystem).not.toContain('title="Ecosystem"')
    expect(ecosystemVisual).toContain("type EcosystemVisualVariant = 'token' | 'agent' | 'infra' | 'report'")
    expect(ecosystemVisual).toContain('ecosystem-visual--${variant}')
    expect(ecosystemVisual).toContain('visualComponents[variant]')
    expect(ecosystemVisual).toContain('EcosystemTokenVisual')
    expect(ecosystemVisual).toContain('EcosystemAgentVisual')
    expect(ecosystemVisual).toContain('EcosystemInfraVisual')
    expect(ecosystemVisual).toContain('EcosystemReportVisual')
    expect(ecosystemTokenVisual).toContain('cloudDots')
    expect(ecosystemTokenVisual).toContain('r="0.35"')
    expect(ecosystemTokenVisual).toContain('filter id="glow-map"')
    expect(ecosystemAgentVisual).toContain('filter id="edgeGlow"')
    expect(ecosystemInfraVisual).toContain('filter id="serverGlow"')
    expect(ecosystemReportVisual).toContain('filter id="bridgeGlow"')
    expect(ecosystemVisualData).toContain('x1: 105')
    expect(ecosystemVisualData).toContain('x2: 125')
    expect(ecosystemVisualData).toContain('x1: 120')
    expect(ecosystemVisualData).toContain('x2: 140')
    expect(ecosystemVisualData).toContain('x1: 80')
    expect(ecosystemVisualData).toContain('x2: 115')
    expect(ecosystemVisualData).toContain('transform: \'translate(115, 21)\'')
    expect(ecosystemVisualData).toContain('transform: \'translate(135, 45)\'')
    expect(ecosystemVisualData).toContain('transform: \'translate(105, 58)\'')
    expect(ecosystemReportVisual).toContain('论文')
    expect(ecosystemReportVisual).toContain('领域')
    expect(ecosystemVisual).toContain('top: -5px')
    expect(ecosystemVisual).toContain('right: -5%')
    expect(ecosystemVisual).toContain('top: -5%')
    expect(ecosystemVisual).toContain('height: 110%')
    expect(ecosystemVisual).toContain('width: 80%')
    expect(ecosystemVisual).toContain('width: 65%')
    expect(ecosystemAgentVisual).toContain('stroke-dasharray="1 2"')
    expect(ecosystemAgentVisual).toContain('stroke-dasharray="1 15"')
    expect(ecosystemVisual).toContain('animation-play-state: paused')
    expect(ecosystemVisual).toContain('stroke-dashoffset: 16')
    expect(ecosystemVisual).toContain('@keyframes ecosystemVisualFlow')
    expect(ecosystemVisual).toContain('@keyframes ecosystemVisualPulse')
  })
}
