import { expect, it } from 'vitest'
import { loadHomeVisualSources } from './context'

export function registerHomeFooterVisualContracts() {
  it('keeps HOME footer and flow contracts', () => {
    const {
      siteFooter,
      footerSubscribe,
      footerMain,
      footerSocials,
      footerBottom,
      footerData,
      footerMainIndex,
      footerSocialsIndex,
      footerBottomRuleIndex,
      footerSources,
      enterpriseFlow,
    } = loadHomeVisualSources()

    expect(siteFooter).toContain('class="site-footer"')
    expect(siteFooter).toContain('padding-top: 48px')
    expect(siteFooter).toContain('background: var(--dt-color-bg-soft)')
    expect(siteFooter).toContain('FooterSubscribe')
    expect(siteFooter).toContain('FooterMain')
    expect(siteFooter).toContain('FooterSocials')
    expect(siteFooter).toContain('FooterBottom')
    expect(footerSubscribe).toContain('订阅 DeepTrols 最新资讯')
    expect(footerSubscribe).toContain('data-slot="base"')
    expect(footerSubscribe).toContain('dt-button dt-button--primary dt-button--lg')
    expect(footerMain).toContain('class="site-footer__main"')
    expect(footerMain).toContain('class="site-footer__identity"')
    expect(footerMain).toContain('src="/logo-while.svg"')
    expect(footerMain).toContain('width: 240px')
    expect(footerMainIndex).toBeGreaterThan(-1)
    expect(footerSocialsIndex).toBeGreaterThan(footerMainIndex)
    expect(footerSocialsIndex).toBeLessThan(footerBottomRuleIndex)
    expect(footerSocials).toContain('class="site-footer__socials"')
    expect(footerSocials).toContain('aria-label="社交媒体"')
    expect(footerSocials).toContain('class="site-footer__social-link"')
    expect(footerData).toContain("label: 'GitHub'")
    expect(footerData).toContain("label: 'X'")
    expect(footerData).toContain("label: '哔哩哔哩'")
    expect(footerData).toContain("label: 'LinkedIn'")
    expect(footerData).toContain("label: '微信公众号'")
    expect(footerSocials).toContain('margin-top: 40px')
    expect(footerSocials).toContain('gap: 24px')
    expect(footerSocials).toContain('iconify iconify--simple-icons w-full h-6')
    expect(footerMain).toContain('class="site-footer__columns"')
    expect(footerMain).toContain('grid-template-columns: repeat(5, minmax(0, 1fr))')
    expect(footerMain).toContain('gap: 32px')
    expect(footerMain).toContain('font-size: 14px')
    expect(footerMain).toContain('line-height: 20px')
    expect(footerMain).toContain('gap: 10px')
    expect(footerMain).toContain('margin: 16px 0')
    expect(footerMain).toContain('class="site-footer__group-rule"')
    expect(footerData).toContain('产品')
    expect(footerData).toContain('数曜·数据治理平台')
    expect(footerData).toContain('数曜·数据标签平台')
    expect(footerData).toContain('数曜·数据开发平台')
    expect(footerData).toContain('数曜·数据要素监管平台')
    expect(footerData).not.toContain('数曜·数据资产管理平台')
    expect(footerData).toContain('博曜·企业级知识管理平台')
    expect(footerData).toContain('探曜·AI物联感知平台')
    expect(footerData).toContain('Device Agent')
    expect(footerData).toContain('API安全管控平台')
    expect(footerData).toContain('API安全审计系统')
    expect(footerData).toContain('业务威胁感知系统')
    expect(footerData).toContain('使用场景')
    expect(footerData).toContain('智能制造')
    expect(footerData).toContain('智能环保')
    expect(footerData).toContain('智能水利')
    expect(footerData).toContain('智慧能源')
    expect(footerData).toContain('数据治理')
    expect(footerData).toContain('企业AI应用')
    expect(footerData).toContain('智慧城市')
    expect(footerData).toContain('智慧医疗')
    expect(footerData).toContain('行业')
    expect(footerData).toContain('制造业')
    expect(footerData).toContain('能源')
    expect(footerData).toContain('交通运输与物流')
    expect(footerData).toContain('政府/公共事业')
    expect(footerData).toContain('教育')
    expect(footerData).toContain('水利/水务')
    expect(footerData).toContain('金融服务')
    expect(footerData).toContain('城市治理')
    expect(footerData).toContain('零售')
    expect(footerData).toContain('服务')
    expect(footerData).toContain('Token Hub')
    expect(footerData).toContain('白皮书&报告')
    expect(footerData).toContain('产品文档')
    expect(footerData).toContain('算力与基础设施')
    expect(footerData).toContain('智能体社区')
    expect(footerMain).toContain('translate-inline-px translate-y-[-2px] scale-inline-100 transform')
    expect(footerMain).toContain('stroke-width="1.3"')
    expect(footerData).toContain('公司')
    expect(footerData).toContain('关于我们')
    expect(footerData).toContain('新闻动态')
    expect(footerData).toContain('合作伙伴')
    expect(footerData).toContain('加入我们')
    expect(footerData).toContain('联系我们')
    expect(footerData).toContain('品牌资源')
    expect(footerData).toContain('服务案例')
    expect(footerData).toContain('投资计划')
    expect(footerBottom).toContain('class="site-footer__filings"')
    expect(footerBottom).toContain('京公网安备100861001010000号')
    expect(footerBottom).toContain('京ICP备20018888号-4')
    expect(footerBottom).toContain('https://beian.miit.gov.cn/')
    expect(footerBottom).toContain('class="site-footer__copyright"')
    expect(footerBottom).toContain('@ 武汉深度数智科技有限公司 2026 版权所有')
    expect(footerBottom).toContain('justify-content: space-between')
    expect(footerSources).not.toContain('© 2026 DeepTrols. All rights reserved')
    expect(footerSources).not.toContain('legalLinks')
    expect(footerSources).not.toContain('class="site-footer__locale"')
    expect(footerSources).not.toContain('site-footer__locale-leading')
    expect(footerSources).not.toContain('site-footer__locale-trailing')
    expect(footerSources).not.toContain('aria-label="切换语言"')
    expect(footerSources).not.toContain('primaryNavigation')
    expect(footerSources).not.toContain('flattenColumnLinks')
    expect(footerSources).not.toContain('Mail')
    expect(footerSources).not.toContain('MapPin')
    expect(footerSources).not.toContain('Phone')
    expect(enterpriseFlow).toContain('height: 100%')
    expect(enterpriseFlow).toContain('background: transparent')
    expect(enterpriseFlow).not.toContain('border: 1px solid var(--dt-color-line)')
  })
}
