import { expect, it } from 'vitest'
import { loadHomeVisualSources } from './context'

export function registerHomeHeaderVisualContracts() {
  it('keeps HOME header rhythm and navigation contracts', () => {
    const {
      header,
      siteHeaderStyles,
      headerDesktopNav,
      headerActions,
      headerMobileNav,
      headerMenuButton,
    } = loadHomeVisualSources()

    expect(siteHeaderStyles).toContain('position: fixed')
    expect(siteHeaderStyles).toContain('height: var(--dt-header-height)')
    expect(siteHeaderStyles).toContain('z-index: 1000')
    expect(siteHeaderStyles).not.toContain('margin-bottom: calc(var(--dt-header-height) * -1)')
    expect(header).toContain('data-slot="root"')
    expect(header).toContain('data-slot="container"')
    expect(header).toContain('/images/brand/deeptrols-logo-white.png')
    expect(header).toContain('/images/brand/deeptrols-logo-black.png')
    expect(header).toContain('shouldUseDarkLogo')
    expect(header).toContain('has-mega')
    expect(header).toContain('is-at-top')
    expect(siteHeaderStyles).toContain('background: transparent')
    expect(siteHeaderStyles).toContain('background: rgba(0, 0, 0, 0.4)')
    expect(siteHeaderStyles).toContain('background: rgba(255, 255, 255, 0.98)')
    expect(siteHeaderStyles).toContain('height: 35px')
    expect(siteHeaderStyles).toContain('site-header__left')
    expect(siteHeaderStyles).toContain('width: 100%')
    expect(siteHeaderStyles).not.toContain('max-width: 1600px')
    expect(siteHeaderStyles).toContain('flex: 0 1 auto')
    expect(header).toContain('SiteHeaderDesktopNav')
    expect(header).toContain('SiteHeaderActions')
    expect(header).toContain('SiteHeaderMobileNav')
    expect(header).toContain('SiteHeaderMenuButton')
    expect(header).toContain('function handleNavMouseEnter')
    expect(header).toContain('function handleNavMouseLeave')
    expect(header).not.toContain('max-width: var(--dt-container)')
    expect(header).not.toContain('@media (max-width: 1279px)')
    expect(headerActions).toContain('site-header__scheme-link')
    expect(headerActions).toContain('免费获取专属方案')
    expect(headerActions).toContain('site-header__lang-switch')
    expect(headerActions).toContain('CN')
    expect(headerActions).toContain('EN')
    expect(headerActions).toContain('width: 212px')
    expect(headerActions).toContain('height: var(--dt-header-height)')
    expect(headerActions).toContain('margin-left: auto')
    expect(headerActions).toContain('font-size: 15px')
    expect(headerActions).not.toContain('GitFork')
    expect(headerActions).not.toContain('site-header__github-icon')
    expect(headerActions).not.toContain('site-header__language-icon')
    expect(headerActions).not.toContain('登录OPS')
    expect(headerActions).not.toContain('联系我们')
    expect(headerActions).not.toContain('免费咨询')
    expect(headerDesktopNav).toContain('<div style="position:relative;">')
    expect(headerDesktopNav).toContain('justify-content: center')
    expect(headerDesktopNav).toContain('flex: 0 0 auto')
    expect(headerDesktopNav).toContain('site-header__nav-underline')
    expect(headerDesktopNav).toContain('function isActiveItem')
    expect(headerDesktopNav).toContain('margin-left: 0')
    expect(headerDesktopNav).toContain('width: 121px')
    expect(headerDesktopNav).toContain('width: 104px')
    expect(headerDesktopNav).toContain('@mouseenter="$emit(\'enter\', item, index)"')
    expect(headerDesktopNav).toContain('@mouseleave="$emit(\'leave\', item)"')
    expect(headerDesktopNav).toContain(":class=\"{ 'direct-link': !hasMega(item), active: isActiveItem(item) }\"")
    expect(headerDesktopNav).toContain('color: inherit')
    expect(headerDesktopNav).toContain('color: var(--dt-color-primary)')
    expect(headerDesktopNav).toContain('&.direct-link:hover')
    expect(headerDesktopNav).toContain('color: var(--dt-color-primary)')
    expect(headerDesktopNav).toContain('background: transparent')
    expect(headerDesktopNav).toContain('border-radius: var(--dt-ui-radius)')
    expect(headerDesktopNav).toContain('@media (max-width: 1260px)')
    expect(headerMobileNav).toContain('mobile-navigation')
    expect(headerMenuButton).toContain('Menu')
    expect(headerMenuButton).toContain('color: inherit')
  })
}
