import { expect, it } from 'vitest'
import { loadHomeVisualSources } from './context'

export function registerHomeHeroProductVisualContracts() {
  it('keeps HOME hero, deliverables, and product-system contracts', () => {
    const {
      page,
      sectionHeader,
      baseCard,
      iconBox,
      cardGrid,
      productSystemSection,
      productSystemFlowFrame,
      productSystemCards,
      hero,
      logos,
      deliverables,
      productSystem,
    } = loadHomeVisualSources()

    expect(page).not.toContain('class="home-hero-deliverables"')
    expect(page).not.toContain('class="home-hero-deliverables__video"')
    expect(page).toContain('<HomeHero />')
    expect(page).toContain('<HomeDeliverables />')
    expect(page).toContain('      <HomeDeliverables />\n      <HomeProductSystem />')
    expect(page).not.toContain('<HomeCases />')
    expect(hero).toContain('class="home-shell home-hero__content pt-40 pb-32 lg:pb-44"')
    expect(hero).toContain('aspect-ratio: 1920 / 655')
    expect(hero).toContain('url("/images/home/deepctrls-hero-ai.png")')
    expect(hero).toContain('linear-gradient(90deg, rgba(0, 0, 0, 0.55)')
    expect(hero).toContain('width: var(--dt-container)')
    expect(hero).toContain('top: clamp(78px, 10.729vw, 206px)')
    expect(hero).toContain('font-size: clamp(28px, 2.5vw, 48px)')
    expect(hero).toContain('line-height: clamp(38px, 3.75vw, 72px)')
    expect(hero).toContain('top: clamp(150px, 19.74vw, 379px)')
    expect(hero).toContain('top: clamp(205px, 24.375vw, 468px)')
    expect(hero).toContain('width: 277px')
    expect(hero).toContain('height: 47px')
    expect(hero).toContain('免费获取专属方案')
    expect(hero).not.toContain('HomeCustomerLogos')
    expect(hero).not.toContain('BaseButton')
    expect(hero).not.toContain('home-hero__wash')
    expect(hero).not.toContain('ClientOnly')
    expect(logos).toContain('padding-top: 5.5rem')
    expect(logos).toContain('gap: 4rem')
    expect(deliverables).toContain('class="section deliverables flow-root pt-32 pb-32 lg:pb-44"')
    expect(deliverables).toContain('class="container"')
    expect(deliverables).toContain('flex: 0 0 40%')
    expect(deliverables).toContain('min-height: 280px')
    expect(deliverables).toContain('padding: 48px')
    expect(deliverables).toContain('padding-right: 112px')
    expect(deliverables).toContain('linear-gradient(100deg, #ffffff 0%, #f0f5ff 100%)')
    expect(deliverables).toContain('aria-roledescription="轮播"')
    expect(deliverables).toContain('showPreviousDeliverable')
    expect(deliverables).toContain('showNextDeliverable')
    expect(deliverables).toContain('data-active-slide')
    expect(deliverables).toContain('flex: 0 0 100%')
    expect(deliverables).toContain('transform: translate3d(-100%, 0, 0)')
    expect(deliverables).toContain('transform: translate3d(-200%, 0, 0)')
    expect(deliverables).not.toContain('animation:')
    expect(deliverables).not.toContain('deliverablesCarousel')
    expect(deliverables).not.toContain('deliverablesMarquee')
    expect(deliverables).toContain('font-size: 20px')
    expect(deliverables).toContain('font-size: 24px')
    expect(deliverables).toContain('font-size: 14px')
    expect(deliverables).toContain('display: none')
    expect(deliverables).not.toContain('What We Deliver')

    expect(productSystem).toContain('eyebrow="DeepTrols OPS"')
    expect(productSystem).toContain('title="连接真实业务与人工智能"')
    expect(productSystem).toContain('以数据与知识底座桥接企业业务与人工智能。赋能 AI Agent，实现对真实业务的支撑。')
    expect(productSystem).toContain('ProductSystemSection')
    expect(productSystem).toContain('ProductSystemFlowFrame')
    expect(productSystem).not.toContain('HomeProductSystemFlow')
    expect(productSystem).not.toContain('HomeProductSystemMobileFlow')
    expect(productSystem).toContain('ProductSystemCards')
    expect(productSystem).toContain('label="DeepTrols OPS 产品架构图占位"')
    expect(productSystem).toContain('fallback-text="产品架构图占位符"')
    expect(productSystemSection).toContain('SectionShell')
    expect(productSystemSection).toContain('SectionHeader')
    expect(productSystemSection).toContain('nowrap-subtitle')
    expect(productSystemSection).toContain('subtitle-size="large"')
    expect(productSystemSection).toContain(":width=\"headingWide ? 'wide' : 'default'\"")
    expect(sectionHeader).toContain('section-heading--subtitle-large')
    expect(sectionHeader).toContain('font-size: 18px')
    expect(sectionHeader).toContain('white-space: nowrap')
    expect(productSystemSection).toContain('product-system__content')
    expect(productSystemSection).not.toContain('role="img"')
    expect(productSystemSection).not.toContain('product-system__mobile-flow')
    expect(productSystemSection).not.toContain('v-for="card in cards"')
    expect(productSystemSection).not.toContain('flowFallbackText')
    expect(productSystemSection).not.toContain('EnterpriseFlow')
    expect(productSystemFlowFrame).toContain('role="img"')
    expect(productSystemFlowFrame).toContain('height: 560px')
    expect(productSystemFlowFrame).toContain('rgba(148, 163, 184, 0.12) 1px')
    expect(productSystemFlowFrame).toContain('background-size: 48px 48px')
    expect(productSystemCards).toContain('CardGrid')
    expect(productSystemCards).toContain('BaseCard')
    expect(productSystemCards).toContain('IconBox')
    expect(productSystemCards).toContain('columns="four" gap="sm"')
    expect(productSystemCards).toContain('variant="product"')
    expect(productSystemCards).toContain('accent equal-height')
    expect(baseCard).toContain('dt-product-card')
    expect(baseCard).toContain('dt-card--adaptive')
    expect(baseCard).toContain('dt-product-card__accent')
    expect(iconBox).toContain('dt-icon-box')
    expect(cardGrid).toContain('md:grid-cols-2 lg:grid-cols-4')
    expect(productSystemCards).not.toContain('min-height')
    expect(productSystemCards).toContain('<h3>{{ card.name }}</h3>')
    expect(productSystemCards).not.toContain('{{ card.title }}')
  })
}
