import { expect, it } from 'vitest'
import { loadHomeVisualSources } from './context'

export function registerHomeInsightsCtaVisualContracts() {
  it('keeps HOME insights and CTA contracts', () => {
    const {
      ctaSection,
      homeInsights,
      homeCta,
    } = loadHomeVisualSources()

    expect(homeInsights).toContain('SectionHeading')
    expect(homeInsights).toContain('class="section insights !pt-16 lg:!pt-24"')
    expect(homeInsights).toContain('eyebrow="Resources"')
    expect(homeInsights).toContain('title="创新、洞察与新闻"')
    expect(homeInsights).toContain('title-id="insights-title"')
    expect(homeInsights).toContain('class="insights__layout"')
    expect(homeInsights).toContain('grid-template-columns: 1fr')
    expect(homeInsights).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(homeInsights).toContain('gap: 24px')
    expect(homeInsights).toContain('margin-bottom: 48px')
    expect(homeInsights).toContain('font-size: 16px')
    expect(homeInsights).toContain('class="group insights__featured"')
    expect(homeInsights).toContain('class="group insights__item"')
    expect(homeInsights).toContain('aspect-ratio: 2 / 1')
    expect(homeInsights).toContain('aspect-ratio: 400 / 180')
    expect(homeInsights).toContain('aspect-ratio: auto')
    expect(homeInsights).toContain('border-radius: var(--dt-ui-radius)')
    expect(homeInsights).toContain('border-color: var(--dt-color-line-strong)')
    expect(homeInsights).toContain('transform: scale(1.05)')
    expect(homeInsights).toContain('transition: transform 500ms ease')
    expect(homeInsights).toContain('position: absolute')
    expect(homeInsights).toContain('inset: 0')
    expect(homeInsights).toContain('object-fit: cover')
    expect(homeInsights).toContain('-webkit-line-clamp: 3')
    expect(homeInsights).toContain('-webkit-line-clamp: 2')
    expect(homeInsights).toContain('-webkit-line-clamp: 1')
    expect(homeInsights).toContain('class="insights__all-link insights__all-link--desktop"')
    expect(homeInsights).toContain('class="insights__mobile-action"')
    expect(homeInsights).toContain('BaseButton')
    expect(homeInsights).toContain('查看全部资源')
    expect(homeInsights).not.toContain('insights__topline')
    expect(homeInsights).not.toContain('transform: translateY')

    expect(homeCta).toContain('CtaSection')
    expect(homeCta).toContain('title-id="home-cta-title"')
    expect(ctaSection).toContain('home-contact-cta relative h-[314px]')
    expect(ctaSection).toContain("bg-[url('/contact-cta-banner.webp')]")
    expect(ctaSection).toContain('home-contact-cta__inner relative z-[1] mx-auto h-full w-[var(--dt-container)] max-w-none')
    expect(ctaSection).toContain('home-contact-cta__metrics absolute left-0 top-[138px] flex flex-wrap items-center gap-x-5 gap-y-2')
    expect(ctaSection).toContain('home-contact-cta__metric inline-flex h-[18px] items-center')
    expect(ctaSection).toContain('以 AI 重塑数字世界与物理世界')
    expect(ctaSection).toContain('新一代智能基础设施')
    expect(ctaSection).toContain('四大智能技术底座')
    expect(ctaSection).toContain('覆盖关键产业场景')
    expect(ctaSection).toContain('免费获取专属方案')
    expect(ctaSection).toContain('top-[78px]')
    expect(ctaSection).toContain('top-[190px]')
    expect(ctaSection).toContain('text-[clamp(24px,4.1vw,42px)]')
    expect(ctaSection).toContain('home-cta home-cta--contact home-cta--iconless absolute left-0 top-[190px]')
    expect(ctaSection).toContain('hover:shadow-[0_0_24px_rgba(118,255,155,0.22)]')
    expect(ctaSection).toContain('/images/icons/check-circle-white.svg')
    expect(ctaSection).not.toContain('<style')
    expect(ctaSection).not.toContain('class="cta-section__panel dt-cta-panel"')
    expect(ctaSection).not.toContain('class="cta-section__actions"')
    expect(ctaSection).not.toContain('BaseButton')
    expect(homeCta).not.toContain('咨询合作')
    expect(homeCta).not.toContain('申请试用')
    expect(homeCta).not.toContain('Start With DeepTrols')
    expect(homeCta).not.toContain('构建属于企业自己的 AI 能力')
  })
}
