import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../utils'

export function registerAboutVisualContracts() {
  it('renders the About Us page from the shared page baseline', () => {
    const page = readComponent('pages/about_us.vue')
    const pageHero = readComponent('components/common/PageHero.vue')
    const hero = readComponent('components/about/AboutHero.vue')
    const stats = readComponent('components/about/AboutStatsSection.vue')
    const intro = readComponent('components/about/AboutIntroSection.vue')
    const textBlock = readComponent('components/about/AboutTextBlock.vue')
    const values = readComponent('components/about/AboutValuesSection.vue')
    const address = readComponent('components/about/AboutAddressSection.vue')
    const contact = readComponent('components/about/AboutContactSection.vue')
    const data = readComponent('data/about.ts')
    const navigation = readComponent('data/navigation.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('AboutHero')
    expect(page).toContain('AboutStatsSection')
    expect(page).toContain('AboutIntroSection')
    expect(page).toContain('AboutValuesSection')
    expect(page).toContain('AboutAddressSection')
    expect(page).toContain('AboutContactSection')
    expect(page).toContain('about-page')

    expect(hero).toContain('PageHero')
    expect(hero).toContain('title-id="about-hero-title"')
    expect(hero).toContain(':title-line="aboutHero.title"')
    expect(hero).toContain(':description="aboutHero.description"')
    expect(hero).toContain(':visual-label="aboutHero.visualLabel"')
    expect(hero).toContain(':background-video-src="aboutHero.backgroundVideo"')
    expect(hero).toContain('align="center"')
    expect(hero).not.toContain('badge=')
    expect(hero).not.toContain('badge-icon')
    expect(hero).not.toContain('title-gradient')

    expect(pageHero).toContain('badge?: string')
    expect(pageHero).toContain('titleGradient?: string')
    expect(pageHero).toContain('actions?: PageHeroAction[]')
    expect(pageHero).toContain('backgroundVideoSrc?: string')
    expect(pageHero).toContain('v-if="backgroundVideoSrc"')
    expect(pageHero).toContain('class="page-hero__background-video"')
    expect(pageHero).toContain('v-if="badge"')
    expect(pageHero).toContain('v-if="titleGradient"')
    expect(pageHero).toContain('v-if="actions.length"')
    expect(pageHero).toContain('v-if="hasVisual"')
    expect(pageHero).toContain('object-fit: cover')

    expect(stats).toContain('SectionShell')
    expect(stats).toContain('HeroStatsStrip')
    expect(stats).toContain('placement="section"')
    expect(intro).toContain('SectionShell')
    expect(intro).toContain('AboutTextBlock')
    expect(textBlock).toContain('max-w-5xl text-xl leading-relaxed md:text-2xl')
    expect(textBlock).toContain('<style scoped lang="scss">')

    expect(values).toContain('我们的核心价值观')
    expect(values).toContain('这些原则指引着我们的一言一行，从产品创新到客户关系，贯穿始终。')
    expect(values).toContain('grid grid-cols-1 gap-6 md:grid-cols-3')
    expect(values).toContain('tabindex="0"')
    expect(values).toContain('translate-y-full')
    expect(values).toContain('group-hover:translate-y-0')
    expect(values).toContain('group-focus-visible:translate-y-0')
    expect(values).toContain('<style scoped lang="scss">')

    expect(address).toContain('SectionHeader')
    expect(address).toContain('title="公司地址"')
    expect(address).toContain('AboutTextBlock')

    expect(contact).toContain('联系我们')
    expect(contact).toContain('grid grid-cols-1 overflow-hidden rounded-2xl border border-default md:grid-cols-2 lg:grid-cols-3')
    expect(contact).toContain('aboutContacts.filter')
    expect(contact).toContain('<style scoped lang="scss">')

    expect(data).toContain("title: '关于深度数智（DEEPTROLS）'")
    expect(data).toContain("backgroundVideo: '/images/about/custom-rad-hero-bg-video.mp4'")
    expect(data).toContain("title: '极客'")
    expect(data).toContain("revealTitle: '技术驱动'")
    expect(data).toContain("value: 'contact@deeptrols.com'")
    expect(data).toContain("value: 'product@deeptrols.com'")
    expect(data).toContain("value: 'support@deeptrols.com'")
    expect(data).toContain("value: 'hr@deeptrols.com'")
    expect(data).toContain("label: '社交媒体'")
    expect(navigation).toContain("href: '/about_us'")
    expect(existsSync(join(root, 'public/images/about/custom-rad-hero-bg-video.mp4'))).toBe(true)
  })
}
