import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerBoyaoVisualContracts() {
  it('renders the knowledge hub flow inside the shared grid frame and unified canvas', () => {
    const architecture = readComponent('components/product/boyao/BoyaoArchitectureSection.vue')

    expect(architecture).toContain('ProductArchitectureSection')
    expect(architecture).toContain('KnowledgeHubFlow')
    expect(architecture).toContain('<ClientOnly>')
    expect(architecture).toContain('class="max-lg:hidden"')
    expect(architecture).toContain('w-full overflow-hidden @container')
    expect(architecture).toContain('scale-[min(1,calc(100cqw/1704px))]')
    expect(architecture).toContain('h-[520px] w-[1704px]')
    expect(architecture).toContain('-translate-x-1/2 -translate-y-1/2')
    expect(architecture).toContain('fallback-text="统一知识架构图加载中"')
    expect(architecture).not.toContain('<style')
  })

  it('renders the boyao integration flow inside the shared grid frame and unified canvas', () => {
    const integration = readComponent('components/product/boyao/BoyaoIntegrationSection.vue')
    const flow = readComponent('components/demo/boyao-integration/BoyaoIntegrationFlow.client.vue')

    expect(integration).toContain('ProductArchitectureSection')
    expect(integration).toContain('BoyaoIntegrationFlow')
    expect(integration).toContain('<ClientOnly>')
    expect(integration).toContain('class="max-lg:hidden"')
    expect(integration).toContain('relative z-[1] mx-auto h-full w-full overflow-hidden @container')
    expect(integration).toContain('scale-[min(1,calc(100cqw/1704px))]')
    expect(integration).toContain('h-[560px] w-[1704px]')
    expect(integration).toContain('-translate-x-1/2 -translate-y-1/2')
    expect(integration).toContain(':viewport-y="16"')
    expect(integration).toContain('label="博曜系统集成架构图"')
    expect(integration).toContain('fallback-text="系统集成架构图加载中"')
    expect(integration).not.toContain(':grid="false"')
    expect(integration).not.toContain('<style')
    expect(flow).toContain('viewportY: 26')
  })

  it('renders the boyao hero card icon boxes through the shared IconBox soft tone', () => {
    const iconBox = readComponent('components/common/card/IconBox.vue')
    const featureCard = readComponent('components/common/card/FeatureCard.vue')
    const hero = readComponent('components/product/boyao/BoyaoHero.vue')
    const heroVisual = readComponent('components/product/boyao/BoyaoHeroVisual.vue')

    expect(hero).toContain('background-image-src="/images/products/product-hero-bg.png"')
    expect(hero).toContain('class="min-h-[655px]"')
    expect(iconBox).toContain("tone?: 'primary' | 'muted' | 'white' | 'gradient' | 'soft'")
    expect(iconBox).toContain('icon-box--tone-soft')
    expect(iconBox).toContain('color-mix(in oklab, var(--dt-color-bg-soft) 50%, transparent)')
    expect(featureCard).toContain("tone?: 'primary' | 'muted' | 'white' | 'gradient' | 'soft'")
    expect(heroVisual).toContain('IconBox')
    expect(heroVisual).toContain(':size="40" tone="soft"')
    expect(heroVisual).toContain(':size="56"')
    expect(heroVisual).toContain('class="col-span-2"')
    expect(heroVisual).toContain('capabilityStyles[index]?.iconBox')
    expect(heroVisual).not.toContain('flex h-10 w-10 items-center justify-center rounded-[16px]')
    expect(heroVisual).not.toContain('flex h-14 items-center justify-center rounded-[12px]')
    expect(heroVisual).toContain('hidden w-full lg:block')
    expect(heroVisual).toContain('pointer-events-none relative ml-auto h-[520px] w-full max-w-[680px]')
    expect(heroVisual).not.toContain('max-w-2xl')
  })

  it('renders the boyao core capability section through the shared AlternatingTimelineSection', () => {
    const capability = readComponent('components/product/boyao/BoyaoCapabilitySection.vue')
    const page = readComponent('pages/products/knowledge-base.vue')
    const boyaoData = readComponent('data/boyao.ts')

    expect(capability).toContain('AlternatingTimelineSection')
    expect(capability).toContain('boyaoTimelineItems')
    expect(capability).toContain('eyebrow="核心能力"')
    expect(capability).toContain('title="让企业知识真正理解业务"')
    expect(capability).toContain('title-id="boyao-capability-title"')
    expect(capability).toContain('BoyaoCapabilityVisual')
    expect(capability).toContain('transparent-visual')
    expect(capability).toContain('<template #visual="{ index }">')
    expect(capability).not.toContain('ProductSystemSection')
    expect(boyaoData).toContain('export const boyaoTimelineItems: AlternatingTimelineItem[]')
    expect(boyaoData).not.toContain('boyaoCapabilitiesPlaceholder')
    expect(boyaoData).not.toContain('boyaoShowcases')
    expect(page).toContain('BoyaoCapabilitySection')
    expect(page).not.toContain('ServiceShowcaseSection')
    expect(page).not.toContain('boyaoShowcases')

    const capabilityVisual = readComponent('components/product/boyao/capability/BoyaoCapabilityVisual.vue')
    const parsingVisual = readComponent('components/product/boyao/capability/BoyaoMultimodalParsingVisual.vue')
    const batchVisual = readComponent('components/product/boyao/capability/BoyaoBatchParsingVisual.vue')
    const availabilityVisual = readComponent('components/product/boyao/capability/BoyaoHighAvailabilityVisual.vue')
    expect(capabilityVisual).toContain('BoyaoMultimodalParsingVisual')
    expect(capabilityVisual).toContain('BoyaoBatchParsingVisual')
    expect(capabilityVisual).toContain('BoyaoHighAvailabilityVisual')
    for (const visual of [parsingVisual, batchVisual, availabilityVisual]) {
      expect(visual).toContain('useRuntimeTimeline(6200)')
      expect(visual).toContain('flex h-full min-h-[280px] flex-col overflow-hidden rounded-2xl border border-muted bg-white shadow-[0_0_16px_rgba(15,23,42,0.08)] transition-shadow duration-500 hover:shadow-[0_0_28px_rgba(30,68,224,0.22)] lg:min-h-[360px]')
      expect(visual).toContain('flex items-center border-b border-muted px-4 py-3')
      expect(visual).toContain('size-3 rounded-full bg-red-500/70')
      expect(visual).toContain('size-3 rounded-full bg-yellow-500/70')
      expect(visual).toContain('size-3 rounded-full bg-green-500/70')
      expect(visual).not.toContain('<style')
      expect(visual).not.toContain('style=')
    }
    expect(parsingVisual).toContain('多模态解析引擎')
    expect(parsingVisual).toContain('Markdown / JSON')
    expect(batchVisual).toContain('批量解析任务')
    expect(batchVisual).toContain('100 页 / 1.5 秒')
    expect(availabilityVisual).toContain('知识服务运行中心')
    expect(availabilityVisual).toContain('99.999%')
  })

  it('renders the boyao xinchuang compatibility grid through the shared CompatibilityGridSection', () => {
    const compatibility = readComponent('components/common/CompatibilityGridSection.vue')
    const page = readComponent('pages/products/knowledge-base.vue')
    const boyaoData = readComponent('data/boyao.ts')

    expect(compatibility).toContain('SectionHeader')
    expect(compatibility).toContain('CardGrid')
    expect(compatibility).toContain('columns="three"')
    expect(compatibility).toContain('IconBox')
    expect(compatibility).toContain('export interface CompatibilityGridCategory')
    expect(compatibility).toContain('uppercase tracking-wider')
    expect(page).toContain('CompatibilityGridSection')
    expect(page).toContain('eyebrow="国产化适配"')
    expect(page).toContain('title="适配信创生态"')
    expect(page).toContain('boyaoCompatibilityCategories')
    expect(page.indexOf('<BoyaoIntegrationSection')).toBeLessThan(page.indexOf('<CompatibilityGridSection'))
    expect(boyaoData).toContain('export const boyaoCompatibilityCategories: CompatibilityGridCategory[]')
  })
}
