import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { readComponent, root } from '../utils'

export function registerCaseVisualContracts() {
  it('builds the industry cases page from the case requirement layout', () => {
    const page = readComponent('pages/cases/index.vue')
    const hero = readComponent('components/case/CaseHero.vue')
    const featured = readComponent('components/case/CaseFeaturedSection.vue')
    const resources = readComponent('components/case/CaseResourcesSection.vue')
    const card = readComponent('components/service/report/ReportResourceCard.vue')
    const data = readComponent('data/cases.ts')
    const navigation = readComponent('data/navigation.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('<CaseHero />')
    expect(page).toContain('<ProductMetricsSection :items="caseMetrics" spacing="compact" />')
    expect(page).toContain('<CaseFeaturedSection />')
    expect(page).toContain('ReportFilterBar')
    expect(page).toContain('v-model:active-filter="activeCaseFilter"')
    expect(page).toContain('v-model:search-query="caseSearchQuery"')
    expect(page).toContain('<CaseResourcesSection :items="filteredCaseResources" />')
    expect(page).toContain('cases-page')
    expect(page).toContain("title: '行业案例 - DeepTrols'")
    expect(page).toContain("item.solutionKey === activeCaseFilter.value")
    expect(page).not.toContain('<style')
    expect(page).not.toContain('style=')

    expect(hero).toContain('h-[586px]')
    expect(hero).toContain('<video')
    expect(hero).toContain(':src="caseHero.video"')
    expect(hero).toContain('autoplay')
    expect(hero).toContain('playsinline')
    expect(hero).toContain('bg-black/70')
    expect(hero).toContain('page-hero__title-block')
    expect(hero).toContain('bg-[linear-gradient(104.09deg,#1e44e0_-15.53%,#ffffff_36.62%)]')
    expect(hero).toContain('max-md:whitespace-normal')
    expect(hero).toContain('max-md:top-[250px]')
    expect(hero).toContain('page-hero__description-block')
    expect(hero).toContain('page-hero__actions')
    expect(hero).toContain('免费获取专属方案')
    expect(hero).toContain('to="/contact"')
    expect(hero).not.toContain('<style')
    expect(hero).not.toContain('style=')

    expect(featured).toContain('flow-root pb-16 lg:pb-32')
    expect(featured).toContain('aria-labelledby="case-featured-title"')
    expect(featured).toContain('grid grid-cols-1 gap-8 md:grid-cols-3')
    expect(featured).toContain('ReportResourceCard')
    expect(featured).toContain('hide-meta')
    expect(featured).toContain('caseFeatured')
    expect(featured).not.toContain('<style')
    expect(featured).not.toContain('style=')

    expect(resources).toContain('id="case-resources-panel"')
    expect(resources).toContain('flow-root pb-32 lg:pb-44')
    expect(resources).toContain('grid grid-cols-1 gap-8 md:grid-cols-3')
    expect(resources).toContain('hide-meta')
    expect(resources).toContain('暂无匹配案例')
    expect(resources).toContain('PAGE_SIZE = 6')
    expect(resources).toContain('PagerArrows')
    expect(resources).toContain('mt-10 flex justify-center md:justify-end')
    expect(resources).not.toContain('加载更多')
    expect(resources).not.toContain('load-more-link')
    expect(resources).not.toContain('<style')
    expect(resources).not.toContain('style=')

    expect(card).toContain('hideMeta?: boolean')
    expect(card).toContain('v-if="!hideMeta && item.type"')
    expect(card).toContain('v-if="!hideMeta && item.category"')

    expect(data).toContain("title: '深度数智 智能化转型实践精选'")
    expect(data).toContain("video: '/images/cases/case-hero.mp4'")
    expect(data).toContain("{ value: '100+', label: '服务客户' }")
    expect(data).toContain("{ value: '300+', label: '落地项目' }")
    expect(data).toContain("{ value: '50%-70%', label: 'AI赋能业务提效' }")
    expect(data).toContain("{ value: '10+', label: '覆盖行业' }")
    expect(data).toContain('模拟样例：案例内容清单待产品提供后整体替换')
    expect(data).toContain('export const caseResources: CaseResource[] = [')
    expect(data).toContain('export const caseFeatured = caseResources.slice(0, 3)')
    expect(data).toContain("solutionKey: 'smart-manufacturing'")
    expect(data).toContain("solutionKey: 'data-infrastructure'")
    expect(data).toContain("solutionKey: 'knowledge-engineering'")
    expect(data).toContain("solutionKey: 'smart-water'")
    expect(data).toContain("solutionKey: 'smart-education'")
    expect(data).toContain("solutionKey: 'fde'")
    expect(data).toContain("solutionKey: 'compute-power'")

    expect(navigation).toContain("href: '/cases'")
    expect(existsSync(join(root, 'public/images/cases/case-hero.mp4'))).toBe(true)
  })
}
