import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerNewsVisualContracts() {
  it('builds the news list page from the mc-* reference layout', () => {
    const page = readComponent('pages/news/index.vue')
    const hero = readComponent('components/news/NewsHero.vue')
    const tabs = readComponent('components/news/NewsCategoryTabs.vue')
    const list = readComponent('components/news/NewsListSection.vue')
    const pager = readComponent('components/common/PagerArrows.vue')
    const data = readComponent('data/news.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('<NewsHero :category="activeCategory" />')
    expect(page).toContain('<NewsCategoryTabs :active-category="activeCategory" @change="handleCategoryChange" />')
    expect(page).toContain('<NewsListSection :items="categoryItems" />')
    expect(page).toContain('news-page')
    expect(page).toContain('route.query.category')
    expect(page).toContain("title: '新闻动态 - DeepTrols'")
    expect(page).not.toContain('<style')
    expect(page).not.toContain('style=')

    expect(hero).toContain('md:h-[650px]')
    expect(hero).toContain('bg-[#111318]')
    expect(hero).toContain("bg-[url('/images/news/news-hero-bg.svg')]")
    expect(hero).toContain('class="container relative flex')
    expect(hero).toContain('md:grid-cols-[minmax(0,588fr)_minmax(0,712fr)]')
    expect(hero).toContain('md:gap-[103px]')
    expect(hero).toContain('md:pt-[223px]')
    expect(hero).toContain('text-base leading-[31px] text-justify text-[#ffffffb8]')
    expect(hero).toContain('text-[26px] font-normal leading-[38px] tracking-[1px] !text-white')
    expect(hero).toContain('md:text-[30px] md:leading-[50px]')
    expect(hero).toContain('hover:!text-[#9db2ff]')
    expect(hero).toContain('md:h-[99px]')
    expect(hero).toContain('text-lg leading-[31px] tracking-[1px] text-[#ffffffc7]')
    expect(hero).toContain('md:top-[547px]')
    expect(hero).toContain('md:w-[647.5px]')
    expect(hero).toContain('bg-[#ffffff38]')
    expect(hero).toContain("after:top-[5.5px] after:h-0.5 after:bg-white")
    expect(hero).toContain('md:mt-[186px]')
    expect(hero).toContain('md:h-[361px]')
    expect(hero).toContain('bg-[#d9d9d9]')
    expect(hero).toContain('group-hover:scale-[1.03]')
    expect(hero).toContain('AUTOPLAY_INTERVAL = 6000')
    expect(hero).toContain('getNewsByCategory')
    expect(hero).not.toContain('<style')
    expect(hero).not.toContain('style=')

    expect(tabs).toContain('shadow-[0_12px_20px_#f1f5fa]')
    expect(tabs).toContain('h-[74px]')
    expect(tabs).toContain('class="container grid h-[74px] grid-cols-3"')
    expect(tabs).toContain('grid-cols-3')
    expect(tabs).toContain('text-lg leading-[73px] text-[#969696]')
    expect(tabs).toContain('hover:text-primary')
    expect(tabs).toContain('h-1 w-[263px] max-w-full -translate-x-1/2 bg-primary')
    expect(tabs).not.toContain('<style')
    expect(tabs).not.toContain('style=')

    expect(list).toContain('md:pt-[138px]')
    expect(list).toContain('class="container pb-16 md:pb-[91px]"')
    expect(list).toContain('md:pb-[91px]')
    expect(list).toContain('md:grid-cols-[minmax(0,855fr)_minmax(0,484fr)]')
    expect(list).toContain('md:gap-x-[61px]')
    expect(list).toContain('md:pt-[11px]')
    expect(list).toContain('border-b border-[#e7eaef] pb-8 mb-8')
    expect(list).toContain('text-[22px] font-normal leading-10 tracking-[1px] !text-[#2d2d2d]')
    expect(list).toContain('hover:!text-primary')
    expect(list).toContain('leading-[26px] text-[#555]')
    expect(list).toContain('mt-1.5 text-base leading-[31px] text-[#2d2d2d]')
    expect(list).toContain('rounded-[6px]')
    expect(list).toContain('shadow-[0_4px_16px_#1d22341a]')
    expect(list).toContain('hover:shadow-[0_10px_28px_#1d223429]')
    expect(list).toContain('group-hover:scale-[1.04]')
    expect(list).toContain('md:h-[246px]')
    expect(list).toContain('PAGE_SIZE = 5')
    expect(list).toContain('PagerArrows')
    expect(list).toContain('md:justify-end')
    expect(list).toContain('text-[#68758c]')
    expect(list).not.toContain('<style')
    expect(list).not.toContain('style=')

    expect(pager).toContain('size-[49px]')
    expect(pager).toContain('gap-[17px]')
    expect(pager).toContain('ArrowRight')
    expect(pager).toContain('rotate-180')
    expect(pager).toContain('disabled:opacity-45')
    expect(pager).toContain("prev: []")
    expect(pager).toContain("next: []")
    expect(pager).not.toContain('<style')
    expect(pager).not.toContain('style=')

    expect(data).toContain('export type NewsCategory = \'company\' | \'media\' | \'insight\'')
    expect(data).toContain('export const newsItems: NewsItem[] = [')
    expect(data).toContain('模拟样例')
    expect(data).toContain("{ key: 'company', label: '公司动态' }")
    expect(data).toContain("{ key: 'media', label: '新闻报道' }")
    expect(data).toContain("{ key: 'insight', label: '技术洞见' }")
    expect(data).toContain('export function getNewsByCategory(category: NewsCategory)')
    expect(data).toContain("coverImage: COVER_PLACEHOLDER")
  })
}
