import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerNewsDetailVisualContracts() {
  it('builds the news detail page from the ma-* reference layout', () => {
    const page = readComponent('pages/news/[id].vue')
    const aside = readComponent('components/news/NewsRelatedAside.vue')
    const card = readComponent('components/news/NewsRelatedCard.vue')
    const content = readComponent('components/common/article/ArticleContent.vue')
    const header = readComponent('components/navigation/SiteHeader.vue')
    const data = readComponent('data/news-details.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('<ArticleBreadcrumb :items="breadcrumbItems" />')
    expect(page).toContain('news-detail-page bg-white bg-[linear-gradient(180deg,#eff5fe,transparent)] bg-[length:100%_1134px] bg-no-repeat')
    expect(page).toContain('grid grid-cols-1 gap-18 pt-12 pb-24 xl:grid-cols-[minmax(0,1fr)_376px] xl:gap-[124px]')
    expect(page).toContain("label: '新闻动态', href: '/news'")
    expect(page).toContain("label: '文章正文'")
    expect(page).toContain('h-[30px] w-[104px] place-items-center rounded-[44px] bg-primary/8 text-sm font-medium text-primary')
    expect(page).toContain('text-[30px] font-normal leading-[44px] text-[#1d2234] md:text-[48px] md:leading-[57px]')
    expect(page).toContain('发布时间: {{ formatNewsDateShort(newsItem.publishedAt) }}')
    expect(page).toContain('mt-[34px] block h-px bg-[#d9dde4]')
    expect(page).toContain('mt-10 md:mt-[66px]')
    expect(page).toContain('<ArticleContent :blocks="detail.blocks" variant="news" />')
    expect(page).toContain('xl:pt-[261px]')
    expect(page).toContain('<CtaSection />')
    expect(page).toContain('statusCode: 404')
    expect(page).toContain('createError')
    expect(page).not.toContain('<style')
    expect(page).not.toContain('style=')

    expect(aside).toContain('相关动态')
    expect(aside).toContain('text-[38px] font-normal leading-[42px] text-[#1d2234] max-md:text-[28px] max-md:leading-[34px]')
    expect(aside).toContain('GROUP_SIZE = 3')
    expect(aside).toContain('item.id !== props.currentId')
    expect(aside).toContain("index === 0 ? 'mt-[43px]' : 'mt-[42px]'")
    expect(aside).toContain('PagerArrows')
    expect(aside).toContain('mt-10 flex justify-start xl:mt-20 xl:justify-end')
    expect(aside).toContain('text-[#8a8a8a]')
    expect(aside).not.toContain('<style')
    expect(aside).not.toContain('style=')

    expect(card).toContain('h-[213px]')
    expect(card).toContain('bg-[#8a8a8a]')
    expect(card).toContain('group-hover:scale-[1.04]')
    expect(card).toContain('line-clamp-2 mt-[22px] block h-[50px] text-justify text-base font-light leading-[25px]')
    expect(card).toContain('group-hover:text-primary')
    expect(card).toContain('mt-3 block text-[15px] font-light leading-[26px] text-[#555]')
    expect(card).toContain('formatNewsDateShort')
    expect(card).not.toContain('<style')
    expect(card).not.toContain('style=')

    // ArticleContent variant 改造不得触及 case 分支既有字面量
    expect(content).toContain("variant?: 'case' | 'news'")
    expect(content).toContain("variant: 'case'")
    expect(content).toContain('text-base leading-[30px] text-justify text-[#1d2234]')
    expect(content).toContain("'first:mt-0 mb-5 mt-14 text-left text-[26px] font-medium leading-[38px] text-[#1d2234]'")
    expect(content).toContain('mb-12 list-disc pl-[26px] marker:text-primary')
    expect(content).toContain('my-12 h-px bg-[#e2e2e2]')
    expect(content).toContain('text-base leading-[30px] text-justify text-[#555] max-md:text-left max-md:leading-7')
    expect(content).toContain("'mb-[30px]'")
    expect(content).toContain('mb-[30px] list-disc pl-[26px] marker:text-primary')
    expect(content).toContain('my-12 h-px bg-[#d9dde4]')
    expect(content).not.toContain('<style')
    expect(content).not.toContain('style=')

    expect(header).toContain('isNewsDetailRoute')
    expect(header).toContain("route.path.startsWith('/news/')")

    expect(data).toContain('export const newsDetails: NewsDetail[] = [')
    expect(data).toContain('export function getNewsDetailById(id: number)')
    expect(data).toContain('模拟样例')
    expect(data).toContain("text: '算电协同进入新基建阶段'")
  })
}
