import { expect, it } from 'vitest'
import { readComponent } from '../utils'

export function registerReportVisualContracts() {
  it('renders the report service page with the required resources layout', () => {
    const page = readComponent('pages/resources/reports.vue')
    const hero = readComponent('components/service/report/ReportHero.vue')
    const featured = readComponent('components/service/report/ReportFeaturedSection.vue')
    const filter = readComponent('components/service/report/ReportFilterBar.vue')
    const section = readComponent('components/service/report/ReportResourcesSection.vue')
    const card = readComponent('components/service/report/ReportResourceCard.vue')
    const data = readComponent('data/reports.ts')
    const navigation = readComponent('data/navigation.ts')
    const footer = readComponent('data/footer.ts')
    const requirement = readComponent('doc/product/PAGE_REQUIREMENTS/SERVICE/REPORT/report.md')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('ReportHero')
    expect(page).toContain('ReportFeaturedSection')
    expect(page).toContain('ReportFilterBar')
    expect(page).toContain('ReportResourcesSection')
    expect(page.indexOf('<ReportHero')).toBeLessThan(page.indexOf('<ReportFeaturedSection'))
    expect(page.indexOf('<ReportFeaturedSection')).toBeLessThan(page.indexOf('<ReportFilterBar'))
    expect(page.indexOf('<ReportFilterBar')).toBeLessThan(page.indexOf('<ReportResourcesSection'))
    expect(page).toContain('v-model:active-filter="activeReportFilter"')
    expect(page).toContain('v-model:search-query="reportSearchQuery"')
    expect(page).toContain(':items="filteredReportResources"')
    expect(page).toContain('report-page')
    expect(page).toContain("title: '白皮书&报告 - DeepTrols'")
    expect(page).toContain("description: '全球最新的AI相关白皮书&报告，深入了解人工智能的世界。'")

    expect(hero).toContain('PageHero')
    expect(hero).toContain('title-id="report-hero-title"')
    expect(hero).toContain(':title-line="reportHero.title"')
    expect(hero).toContain(':description="reportHero.description"')
    expect(hero).toContain('align="center"')
    expect(hero).toContain('padding-top: 8.5rem')
    expect(hero).toContain('padding-bottom: 4rem')
    expect(hero).toContain('padding-top: 9.5rem')
    expect(hero).toContain('padding-bottom: 5rem')
    expect(hero).toContain('font-size: 24px')
    expect(hero).toContain('font-size: 48px')

    expect(featured).toContain('class="container pb-16 md:pb-20"')
    expect(featured).toContain('aria-labelledby="report-featured-title"')
    expect(featured).toContain('featuredReportResources')
    expect(featured).toContain('class="grid grid-cols-1 gap-8 md:grid-cols-3"')
    expect(featured).toContain(':eager="index === 0"')

    expect(filter).toContain('role="tablist"')
    expect(filter).toContain('class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8"')
    expect(filter).toContain('class="flex gap-4 flex-wrap"')
    expect(filter).toContain('text-sm font-medium text-toned cursor-pointer whitespace-nowrap flex min-h-10 px-4 justify-center items-center rounded-full border border-solid border-accented transition-all')
    expect(filter).toContain('text-highlighted border-primary')
    expect(filter).toContain('placeholder="搜索"')
    expect(filter).toContain('data-slot="root"')
    expect(filter).toContain('data-slot="leadingIcon"')
    expect(filter).toContain("emit('update:searchQuery'")

    expect(section).toContain('class="container pb-32"')
    expect(section).toContain('class="mb-24"')
    expect(section).toContain('class="grid grid-cols-1 gap-8 md:grid-cols-3"')
    expect(section).toContain('ReportResourceCard')
    expect(section).toContain('items: ReportResource[]')
    expect(section).toContain(':eager="index === 0"')

    expect(card).toContain('class="group block"')
    expect(card).toContain('class="relative mb-4 aspect-[400/180] overflow-hidden rounded-lg"')
    expect(card).toContain('absolute left-3 top-3 z-10 inline-flex')
    expect(card).toContain('rounded-full bg-violet-500 px-2.5 py-0.5 text-sm text-white')
    expect(card).toContain('width="400"')
    expect(card).toContain('height="180"')
    expect(card).toContain(':loading="eager ? \'eager\' : \'lazy\'"')
    expect(card).toContain('class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"')
    expect(card).toContain('text-xl font-semibold leading-snug text-highlighted')
    expect(card).not.toContain('style=')

    expect(data).toContain("title: '白皮书&报告'")
    expect(data).toContain("description: '全球最新的AI相关白皮书&报告，深入了解人工智能的世界。'")
    expect(data).toContain('reportFilterTabs')
    expect(data).toContain('featuredReportResources')
    expect(data).toContain("{ key: 'all', label: '全部' }")
    expect(data).toContain("{ key: '产品规格书', label: '产品规格书' }")
    expect(data).toContain("{ key: '电子书', label: '电子书' }")
    expect(data).toContain("{ key: '白皮书', label: '白皮书' }")
    expect(data).toContain("{ key: '视频', label: '视频' }")
    expect(data).toContain("{ key: '幻灯片', label: '幻灯片' }")
    expect(data).toContain("{ key: '基准测试报告', label: '基准测试报告' }")
    expect(data).toContain("type: '产品规格书'")
    expect(data).toContain("type: '白皮书'")
    expect(data).toContain("type: '视频'")
    expect(data).toContain("type: '幻灯片'")
    expect(data).toContain("type: '基准测试报告'")
    expect(data).toContain("image: '/images/home/solutions/data-center-ai.CDu93Miw.png'")
    expect(data).not.toContain('doc/product/PAGE_REQUIREMENTS')
    expect(navigation).toContain("href: '/resources/reports'")
    expect(footer).toContain("href: '/resources/reports'")
    expect(requirement).toContain('白皮书&报告 页面结构')
  })
}
