import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { whyTrustTabs } from '../../../data/why'
import { readComponent, root } from '../utils'

export function registerWhyVisualContracts() {
  it('keeps the Why DeepTrols page on the shared HOME baseline', () => {
    const page = readComponent('pages/why-deeptrols.vue')
    const pageHero = readComponent('components/common/PageHero.vue')
    const heroLogoStrip = readComponent('components/common/HeroLogoStrip.vue')
    const trustTabsSection = readComponent('components/common/TrustTabsSection.vue')
    const serviceShowcaseSection = readComponent('components/common/ServiceShowcaseSection.vue')
    const engineLinksSection = readComponent('components/common/EngineLinksSection.vue')
    const sectionShell = readComponent('components/common/section/SectionShell.vue')
    const baseCard = readComponent('components/common/card/BaseCard.vue')
    const iconBox = readComponent('components/common/card/IconBox.vue')
    const cardGrid = readComponent('components/common/card/CardGrid.vue')
    const featureCard = readComponent('components/common/card/FeatureCard.vue')
    const cardText = readComponent('components/common/card/CardText.vue')
    const baseTabs = readComponent('components/common/tabs/BaseTabs.vue')
    const hero = readComponent('components/why/WhyHero.vue')
    const heroLogos = readComponent('components/why/WhyHeroLogos.vue')
    const heroVisual = readComponent('components/why/WhyHeroVisual.vue')
    const heroAnimation = readComponent('components/why/useWhyHeroAnimation.ts')
    const tailwindCss = readComponent('assets/css/tailwind.css')
    const tabs = readComponent('components/why/WhyTrustTabs.vue')
    const service = readComponent('components/why/WhyServiceReset.vue')
    const engine = readComponent('components/why/WhyEngine.vue')
    const data = readComponent('data/why.ts')

    expect(page).toContain('SiteHeader')
    expect(page).toContain('SiteFooter')
    expect(page).toContain('WhyHero')
    expect(page).toContain('WhyHeroLogos')
    expect(page).toContain('WhyTrustTabs')
    expect(page).toContain('WhyServiceReset')
    expect(page).toContain('WhyEngine')
    expect(page).toContain('CtaSection')
    expect(page).toContain('whyCtaActions')
    expect(hero).toContain('PageHero')
    expect(hero).toContain('import { Sparkles }')
    expect(hero).toContain('badge="为什么选择 DeepTrols"')
    expect(hero).toContain('title-id="why-hero-title"')
    expect(hero).toContain('title-line="数据、知识、智能统一"')
    expect(hero).toContain('title-gradient="企业级AI应用服务商"')
    expect(hero).toContain('visual-size="large"')
    expect(hero).not.toContain('HomeCustomerLogos')
    expect(hero).not.toContain('why-hero__logos')
    expect(heroLogos).toContain('HeroLogoStrip')
    expect(heroLogos).toContain('HomeCustomerLogos')
    expect(hero).toContain('flush-bottom')
    expect(heroLogoStrip).toContain('class="container"')
    expect(heroLogoStrip).toContain('class="hero-logo-strip__inner mt-24 border-t border-dt-line pt-12 lg:mt-28"')
    expect(heroLogoStrip).toContain('padding-bottom: 96px')
    expect(heroLogoStrip).toContain('padding-bottom: 128px')
    expect(pageHero).toContain('class="page-hero relative overflow-hidden"')
    expect(pageHero).toContain('container page-hero__body relative isolate pt-24 lg:pt-32')
    expect(pageHero).toContain('class="page-hero__body-bg absolute inset-0 z-0 bg-dt-bg"')
    expect(pageHero).toContain('class="page-hero__background" aria-hidden="true"')
    expect(pageHero).toContain('page-hero__inner relative z-10 flex flex-col items-center')
    expect(pageHero).toContain('width: 100vw')
    expect(pageHero).toContain('transform: translateX(-50%)')
    expect(pageHero).toContain('z-index: 1')
    expect(pageHero).toContain("flushBottom ? 'pb-0 lg:pb-0' : 'pb-24 lg:pb-32'")
    expect(pageHero).toContain('page-hero__content w-full text-center')
    expect(pageHero).toContain("align === 'center' ? 'max-w-4xl' : 'max-w-2xl lg:self-center lg:text-left'")
    expect(pageHero).toContain('page-hero__actions flex flex-wrap items-center justify-center gap-4')
    expect(pageHero).toContain("align === 'center' ? '' : 'lg:justify-start'")
    expect(pageHero).not.toContain('padding: 144px')
    expect(pageHero).not.toContain('padding: 144px 0 96px')
    expect(pageHero).not.toContain('padding-bottom: 112px')
    expect(pageHero).toContain('font-size: 36px')
    expect(pageHero).toContain('font-size: 48px')
    expect(pageHero).toContain('font-size: 60px')
    expect(pageHero).toContain('line-height: 1.1')
    expect(pageHero).toContain('margin: 0 auto 32px')
    expect(hero).toContain('立即咨询')
    expect(hero).toContain('关于我们')
    expect(pageHero).toContain('BaseButton')
    expect(hero).toContain('WhyHeroVisual')
    expect(hero).not.toContain('<video')
    expect(hero).not.toContain('robot.webm')
    expect(hero).not.toContain('new URL(')
    expect(pageHero).toContain('background-size: 72px 72px')
    expect(pageHero).toContain('max-w-[820px]')
    expect(pageHero).toContain('self-stretch')
    expect(hero).toContain('lg:h-full')
    expect(hero).toContain('max-w-[728px]')
    expect(hero).not.toContain('&::after')
    expect(hero).not.toContain('linear-gradient(180deg, var(--dt-color-bg) 0%')
    expect(hero).not.toContain('linear-gradient(90deg, var(--dt-color-bg) 0%')
    expect(pageHero).toContain('lg:grid-cols-[minmax(0,0.88fr)_minmax(520px,1fr)]')
    expect(hero).not.toContain('video {')
    expect(hero).not.toContain('box-shadow: 0 24px 60px')
    expect(heroVisual).toContain('viewBox="0 0 560 480"')
    expect(heroVisual).toContain('whyHeroNodes')
    expect(heroVisual).toContain('whyHeroCenterLogo')
    expect(heroVisual).toContain('useWhyHeroAnimation')
    expect(heroVisual).toContain('animate-why-node-pulse')
    expect(heroVisual).toContain('animate-why-center-pulse')
    expect(heroVisual).toContain('preserveAspectRatio="xMidYMid meet"')
    expect(heroVisual).toContain('rx="16"')
    expect(heroVisual).toContain('why-hv-hub-ring')
    expect(heroVisual).not.toContain('hubRingArcs')
    expect(heroVisual).toContain('fill-[var(--dt-color-bg-elevated)]')
    expect(heroAnimation).toContain('ROTATE_DURATION_MS = 800')
    expect(heroAnimation).toContain('SETTLE_DELAY_MS = 200')
    expect(heroAnimation).toContain('MESSAGE_DURATION_MS = 900')
    expect(heroAnimation).toContain('HOLD_DURATION_MS = 400')
    expect(heroAnimation).toContain('START_DELAY_MS = 400')
    expect(heroAnimation).toContain('INITIAL_ROTATION_DEG = 270')
    expect(heroAnimation).toContain('ROTATION_STEP_DEG = 90')
    expect(heroAnimation).toContain('ORBIT_RADIUS = 150')
    expect(tailwindCss).toContain('--animate-why-node-pulse')
    expect(tailwindCss).toContain('--animate-why-center-pulse')
    expect(data).toContain('whyHeroNodes')
    expect(data).toContain('whyHeroCenterLogo')
    expect(data).toContain('shuyao-logo.svg?url')
    expect(data).toContain('boyao-logo.svg?url')
    expect(data).toContain('tanyao-iot-logo.svg?url')
    expect(data).toContain('zhiyao-logo.svg?url')
    expect(data).toContain("whyHeroCenterLogo = '/logo-while.svg'")
    expect(tabs).toContain('TrustTabsSection')
    expect(tabs).toContain('为什么DeepTrols值得信赖')
    expect(trustTabsSection).toContain('SectionShell')
    expect(trustTabsSection).toContain('SectionHeader')
    expect(trustTabsSection).toContain('BaseTabs')
    expect(trustTabsSection).toContain('CardGrid')
    expect(trustTabsSection).toContain('BaseCard')
    expect(trustTabsSection).toContain('IconBox')
    expect(sectionShell).toContain('pb-32 lg:pb-44')
    expect(baseTabs).toContain('role="tablist"')
    expect(baseTabs).toContain('role="tab"')
    expect(trustTabsSection).toContain('role="tabpanel"')
    expect(trustTabsSection).toContain('mb-12 text-center lg:mb-16')
    expect(baseTabs).toContain('dt-segmented-tabs')
    expect(baseTabs).toContain('dt-segmented-tab')
    expect(cardGrid).toContain('gap-5 lg:gap-6')
    expect(cardGrid).toContain('md:grid-cols-2')
    expect(trustTabsSection).toContain('variant="product"')
    expect(trustTabsSection).toContain('equal-height')
    expect(trustTabsSection).toContain('!p-7 lg:!p-8')
    expect(baseCard).toContain('dt-product-card')
    expect(baseCard).toContain('dt-card--adaptive')
    expect(trustTabsSection).not.toContain('min-h-[280px]')
    expect(iconBox).toContain('dt-icon-box')
    expect(trustTabsSection).not.toContain('!rounded-xl')
    expect(trustTabsSection).toContain(':size="40"')
    expect(trustTabsSection).toContain(':icon-size="20"')
    expect(trustTabsSection).toContain('font-size: 24px')
    expect(trustTabsSection).toContain('font-size: 18px')
    expect(trustTabsSection).not.toContain('dt-tab-list')
    expect(trustTabsSection).not.toContain('class="dt-tab"')
    expect(trustTabsSection).not.toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(serviceShowcaseSection).toContain('SectionHeader')
    expect(serviceShowcaseSection).toContain('FeatureCard')
    expect(engineLinksSection).toContain('SectionHeader')
    expect(engineLinksSection).toContain('BaseCard')
    expect(engineLinksSection).toContain('CardText')
    expect(engineLinksSection).toContain('IconBox')
    expect(service).toContain('业务价值可衡量，AI成果可持续')
    expect(service).toContain('ServiceShowcaseSection')
    expect(service).toContain('fangangaishu.png?url')
    expect(service).not.toContain('new URL(')
    expect(serviceShowcaseSection).toContain('SectionHeader')
    expect(serviceShowcaseSection).toContain('variant="soft"')
    expect(featureCard).toContain(':variant="variant"')
    expect(baseCard).toContain('dt-card--soft')
    expect(serviceShowcaseSection).not.toContain('transform: translateY(-4px)')
    expect(serviceShowcaseSection).not.toContain('border-color: rgba(94, 78, 255, 0.4)')
    expect(serviceShowcaseSection).not.toContain('border-radius: 24px')
    expect(engine).toContain('重塑引擎')
    expect(engine).toContain('whyEngineLinks')
    expect(engine).toContain('EngineLinksSection')
    expect(engineLinksSection).toContain('SectionHeader')
    expect(engineLinksSection).toContain('variant="soft"')
    expect(engineLinksSection).toContain('tone="white"')
    expect(baseCard).toContain('dt-card--soft')
    expect(cardText).toContain('card-text__title')
    expect(engineLinksSection).not.toContain('transform: translateY(-4px)')
    expect(engineLinksSection).not.toContain('border-color: rgba(94, 78, 255, 0.4)')
    expect(engineLinksSection).not.toContain('border-radius: 24px')
    expect(data).toContain("label: '面向技术层'")
    expect(data).toContain("label: '面向业务层'")
    expect(data).toContain("label: '面向服务层'")
    expect(data).toContain("label: '面向长期价值'")
    expect(whyTrustTabs).toHaveLength(4)
    expect(whyTrustTabs.every((tab) => tab.features.length === 4)).toBe(true)
    expect(data).toContain('DeepTrolsOPS企业AI引擎')
    expect(data).toContain('FDE企业AI服务指南')
    expect(existsSync(join(root, 'public/logo-while.svg'))).toBe(true)
    expect(existsSync(join(root, 'assets/images/brand/shuyao-logo.svg'))).toBe(true)
    expect(existsSync(join(root, 'assets/images/brand/boyao-logo.svg'))).toBe(true)
    expect(existsSync(join(root, 'assets/images/brand/tanyao-iot-logo.svg'))).toBe(true)
    expect(existsSync(join(root, 'assets/images/brand/zhiyao-logo.svg'))).toBe(true)
    expect(existsSync(join(root, 'assets/images/why/fangangaishu.png'))).toBe(true)
  })
}
